Repository fetchai/ledger, pull requests merged in 2019-06, with the labels that each got.

#1121 Minibatching for optimisers and graph trainable lookup
  libs/ml/examples/word2vec_SGNS/main.cpp
  libs/ml/include/ml/graph.hpp
  libs/ml/include/ml/ops/weights.hpp
  libs/ml/include/ml/optimisation/adagrad_optimiser.hpp
  libs/ml/include/ml/optimisation/adam_optimiser.hpp
  libs/ml/include/ml/optimisation/momentum_optimiser.hpp
  libs/ml/include/ml/optimisation/optimiser.hpp
  libs/ml/include/ml/optimisation/rmsprop_optimiser.hpp
  libs/ml/include/ml/optimisation/sgd_optimiser.hpp
  libs/ml/tests/ml/ops/embeddings.cpp
  libs/ml/tests/ml/ops/graph.cpp
  libs/ml/tests/ml/optimisation/optimisers.cpp
Labels: A-ml, S-ready-for-review

#1141 Implement String split member function
  libs/vm/include/vm/string.hpp
  libs/vm/src/module.cpp
  libs/vm/src/string.cpp
  libs/vm_modules/src/core/print.cpp
  libs/vm_modules/tests/unit/print_tests.cpp
  libs/vm_modules/tests/unit/string_tests.cpp
Labels: S-ready-for-review

#1146 Add version checks and error handling to style check
  scripts/apply_style.py
Labels: S-ready-for-review

#1149 Disable unreliable tests
  cmake/BuildTools.cmake
  libs/core/tests/CMakeLists.txt
  libs/network/tests/CMakeLists.txt
Labels: S-ready-for-review

#1123 Add GCC 8 and Clang 7 to build
  Jenkinsfile
  cmake/BuildTargets.cmake
  libs/core/include/core/byte_array/const_byte_array.hpp
  libs/ml/include/ml/optimisation/optimiser.hpp
Labels: S-ready-for-review

#1098 Feature/fixedpoint trig functions
  libs/math/include/math/kernels/trigonometry.hpp
  libs/math/include/math/standard_functions/fmod.hpp
  libs/math/include/math/trigonometry.hpp
  libs/math/tests/math/all_tests/fixed_point/fixed_point.cpp
  libs/ml/tests/ml/ops/tanh.cpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
  libs/vm_modules/include/vm_modules/math/abs.hpp
  libs/vm_modules/include/vm_modules/math/trigonometry.hpp
Labels: A-maths, C-feature, S-ready-for-review

#1148 Block timestamps
  libs/ledger/include/ledger/chain/block.hpp
  libs/ledger/src/chain/block.cpp
  libs/ledger/src/testing/block_generator.cpp
  libs/ledger/tests/chain/main_chain_tests.cpp
  libs/miner/src/basic_miner.cpp
  libs/network/include/network/p2pservice/p2p_http_interface.hpp
Labels: S-ready-for-review

#1169 Fixed graph trainable naming issue
  libs/ml/include/ml/graph.hpp
Labels: A-ml, S-ready-for-review

#1173 [VM] Fix for segfault when serialising null-ref `Ptr<Object>` objects
  libs/vm/include/vm/object.hpp
  libs/vm/include/vm/state.hpp
  libs/vm/include/vm/variant.hpp
  libs/vm_modules/tests/unit/array_tests.cpp
  libs/vm_modules/tests/unit/fake_io_observer.cpp
  libs/vm_modules/tests/unit/fake_io_observer.hpp
  libs/vm_modules/tests/unit/print_tests.cpp
  libs/vm_modules/tests/unit/state_tests.cpp
  libs/vm_modules/tests/unit/string_tests.cpp
  libs/vm_modules/tests/unit/vm_test_toolkit.hpp
Labels: C-bug, P-high, S-ready-for-review

#1174 simplified mnist example
  libs/ml/examples/mnist/main.cpp
  libs/ml/include/ml/ops/activation.hpp
Labels: S-ready-for-review

#1183 [VM] Refact. of `State` & `ShardedState` (droping default constr. value)
  libs/ledger/tests/chaincode/smart_contract_tests.cpp
  libs/vm/include/vm/object.hpp
  libs/vm/include/vm/sharded_state.hpp
  libs/vm/include/vm/state.hpp
  libs/vm/src/module.cpp
  libs/vm/src/sharded_state.cpp
  libs/vm/src/state.cpp
  libs/vm_modules/tests/unit/state_tests.cpp
  scripts/end_to_end_test/smart_contract_tests/block_number.py
Labels: C-refactor, P-high, S-ready-for-review

#1166 Commodity prediction example
  libs/ml/examples/commodity_prediction/main.cpp
  libs/ml/examples/file_loader.hpp
  libs/ml/include/ml/ops/activation.hpp
Labels: S-ready-for-review

#1179 DataLoader Cleanup
  libs/ml/examples/asynchronous_distributed_learning/main.cpp
  libs/ml/examples/cbow_simple/w2v_cbow_dataloader.hpp
  libs/ml/examples/centralised_distributed_learning/main.cpp
  libs/ml/examples/commodity_prediction/main.cpp
  libs/ml/examples/decentralised_distributed_learning/main.cpp
  libs/ml/include/ml/dataloaders/code2vec_context_loaders/context_loader.hpp
  libs/ml/include/ml/dataloaders/dataloader.hpp
  libs/ml/include/ml/dataloaders/mnist_loaders/mnist_loader.hpp
  libs/ml/include/ml/dataloaders/tensor_dataloader.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/basic_textloader.hpp
  libs/ml/include/ml/optimisation/optimiser.hpp
  libs/ml/tests/ml/dataloader/tensor_dataloader.cpp
  libs/python/include/python/ml/dataloaders/py_cbow_loader.hpp
Labels: S-ready-for-review

#1170 updated quickstart script to not require sudo
  scripts/quickstart.sh
Labels: S-ready-for-review

#1201 [CI] Improvement of `--only-these-files` arg. handling
  scripts/run_static_analysis.py
Labels: C-improvement, P-low, S-ready-for-review

#1132 Sgns simple
  libs/math/include/math/clustering/knn.hpp
  libs/math/include/math/correlation/cosine.hpp
  libs/math/include/math/tensor.hpp
  libs/math/tests/math/all_tests/clustering/knn_test.cpp
  libs/ml/examples/cbow_simple/main.cpp
  libs/ml/examples/cbow_simple/unigram_table.hpp
  libs/ml/examples/cbow_simple/w2v_cbow_dataloader.hpp
  libs/ml/examples/word2vec_simple/main.cpp
  libs/ml/examples/word2vec_simple/polyfill.hpp
  libs/ml/examples/word2vec_simple/w2v_model.hpp
  libs/ml/examples/word2vec_simple/word_analogy.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/unigram_table.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/vocab.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/w2v_dataloader.hpp
Labels: A-ml, S-ready-for-review

#1214 abs fix + optimiser refactor
  libs/math/include/math/standard_functions/abs.hpp
  libs/ml/include/ml/optimisation/optimiser.hpp
  libs/vectorise/include/vectorise/fixed_point/type_traits.hpp
  libs/vm_modules/examples/abs/abs.etch
Labels: S-ready-for-review

#1187 Etch optimiser
  libs/ml/include/ml/optimisation/adam_optimiser.hpp
  libs/vm_modules/examples/ml_bindings/script/graph.etch
  libs/vm_modules/examples/mnist/main.cpp
  libs/vm_modules/examples/mnist/script/graph.etch
  libs/vm_modules/include/vm_modules/math/tensor.hpp
  libs/vm_modules/include/vm_modules/ml/cross_entropy.hpp
  libs/vm_modules/include/vm_modules/ml/dataloader/mnist_dataloader.hpp
  libs/vm_modules/include/vm_modules/ml/graph.hpp
  libs/vm_modules/include/vm_modules/ml/mean_square_error.hpp
  libs/vm_modules/include/vm_modules/ml/ops/loss_functions/cross_entropy.hpp
  libs/vm_modules/include/vm_modules/ml/ops/loss_functions/mean_square_error.hpp
  libs/vm_modules/include/vm_modules/ml/optimisation/adam_optimiser.hpp
  libs/vm_modules/include/vm_modules/ml/tensor.hpp
  libs/vm_modules/include/vm_modules/ml/training_pair.hpp
  libs/vm_modules/include/vm_modules/vm_factory.hpp
Labels: A-ml, A-vm, S-ready-for-review

#1196 ML sqrt implementation
  libs/ml/benchmark/ops/sqrt.cpp
  libs/ml/include/ml/ops/sqrt.hpp
  libs/ml/tests/ml/ops/sqrt.cpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
Labels: S-ready-for-review

#1232 [VM] Add erase member function to Array
  libs/vm/include/vm/array.hpp
  libs/vm/src/module.cpp
  libs/vm_modules/tests/unit/array_tests.cpp
Labels: S-ready-for-review

#1108 Add macOS builds
  .gitignore
  Jenkinsfile
  libs/ml/include/ml/dataloaders/commodity_dataloader.hpp
  scripts/ci-tool.py
Labels: S-ready-for-review

#1231 Miscellaneous changes
  apps/constellation/constellation.cpp
  libs/auctions/include/auctions/mock_smart_ledger.hpp
  libs/core/include/core/feature_flags.hpp
  libs/core/include/core/vector.hpp
  libs/core/tests/json/gtest/json_tests.cpp
  libs/crypto/tests/gtests/ecdsa_signature_test.cpp
  libs/crypto/tests/gtests/openssl_BIGNUM_padding_test.cpp
  libs/crypto/tests/gtests/openssl_common_test.cpp
  libs/crypto/tests/gtests/openssl_context_detail_primitives_test.cpp
  libs/crypto/tests/gtests/openssl_private_key_test.cpp
  libs/crypto/tests/gtests/sha256_tests.cpp
  libs/ledger/include/ledger/dag/dag_epoch.hpp
  libs/ledger/include/ledger/dag/dag_node.hpp
  libs/ledger/src/chaincode/smart_contract.cpp
  libs/math/include/math/clustering/k_means.hpp
  libs/miner/include/miner/transaction_layout_queue.hpp
  libs/ml/include/ml/dataloaders/dataloader.hpp
  libs/network/include/network/p2pservice/manifest.hpp
  libs/network/include/network/tcp/client_implementation.hpp
  libs/network/tests/muddle/peer_list_tests.cpp
  libs/network/tests/network/tcp_client_stress_tests.cpp
  libs/storage/benchmarks/stack_benchmarks/cache_line_random_access_stack_bench.cpp
  libs/vectorise/include/vectorise/threading/pool.hpp
Labels: S-ready-for-review

#1241 moved math tests into all_tests where they will be enabled
  libs/math/tests/math/all_tests/linalg/blas/gemm_nn_novector.cpp
  libs/math/tests/math/all_tests/linalg/blas/gemm_nn_vector.cpp
  libs/math/tests/math/all_tests/linalg/blas/gemm_nt_novector.cpp
  libs/math/tests/math/all_tests/linalg/blas/gemm_nt_vector.cpp
  libs/math/tests/math/all_tests/linalg/blas/gemm_tn_novector.cpp
  libs/math/tests/math/all_tests/linalg/blas/gemm_tn_vector.cpp
  libs/math/tests/math/all_tests/linalg/blas/gemm_tt_novector.cpp
  libs/math/tests/math/all_tests/linalg/blas/gemm_tt_vector.cpp
  libs/math/tests/math/all_tests/linalg/blas/gemv_n_novector.cpp
  libs/math/tests/math/all_tests/linalg/blas/gemv_n_vector.cpp
  libs/math/tests/math/all_tests/linalg/blas/gemv_t_novector.cpp
  libs/math/tests/math/all_tests/linalg/blas/gemv_t_vector.cpp
  libs/math/tests/math/all_tests/linalg/blas/scal_all.cpp
  libs/math/tests/math/all_tests/linalg/blas/swap_all.cpp
  libs/math/tests/math/all_tests/tensor/view_test.cpp
Labels: S-ready-for-review

#1246 fixed point vm_module tests
  libs/ledger/src/upow/synergetic_contract.cpp
  libs/vm_modules/examples/commodity_prediction/main.cpp
  libs/vm_modules/examples/mnist/main.cpp
  libs/vm_modules/include/vm_modules/crypto/sha256.hpp
  libs/vm_modules/include/vm_modules/math/bignumber.hpp
  libs/vm_modules/include/vm_modules/ml/dataloaders/commodity_dataloader.hpp
  libs/vm_modules/include/vm_modules/ml/dataloaders/mnist_dataloader.hpp
  libs/vm_modules/include/vm_modules/ml/ml.hpp
  libs/vm_modules/include/vm_modules/ml/ops/loss_functions/mean_square_error.hpp
  libs/vm_modules/include/vm_modules/ml/optimisation/adam_optimiser.hpp
  libs/vm_modules/include/vm_modules/ml/training_pair.hpp
  libs/vm_modules/include/vm_modules/vm_factory.hpp
  libs/vm_modules/tests/unit/fixed_point.cpp
Labels: S-ready-for-review

#1272 Mark tests longer than 1s as slow
  libs/math/tests/CMakeLists.txt
  libs/ml/tests/CMakeLists.txt
Labels: S-ready-for-review

#1273 Miscellaneous changes
  apps/constellation/CMakeLists.txt
  libs/core/include/core/bitvector.hpp
  libs/core/include/core/byte_array/const_byte_array.hpp
  libs/http/include/http/response.hpp
  libs/ledger/benchmark/tx_generation.hpp
  libs/ledger/benchmark/tx_submission.cpp
  libs/ledger/include/ledger/chain/main_chain.hpp
  libs/ledger/include/ledger/chaincode/wallet_record.hpp
  libs/ledger/include/ledger/protocols/executor_rpc_client.hpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/src/chaincode/deed.cpp
  libs/ledger/src/protocols/executor_rpc_client.cpp
  libs/ledger/tests/dag/dag_tests.cpp
  libs/math/include/math/standard_functions/clamp.hpp
  libs/math/tests/math/all_tests/fixed_point/fixed_point.cpp
  libs/math/tests/math/all_tests/kernels/sign.cpp
  libs/ml/include/ml/dataloaders/commodity_dataloader.hpp
  libs/ml/tests/ml/estimators/estimators.cpp
  libs/network/src/muddle/router.cpp
  libs/storage/include/storage/mmap_random_access_stack.hpp
  libs/storage/tests/gtest/object_store_tests.cpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
  libs/vectorise/include/vectorise/memory/shared_array.hpp
  libs/vm/include/vm/map.hpp
  libs/vm/include/vm/parser.hpp
  libs/vm/src/sharded_state.cpp
  libs/vm_modules/examples/fixedpoint/main.cpp
  libs/vm_modules/include/vm_modules/math/abs.hpp
  libs/vm_modules/include/vm_modules/math/exp.hpp
  libs/vm_modules/include/vm_modules/math/log.hpp
  libs/vm_modules/include/vm_modules/math/pow.hpp
  libs/vm_modules/include/vm_modules/math/random.hpp
  libs/vm_modules/include/vm_modules/math/sqrt.hpp
  libs/vm_modules/include/vm_modules/math/trigonometry.hpp
  libs/vm_modules/include/vm_modules/polyfill/bitwise_ops.hpp
  libs/vm_modules/src/core/print.cpp
  libs/vm_modules/tests/unit/state_tests.cpp
  scripts/bindings/method.C
Labels: S-ready-for-review

#1244 Bugfix/remove exceptions fixedpoint
  libs/math/include/math/base_types.hpp
  libs/math/tests/math/all_tests/fixed_point/fixed_point.cpp
  libs/ml/tests/ml/ops/sqrt.cpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
Labels: A-maths, C-bug, C-feature, S-ready-for-review

#1283 Build and run core unit tests; remove dead test
  libs/core/tests/CMakeLists.txt
  libs/core/tests/rand_gen/random_generator.cpp
Labels: S-ready-for-review

#1271 [CORE] Fixing FromBase58(...) when input array contains trailing space(s) beyond it's end
  libs/core/src/byte_array/base58.cpp
  libs/core/tests/byte_array/base58_tests.cpp
Labels: A-core, C-bug, P-high, S-ready-for-review

#1274 Reduce PR-merge build workload
  Jenkinsfile
Labels: S-ready-for-review
