Repository fetchai/ledger, pull requests merged in 2019-10, with the labels that each got.

#1715 Distributed client fix
  libs/ml/examples/boston_housing_distributed_learning/main.cpp
  libs/ml/examples/mnist_distributed_learning/main.cpp
  libs/ml/include/ml/distributed_learning/distributed_learning_client.hpp
Labels: S-ready-for-review

#1707 Feature/benchmark entropy gen
  libs/beacon/CMakeLists.txt
  libs/beacon/benchmark/CMakeLists.txt
  libs/beacon/benchmark/entropy_gen_bench.cpp
  libs/beacon/benchmark/main.cpp
  libs/beacon/include/beacon/beacon_service.hpp
  libs/muddle/src/fake_muddle.cpp
Labels: S-work-in-progress

#1711 Feature/entropy in block3
  apps/beacon/main.cpp
  apps/constellation/constellation.cpp
  apps/constellation/main.cpp
  cmake/BuildTargets.cmake
  libs/beacon/benchmark/entropy_gen_bench.cpp
  libs/beacon/include/beacon/aeon.hpp
  libs/beacon/include/beacon/beacon_manager.hpp
  libs/beacon/include/beacon/beacon_service.hpp
  libs/beacon/include/beacon/beacon_setup_service.hpp
  libs/beacon/include/beacon/block_entropy.hpp
  libs/beacon/include/beacon/entropy.hpp
  libs/beacon/include/beacon/event_manager.hpp
  libs/beacon/src/beacon_manager.cpp
  libs/beacon/src/beacon_service.cpp
  libs/beacon/src/beacon_setup_service.cpp
  libs/beacon/tests/dkg/dkg_resilience.cpp
  libs/beacon/tests/dkg/full_cycle.cpp
  libs/beacon/tests/dkg/trusted_dealer_test.cpp
  libs/core/include/core/service_ids.hpp
  libs/dkg/include/dkg/dkg_messages.hpp
  libs/dkg/src/dkg_messages.cpp
  libs/ledger/include/ledger/chain/block.hpp
  libs/ledger/include/ledger/consensus/consensus.hpp
  libs/ledger/include/ledger/consensus/consensus_interface.hpp
  libs/ledger/include/ledger/consensus/entropy_generator_interface.hpp
  libs/ledger/include/ledger/consensus/naive_entropy_generator.hpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_protocol.hpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/consensus/consensus.cpp
  libs/ledger/src/consensus/naive_entropy_generator.cpp
  libs/ledger/src/consensus/stake_manager.cpp
  libs/ledger/tests/unit/naive_entropy_generator_tests.cpp
  libs/ledger/tests/unit/stake_manager_tests.cpp
  libs/muddle/internal/muddle_fake.hpp
  libs/muddle/src/fake_muddle.cpp
  libs/network/include/network/p2pservice/p2p_http_interface.hpp
  scripts/end_to_end_test/end_to_end_test_pos.yaml
  scripts/end_to_end_test/run_end_to_end_test.py
Labels: S-work-in-progress

#1728 Fix unstable synergetic e2e test
  libs/network/src/tcp/tcp_server.cpp
  scripts/end_to_end_test/run_end_to_end_test.py
  scripts/end_to_end_test/smart_contract_tests/synergetic_contract.py
Labels: S-ready-for-review

#1718 Benchmarks signing, verification and group signature computation for entropy
  apps/constellation/main.cpp
  libs/beacon/include/beacon/dkg_output.hpp
  libs/beacon/include/beacon/trusted_dealer.hpp
  libs/beacon/src/beacon_manager.cpp
  libs/beacon/tests/dkg/beacon_manager_tests.cpp
  libs/beacon/tests/dkg/trusted_dealer_test.cpp
  libs/crypto/benchmark/bls_signing_and_verification.cpp
  libs/crypto/include/crypto/mcl_dkg.hpp
  libs/crypto/src/mcl_dkg.cpp
  libs/crypto/tests/unit/mcl_dkg_tests.cpp
Labels: S-ready-for-review

#1724 Benchmark total time for entropy generation
  apps/beacon/main.cpp
  libs/beacon/benchmark/entropy_gen_bench.cpp
  libs/beacon/include/beacon/create_new_certificate.hpp
  libs/beacon/include/beacon/trusted_dealer_beacon_service.hpp
  libs/beacon/src/create_new_certificate.cpp
  libs/beacon/src/trusted_dealer_beacon_service.cpp
  libs/beacon/tests/dkg/dkg_resilience.cpp
  libs/beacon/tests/dkg/full_cycle.cpp
  libs/beacon/tests/dkg/trusted_dealer_test.cpp
Labels: S-ready-for-review

#1685 Word2vec clients shouldn't need to have the same vocab
  libs/beacon/include/beacon/aeon.hpp
  libs/beacon/include/beacon/beacon_service.hpp
  libs/beacon/include/beacon/block_entropy.hpp
  libs/core/include/core/digest.hpp
  libs/ledger/benchmark/in_memory_storage.hpp
  libs/ledger/include/ledger/chain/block.hpp
  libs/ledger/include/ledger/chain/constants.hpp
  libs/ledger/include/ledger/chain/main_chain.hpp
  libs/ledger/include/ledger/chain/transaction.hpp
  libs/ledger/include/ledger/chaincode/smart_contract_manager.hpp
  libs/ledger/include/ledger/consensus/entropy_generator_interface.hpp
  libs/ledger/include/ledger/executor_interface.hpp
  libs/ledger/include/ledger/storage_unit/storage_unit_interface.hpp
  libs/ledger/include/ledger/transaction_status_cache.hpp
  libs/ledger/include/ledger/transaction_status_cache_impl.hpp
  libs/ledger/include/ledger/upow/synergetic_contract.hpp
  libs/ledger/include/ledger/upow/synergetic_execution_manager.hpp
  libs/ledger/include/ledger/upow/work.hpp
  libs/ledger/src/chain/constants.cpp
  libs/ledger/src/consensus/stake_snapshot.cpp
  libs/ledger/src/upow/naive_synergetic_miner.cpp
  libs/ledger/src/upow/synergetic_contract_factory.cpp
  libs/ledger/src/upow/work.cpp
  libs/ledger/tests/chain/block_coordinator_tests.cpp
  libs/ledger/tests/chain/fake_execution_manager.cpp
  libs/ledger/tests/chain/fake_execution_manager.hpp
  libs/ledger/tests/chain/fake_storage_unit.hpp
  libs/ledger/tests/chain/main_chain_tests.cpp
  libs/ledger/tests/chain/mock_execution_manager.hpp
  libs/ledger/tests/chain/mock_storage_unit.hpp
  libs/ledger/tests/chaincode/fake_storage_unit.hpp
  libs/ledger/tests/chaincode/mock_storage_unit.hpp
  libs/ledger/tests/executors/fake_executor.hpp
  libs/ledger/tests/executors/mock_executor.hpp
  libs/ledger/tests/executors/test_block.hpp
  libs/miner/include/miner/basic_miner.hpp
  libs/miner/include/miner/transaction_layout_queue.hpp
  libs/miner/src/transaction_layout_queue.cpp
  libs/miner/tests/basic_miner_tests.cpp
  libs/miner/tests/transaction_layout_queue_tests.cpp
  libs/miner/tests/tx_generator.hpp
  libs/ml/CMakeLists.txt
  libs/ml/examples/word2vec_distributed_learning/main.cpp
  libs/ml/examples/word2vec_distributed_learning/translator.hpp
  libs/ml/examples/word2vec_distributed_learning/word2vec_client.hpp
  libs/ml/examples/word2vec_simple/main.cpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/sgns_w2v_dataloader.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/vocab.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/w2v_dataloader.hpp
  libs/ml/include/ml/distributed_learning/distributed_learning_client.hpp
  libs/ml/src/dataloaders/word2vec_loaders/vocab.cpp
Labels: S-ready-for-review

#1731 Add detailed backtrace on segfault for clang
  Jenkinsfile
  cmake/BuildTargets.cmake
Labels: S-ready-for-review, S-ready-to-merge

#1738 Avoid self-deletion
  libs/vm/include/vm/object.hpp
Labels: S-ready-for-review, S-ready-to-merge

#1742 Moved W2V code from examples to right locations
  libs/ml/examples/word2vec_SGNS_dataloader/main.cpp
  libs/ml/examples/word2vec_distributed_learning/word2vec_client.hpp
  libs/ml/examples/word2vec_graph_evaluation/main.cpp
  libs/ml/include/ml/distributed_learning/translator.hpp
  libs/ml/include/ml/utilities/word2vec_utilities.hpp
Labels: A-ml, S-ready-for-review

#1748 Revert nolint in consensus
  libs/beacon/include/beacon/dkg_output.hpp
  libs/beacon/src/dkg_output.cpp
  libs/muddle/include/muddle/question_struct.hpp
  libs/muddle/src/muddle_endpoint_fake.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1740 Network Stability Improvements
  apps/constellation/bootstrap_monitor.cpp
  libs/muddle/internal/direct_message_service.hpp
  libs/muddle/internal/muddle_register.hpp
  libs/muddle/src/direct_message_service.cpp
  libs/muddle/src/muddle.cpp
  libs/muddle/src/muddle_register.cpp
  libs/network/src/tcp/client_implementation.cpp
Labels: S-ready-to-merge

#1747 Ml exceptions
  libs/ml/examples/bert_save_load_pretrained_model_example/main.cpp
  libs/ml/examples/bert_utilities.hpp
  libs/ml/examples/boston_housing_distributed_learning/main.cpp
  libs/ml/examples/commodity_prediction/main.cpp
  libs/ml/examples/model_saver.hpp
  libs/ml/examples/word2vec_SGNS_dataloader/main.cpp
  libs/ml/examples/word2vec_distributed_learning/word2vec_client.hpp
  libs/ml/examples/word2vec_graph_evaluation/main.cpp
  libs/ml/examples/word2vec_simple/main.cpp
  libs/ml/examples/word2vec_simple/word_analogy.hpp
  libs/ml/include/ml/core/graph.hpp
  libs/ml/include/ml/core/subgraph.hpp
  libs/ml/include/ml/dataloaders/ReadCSV.hpp
  libs/ml/include/ml/dataloaders/code2vec_context_loaders/context_loader.hpp
  libs/ml/include/ml/dataloaders/commodity_dataloader.hpp
  libs/ml/include/ml/dataloaders/dataloader.hpp
  libs/ml/include/ml/dataloaders/mnist_loaders/mnist_loader.hpp
  libs/ml/include/ml/dataloaders/tensor_dataloader.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/sgns_w2v_dataloader.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/w2v_dataloader.hpp
  libs/ml/include/ml/exceptions/exceptions.hpp
  libs/ml/include/ml/model/model.hpp
  libs/ml/include/ml/ops/constant.hpp
  libs/ml/include/ml/ops/divide.hpp
  libs/ml/include/ml/ops/loss_functions/mean_square_error_loss.hpp
  libs/ml/include/ml/optimisation/optimiser.hpp
  libs/ml/include/ml/regularisers/regularisation.hpp
  libs/ml/include/ml/serializers/ml_types.hpp
  libs/ml/include/ml/utilities/graph_builder.hpp
  libs/ml/include/ml/utilities/word2vec_utilities.hpp
Labels: S-ready-to-merge

#1741 bugfix MSE
  libs/ml/include/ml/ops/loss_functions/mean_square_error_loss.hpp
  libs/ml/tests/ml/ops/loss_functions/mean_square_error_loss.cpp
  libs/ml/tests/ml/optimisation/optimisers.cpp
Labels: S-ready-to-merge

#1757 CI Tool: Add cache interrogation on detection failure
  scripts/ci-tool.py
Labels: S-ready-for-review, S-ready-to-merge

#1755 Added checkpointing to ML model
  libs/ml/examples/mnist_model/main.cpp
  libs/ml/examples/word2vec_SGNS_dataloader/main.cpp
  libs/ml/examples/word2vec_graph_evaluation/main.cpp
  libs/ml/include/ml/model/model.hpp
  libs/ml/include/ml/model/model_config.hpp
  libs/ml/include/ml/utilities/graph_saver.hpp
Labels: S-ready-to-merge

#1753 Node and subgraph backprop
  libs/ml/include/ml/core/node.hpp
  libs/ml/include/ml/core/subgraph.hpp
  libs/ml/include/ml/optimisation/optimiser.hpp
  libs/ml/tests/ml/layers/PRelu.cpp
  libs/ml/tests/ml/layers/convolution_1d.cpp
  libs/ml/tests/ml/layers/convolution_2d.cpp
  libs/ml/tests/ml/layers/fully_connected.cpp
  libs/ml/tests/ml/layers/layer_norm.cpp
Labels: S-ready-to-merge

#1727 Model serialisation with tests
  libs/ml/examples/mnist_model/main.cpp
  libs/ml/include/ml/dataloaders/code2vec_context_loaders/context_loader.hpp
  libs/ml/include/ml/dataloaders/commodity_dataloader.hpp
  libs/ml/include/ml/dataloaders/dataloader.hpp
  libs/ml/include/ml/dataloaders/mnist_loaders/mnist_loader.hpp
  libs/ml/include/ml/dataloaders/tensor_dataloader.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/sgns_w2v_dataloader.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/w2v_dataloader.hpp
  libs/ml/include/ml/meta/ml_type_traits.hpp
  libs/ml/include/ml/model/dnn_classifier.hpp
  libs/ml/include/ml/model/dnn_regressor.hpp
  libs/ml/include/ml/model/model.hpp
  libs/ml/include/ml/model/model_config.hpp
  libs/ml/include/ml/model/sequential.hpp
  libs/ml/include/ml/optimisation/adagrad_optimiser.hpp
  libs/ml/include/ml/optimisation/adam_optimiser.hpp
  libs/ml/include/ml/optimisation/momentum_optimiser.hpp
  libs/ml/include/ml/optimisation/optimiser.hpp
  libs/ml/include/ml/optimisation/rmsprop_optimiser.hpp
  libs/ml/include/ml/optimisation/sgd_optimiser.hpp
  libs/ml/include/ml/optimisation/types.hpp
  libs/ml/tests/ml/model/dnn_classifier_test.cpp
  libs/ml/tests/ml/model/dnn_regressor_test.cpp
  libs/ml/tests/ml/model/sequential_test.cpp
Labels: A-ml, S-ready-to-merge

#1759 Remove dummy contract
  libs/ledger/benchmark/tx_generation.hpp
  libs/ledger/include/ledger/chaincode/contract.hpp
  libs/ledger/include/ledger/chaincode/dummy_contract.hpp
  libs/ledger/include/ledger/chaincode/smart_contract.hpp
  libs/ledger/src/chaincode/dummy_contract.cpp
  libs/ledger/src/chaincode/factory.cpp
  libs/ledger/src/chaincode/smart_contract.cpp
  libs/ledger/src/chaincode/smart_contract_manager.cpp
  libs/ledger/tests/chaincode/dummy_contract_tests.cpp
  libs/ledger/tests/executors/test_block.hpp
Labels: S-ready-for-review, S-ready-to-merge

#1756 add initial dmlf classes
  libs/core/include/core/service_ids.hpp
  libs/dmlf/CMakeLists.txt
  libs/dmlf/include/dmlf/networkers/abstract_learner_networker.hpp
  libs/dmlf/include/dmlf/networkers/filepassing_learner_networker.hpp
  libs/dmlf/include/dmlf/networkers/local_learner_networker.hpp
  libs/dmlf/include/dmlf/networkers/muddle_learner_networker.hpp
  libs/dmlf/include/dmlf/queue.hpp
  libs/dmlf/include/dmlf/queue_interface.hpp
  libs/dmlf/include/dmlf/shuffle_algorithm_interface.hpp
  libs/dmlf/include/dmlf/simple_cycling_algorithm.hpp
  libs/dmlf/include/dmlf/type_map.hpp
  libs/dmlf/include/dmlf/update.hpp
  libs/dmlf/include/dmlf/update_interface.hpp
  libs/dmlf/include/dmlf/vm_wrapper_etch.hpp
  libs/dmlf/include/dmlf/vm_wrapper_interface.hpp
  libs/dmlf/src/networkers/abstract_learner_networker.cpp
  libs/dmlf/src/networkers/filepassing_learner_networker.cpp
  libs/dmlf/src/networkers/local_learner_networker.cpp
  libs/dmlf/src/networkers/muddle_learner_networker.cpp
  libs/dmlf/src/shuffle_algorithm_interface.cpp
  libs/dmlf/src/simple_cycling_algorithm.cpp
  libs/dmlf/src/vm_wrapper_etch.cpp
  libs/dmlf/tests/CMakeLists.txt
  libs/dmlf/tests/local/local_tests.cpp
  libs/dmlf/tests/muddle/muddle_test.cpp
  libs/dmlf/tests/vm_wrapper/etch_wrapper_tests.cpp
Labels: S-ready-to-merge

#1758 possibly unused files
  libs/beacon/include/beacon/entropy.hpp
  libs/ledger/include/ledger/protocols/executor_rpc_client.hpp
  libs/miner/include/miner/instance/load_txt.hpp
  libs/miner/include/miner/transaction_item.hpp
  libs/network/include/network/management/connection_register.hpp
  libs/network/include/network/muddle/rpc/server.hpp
  libs/network/include/network/p2pservice/identity_cache.hpp
  libs/network/include/network/p2pservice/manifest.hpp
  libs/network/include/network/p2pservice/p2p_remote_manifest_cache.hpp
  libs/network/include/network/p2pservice/p2p_service_defs.hpp
  libs/network/include/network/service/feed_subscription_manager.hpp
  libs/network/include/network/service/function.hpp
  libs/network/include/network/service/server.hpp
  libs/network/include/network/service/service_client.hpp
Labels: S-ready-for-review, S-ready-to-merge

#1745 Static analysis loop counter fix
  .clang-tidy
  libs/math/include/math/approx_exp.hpp
  libs/math/tests/math/all_tests/gtest/exp_tests.cpp
  libs/math/tests/math/all_tests/gtest/spline_tests.cpp
  libs/math/tests/math/all_tests/serializers/fixed_point.cpp
  libs/ml/tests/ml/ops/embeddings.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1763 Making w2v sgns dataloader templated on TensorType
  libs/ml/examples/word2vec_SGNS_dataloader/main.cpp
  libs/ml/examples/word2vec_distributed_learning/word2vec_client.hpp
  libs/ml/examples/word2vec_graph_evaluation/main.cpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/sgns_w2v_dataloader.hpp
  libs/ml/include/ml/utilities/word2vec_utilities.hpp
  libs/ml/tests/ml/dataloader/skipgram_loader.cpp
Labels: S-ready-to-merge

#1754 Initial interfaces
  libs/dmlf/include/dmlf/execution_error_message.hpp
  libs/dmlf/include/dmlf/execution_interface.hpp
  libs/dmlf/include/dmlf/execution_result.hpp
Labels: S-ready-to-merge

#1768 Type id fixes
  libs/ledger/src/chaincode/smart_contract.cpp
  libs/vm/include/vm/address.hpp
  libs/vm/include/vm/array.hpp
  libs/vm/include/vm/map.hpp
  libs/vm/include/vm/object.hpp
  libs/vm/include/vm/vm.hpp
  libs/vm/src/object.cpp
  libs/vm/src/state.cpp
  libs/vm_modules/src/core/print.cpp
  libs/vm_modules/src/math/bignumber.cpp
Labels: S-ready-to-merge

#1767 Mark slow tests as such
  libs/dmlf/CMakeLists.txt
  libs/dmlf/tests/CMakeLists.txt
  libs/muddle/tests/CMakeLists.txt
Labels: S-ready-for-review, S-ready-to-merge

#1766 Reset cache for shared ops
  libs/ml/include/ml/core/graph.hpp
  libs/ml/include/ml/core/node.hpp
  libs/ml/include/ml/ops/variable.hpp
  libs/ml/include/ml/optimisation/adagrad_optimiser.hpp
  libs/ml/include/ml/optimisation/adam_optimiser.hpp
  libs/ml/include/ml/optimisation/momentum_optimiser.hpp
  libs/ml/include/ml/optimisation/optimiser.hpp
  libs/ml/include/ml/optimisation/rmsprop_optimiser.hpp
  libs/ml/include/ml/optimisation/sgd_optimiser.hpp
  libs/ml/tests/ml/layers/fully_connected.cpp
Labels: S-ready-to-merge

#1764 Feature/add and check signatures consensus
  libs/beacon/include/beacon/beacon_manager.hpp
  libs/beacon/include/beacon/block_entropy.hpp
  libs/beacon/src/beacon_manager.cpp
  libs/beacon/src/beacon_service.cpp
  libs/beacon/src/block_entropy.cpp
  libs/beacon/tests/dkg/dkg_resilience.cpp
  libs/beacon/tests/dkg/full_cycle.cpp
  libs/core/include/core/logging.hpp
  libs/ledger/include/ledger/chain/block.hpp
  libs/ledger/include/ledger/chain/block_coordinator.hpp
  libs/ledger/include/ledger/consensus/consensus.hpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/consensus/consensus.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1771 no shadow beacon lib
  libs/beacon/CMakeLists.txt
  libs/crypto/include/crypto/fetch_mcl.hpp
  libs/crypto/include/crypto/openssl_ecdsa_public_key.hpp
  libs/network/include/network/fetch_asio.hpp
Labels: S-ready-for-review, S-ready-to-merge

#1769 Etch bindings for Transpose Op
  libs/vm_modules/include/vm_modules/ml/graph.hpp
  libs/vm_modules/src/ml/graph.cpp
  libs/vm_modules/tests/unit/ops_tests.cpp
Labels: A-ml, S-ready-to-merge

#1775 Reenable disabled file object seek test
  libs/storage/include/storage/file_object.hpp
  libs/storage/tests/gtest/file_object/file_object_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1774 Feature/shadow most of rest
  libs/core/CMakeLists.txt
  libs/core/include/core/byte_array/consumers.hpp
  libs/core/src/yaml/document.cpp
  libs/crypto/CMakeLists.txt
  libs/dkg/CMakeLists.txt
  libs/dmlf/CMakeLists.txt
  libs/dmlf/src/networkers/filepassing_learner_networker.cpp
  libs/http/CMakeLists.txt
  libs/ledger/CMakeLists.txt
  libs/ledger/src/dag/dag.cpp
  libs/math/CMakeLists.txt
  libs/math/src/math/linalg/blas/gemv_n_vector.cpp
  libs/miner/CMakeLists.txt
  libs/ml/CMakeLists.txt
  libs/moment/CMakeLists.txt
  libs/muddle/CMakeLists.txt
  libs/network/CMakeLists.txt
  libs/python/CMakeLists.txt
  libs/settings/CMakeLists.txt
  libs/storage/CMakeLists.txt
  libs/storage/include/storage/key_value_index.hpp
  libs/telemetry/CMakeLists.txt
  libs/variant/CMakeLists.txt
  libs/vm/CMakeLists.txt
  libs/vm/include/vm/generator.hpp
  libs/vm/src/generator.cpp
  libs/vm_modules/CMakeLists.txt
Labels: S-ready-for-review, S-ready-to-merge

#1772 Add serialization to vm::Variant, only for variant of Primitive types
  .gitignore
  libs/vm/CMakeLists.txt
  libs/vm/include/vm/variant.hpp
  libs/vm/tests/CMakeLists.txt
  libs/vm/tests/variant/serialization.cpp
Labels: S-ready-to-merge

#1770 Resolve clock system/steady clock issue
  libs/beacon/include/beacon/beacon_setup_service.hpp
  libs/ledger/tests/chain/transaction_status_cache_tests.cpp
  libs/moment/include/moment/clock_interfaces.hpp
  libs/moment/include/moment/clocks.hpp
  libs/moment/include/moment/deadline_timer.hpp
  libs/moment/include/moment/detail/adjustable_clock.hpp
  libs/moment/include/moment/detail/steady_clock.hpp
  libs/moment/src/clocks.cpp
  libs/moment/src/deadline_timer.cpp
  libs/moment/tests/unit/clock_tests.cpp
  libs/muddle/include/muddle/punishment_broadcast_channel.hpp
Labels: S-ready-for-review, S-ready-to-merge

#1776 Add serialization to dmfl::ExecutionResult and dmlf::ExecutionErrorMessage
  libs/dmlf/include/dmlf/execution_error_message.hpp
  libs/dmlf/include/dmlf/execution_interface.hpp
  libs/dmlf/include/dmlf/execution_result.hpp
Labels: S-ready-to-merge

#1777 simplifying Array to Vector conversion in etch ml binding for optimser
  libs/vm_modules/src/ml/optimisation/optimiser.cpp
Labels: S-ready-to-merge

#1762 Moved word2vec tests into word2vec_utilities
  libs/ml/examples/word2vec_SGNS_dataloader/main.cpp
  libs/ml/examples/word2vec_distributed_learning/word2vec_client.hpp
  libs/ml/examples/word2vec_graph_evaluation/main.cpp
  libs/ml/include/ml/utilities/word2vec_utilities.hpp
Labels: S-ready-to-merge

#1783 Exp bindings with tests
  libs/vm_modules/include/vm_modules/ml/graph.hpp
  libs/vm_modules/src/ml/graph.cpp
  libs/vm_modules/tests/unit/ops_tests.cpp
Labels: A-ml, S-ready-to-merge

#1761 Variable freezing
  libs/ml/include/ml/core/graph.hpp
  libs/ml/include/ml/ops/embeddings.hpp
  libs/ml/include/ml/ops/trainable.hpp
  libs/ml/include/ml/ops/variable.hpp
  libs/ml/include/ml/optimisation/adagrad_optimiser.hpp
  libs/ml/include/ml/optimisation/adam_optimiser.hpp
  libs/ml/include/ml/optimisation/momentum_optimiser.hpp
  libs/ml/include/ml/optimisation/rmsprop_optimiser.hpp
  libs/ml/include/ml/optimisation/sgd_optimiser.hpp
  libs/ml/tests/ml/graph/graph.cpp
Labels: A-ml, S-ready-to-merge

#1780 Add dmlf::ExecutionEngineInterface and related interfaces + Restructre
  .gitignore
  libs/dmlf/include/dmlf/execution/execution_engine_interface.hpp
  libs/dmlf/include/dmlf/execution/execution_engine_single_threaded.hpp
  libs/dmlf/include/dmlf/execution/execution_error_message.hpp
  libs/dmlf/include/dmlf/execution/execution_interface.hpp
  libs/dmlf/include/dmlf/execution/execution_result.hpp
  libs/dmlf/include/dmlf/execution/local_executor.hpp
  libs/dmlf/include/dmlf/execution/remote_executor.hpp
  libs/dmlf/src/execution_result.cpp
  libs/dmlf/tests/CMakeLists.txt
  libs/dmlf/tests/execution/promise_of_result.cpp
Labels: S-ready-to-merge

#1779 Bug/deployment fixes
  libs/ledger/src/storage_unit/storage_unit_client.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1773 Model etch bindings
  libs/ml/include/ml/model/model.hpp
  libs/vm_modules/include/vm_modules/math/type.hpp
  libs/vm_modules/include/vm_modules/ml/model/model.hpp
  libs/vm_modules/include/vm_modules/ml/state_dict.hpp
  libs/vm_modules/src/ml/ml.cpp
  libs/vm_modules/src/ml/model/model.cpp
  libs/vm_modules/src/ml/optimisation/optimiser.cpp
  libs/vm_modules/tests/unit/ml.cpp
  scripts/etch-language-tests/ml/model/classifier.etch
  scripts/etch-language-tests/ml/model/regressor.etch
  scripts/etch-language-tests/ml/model/sequential.etch
Labels: S-ready-to-merge

#1788 [minor] [dmlf]Add serialization to SourceFile(s)
  libs/vm/include/vm/common.hpp
  libs/vm/tests/CMakeLists.txt
  libs/vm/tests/serialization/source_file.cpp
  libs/vm/tests/serialization/variant.cpp
Labels: S-ready-to-merge

#1781 Squeeze op with tests
  libs/ml/benchmark/ops/ops.cpp
  libs/ml/include/ml/meta/ml_type_traits.hpp
  libs/ml/include/ml/ops/squeeze.hpp
  libs/ml/include/ml/saveparams/saveable_params.hpp
  libs/ml/include/ml/serializers/ml_types.hpp
  libs/ml/include/ml/utilities/graph_builder.hpp
  libs/ml/tests/ml/ops/squeeze.cpp
Labels: A-ml, S-ready-to-merge

#1752 W2V modifications for graph generation
  libs/ml/examples/boston_housing_distributed_learning/main.cpp
  libs/ml/examples/mnist_distributed_learning/main.cpp
  libs/ml/examples/word2vec_distributed_learning/main.cpp
  libs/ml/examples/word2vec_distributed_learning/word2vec_client.hpp
  libs/ml/examples/word2vec_graph_evaluation/main.cpp
  libs/ml/include/ml/distributed_learning/coordinator.hpp
  libs/ml/include/ml/distributed_learning/distributed_learning_client.hpp
  libs/ml/include/ml/utilities/word2vec_utilities.hpp
  libs/ml/src/utilities/word2vec_utilities.cpp
Labels: A-ml, S-ready-to-merge

#1787 Sccache based CI builds
  CMakeLists.txt
  Jenkinsfile
  scripts/ci-tool.py
Labels: S-ready-for-review, S-ready-to-merge

#1784 Centralise serialisation of mcl types
  libs/beacon/include/beacon/beacon_complaints_manager.hpp
  libs/beacon/include/beacon/beacon_manager.hpp
  libs/beacon/include/beacon/beacon_setup_service.hpp
  libs/beacon/src/beacon_manager.cpp
  libs/beacon/src/beacon_setup_service.cpp
  libs/beacon/tests/dkg/beacon_manager_tests.cpp
  libs/beacon/tests/dkg/dkg_resilience.cpp
  libs/crypto/include/crypto/mcl_dkg.hpp
  libs/dkg/include/dkg/dkg_messages.hpp
Labels: S-ready-to-merge

#1801 CachedStorageAdapter bugfix
  libs/ledger/src/storage_unit/cached_storage_adapter.cpp
  libs/ledger/tests/unit/cached_storage_adapter_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1797 Vm public template creation
  libs/vm/include/vm/analyser.hpp
  libs/vm/include/vm/compiler.hpp
  libs/vm/include/vm/module.hpp
  libs/vm/include/vm/parser.hpp
  libs/vm/src/analyser.cpp
  libs/vm/src/module.cpp
  libs/vm/src/parser.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1805 Move constellation to its own library
  apps/constellation/CMakeLists.txt
  apps/constellation/bootstrap_monitor.hpp
  apps/constellation/config_builder.cpp
  apps/constellation/config_builder.hpp
  apps/constellation/main.cpp
  libs/constellation/CMakeLists.txt
  libs/constellation/include/constellation/constellation.hpp
  libs/constellation/include/constellation/health_check_http_module.hpp
  libs/constellation/include/constellation/logging_http_module.hpp
  libs/constellation/include/constellation/muddle_status_http_module.hpp
  libs/constellation/include/constellation/open_api_http_module.hpp
  libs/constellation/include/constellation/telemetry_http_module.hpp
  libs/constellation/src/constellation.cpp
  libs/constellation/src/manifest_builder.cpp
  libs/constellation/src/muddle_status_http_module.cpp
  libs/constellation/src/open_api_http_module.cpp
  libs/network/CMakeLists.txt
Labels: S-ready-for-review, S-ready-to-merge

#1778 Alpha TX Syncing Issues
  libs/ledger/include/ledger/execution_manager.hpp
  libs/ledger/include/ledger/shard_config.hpp
  libs/ledger/include/ledger/storage_unit/transaction_store_sync_protocol.hpp
  libs/ledger/include/ledger/storage_unit/transaction_store_sync_service.hpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/execution_manager.cpp
  libs/ledger/src/storage_unit/transaction_store_sync_protocol.cpp
  libs/ledger/src/storage_unit/transaction_store_sync_service.cpp
  libs/network/include/network/generics/requesting_queue.hpp
Labels: S-ready-for-review

#1798 Avg pooling op
  libs/ml/include/ml/meta/ml_type_traits.hpp
  libs/ml/include/ml/ops/avg_pool_1d.hpp
  libs/ml/include/ml/ops/avg_pool_2d.hpp
  libs/ml/include/ml/saveparams/saveable_params.hpp
  libs/ml/include/ml/serializers/ml_types.hpp
  libs/ml/include/ml/utilities/graph_builder.hpp
  libs/ml/tests/ml/ops/avg_pool_1d.cpp
  libs/ml/tests/ml/ops/avg_pool_2d.cpp
Labels: A-ml, S-ready-to-merge

#1803 Updated code owners file
  .github/CODEOWNERS
Labels: S-ready-to-merge

#1809 Changes execution interface to use Ledge Variant instead of Vm Variant
  libs/dmlf/include/dmlf/execution/basic_vm_engine.hpp
  libs/dmlf/include/dmlf/execution/execution_engine_interface.hpp
  libs/dmlf/include/dmlf/execution/execution_interface.hpp
  libs/dmlf/include/dmlf/execution/execution_result.hpp
  libs/dmlf/src/basic_vm_engine.cpp
  libs/dmlf/tests/execution/basic_engine_tests.cpp
Labels: S-ready-to-merge

#1791 Simplify passing action name to DispatchTransaction
  libs/ledger/include/ledger/chaincode/contract.hpp
  libs/ledger/src/chaincode/contract.cpp
  libs/ledger/src/executor.cpp
  libs/ledger/tests/chaincode/contract_test.hpp
Labels: S-ready-for-review, S-ready-to-merge

#1806 Fixed incorrect use of std::numeric_limits with fixed-point
  libs/math/include/math/clustering/k_means.hpp
  libs/math/include/math/matrix_operations.hpp
  libs/ml/examples/commodity_prediction/main.cpp
  libs/ml/include/ml/clustering/tsne.hpp
  libs/ml/tests/unit/clustering/tsne_tests.cpp
Labels: S-ready-to-merge

#1812 Crypto prediction fix
  libs/vm-modules/examples/crypto_price_prediction/script/bitcoin.etch
Labels: S-ready-to-merge

#1808 TX Sync Improvements (Backport of #1778)
  libs/ledger/include/ledger/execution_manager.hpp
  libs/ledger/include/ledger/shard_config.hpp
  libs/ledger/include/ledger/storage_unit/transaction_store_sync_protocol.hpp
  libs/ledger/include/ledger/storage_unit/transaction_store_sync_service.hpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/execution_manager.cpp
  libs/ledger/src/storage_unit/transaction_store_sync_protocol.cpp
  libs/ledger/src/storage_unit/transaction_store_sync_service.cpp
  libs/network/include/network/generics/requesting_queue.hpp
Labels: S-ready-to-merge

#1807 Dev/dmlf muddle
  libs/dmlf/include/dmlf/execution/execution_result.hpp
  libs/dmlf/include/dmlf/execution_workload.hpp
  libs/dmlf/include/dmlf/remote_execution_client.hpp
  libs/dmlf/include/dmlf/remote_execution_host.hpp
  libs/dmlf/include/dmlf/remote_execution_protocol.hpp
  libs/dmlf/src/execution_result.cpp
  libs/dmlf/src/execution_workload.cpp
  libs/dmlf/src/networkers/muddle_learner_networker.cpp
  libs/dmlf/src/remote_execution_client.cpp
  libs/dmlf/src/remote_execution_host.cpp
  libs/dmlf/src/remote_execution_protocol.cpp
  libs/dmlf/tests/CMakeLists.txt
  libs/dmlf/tests/dmlf_muddle/dmlf_muddle.cpp
Labels: S-ready-to-merge

#1813 Remove getBlockNumber function
  libs/ledger/src/chaincode/smart_contract.cpp
  scripts/end_to_end_test/end_to_end_test.yaml
  scripts/end_to_end_test/smart_contract_tests/ledger_context.py
  scripts/end_to_end_test/smart_contract_tests/synergetic_mining.py
Labels: S-ready-for-review, S-ready-to-merge

#1811 remove bottleneck in peer discovery
  libs/muddle/src/muddle_register.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1796 Example of variable serialisations for the VM execution
  libs/vm-modules/examples/parameter_pack/main.cpp
  libs/vm/include/vm/common.hpp
  libs/vm/include/vm/module.hpp
  libs/vm/include/vm/object.hpp
  libs/vm/include/vm/variant.hpp
  libs/vm/include/vm/vm.hpp
  libs/vm/src/module.cpp
  libs/vm/src/vm.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1819 Initial work around for apple clang 11.0
  cmake/BuildTargets.cmake
Labels: S-ready-for-review, S-ready-to-merge

#1802 Integrated LocalLearnerNetworker version of examples to master
  libs/dmlf/CMakeLists.txt
  libs/dmlf/examples/CMakeLists.txt
  libs/dmlf/examples/boston_housing_distributed_learning/main.cpp
  libs/dmlf/examples/mnist_distributed_learning/main.cpp
  libs/dmlf/examples/word2vec_distributed_learning/main.cpp
  libs/dmlf/examples/word2vec_distributed_learning/word2vec_client.hpp
  libs/dmlf/examples/word2vec_distributed_learning/word2vec_training_params.hpp
  libs/dmlf/include/dmlf/distributed_learning/distributed_learning_client.hpp
  libs/dmlf/include/dmlf/distributed_learning/translator.hpp
  libs/dmlf/include/dmlf/update.hpp
  libs/ml/include/ml/distributed_learning/coordinator.hpp
Labels: A-ml, S-ready-to-merge

#1815 Add methods for aggregate signatures
  libs/crypto/include/crypto/mcl_dkg.hpp
  libs/crypto/src/mcl_dkg.cpp
  libs/crypto/tests/unit/mcl_dkg_tests.cpp
Labels: S-ready-to-merge

#1826 Ranged function for SplitOp
  libs/math/include/math/tensor.hpp
  libs/ml/include/ml/meta/ml_type_traits.hpp
  libs/ml/include/ml/ops/slice.hpp
  libs/ml/include/ml/saveparams/saveable_params.hpp
  libs/ml/tests/unit/ops/slice.cpp
Labels: A-ml, S-ready-to-merge

#1823 add params passing and a test
  libs/dmlf/include/dmlf/execution/execution_interface.hpp
  libs/dmlf/include/dmlf/execution/execution_params.hpp
  libs/dmlf/include/dmlf/execution/local_executor.hpp
  libs/dmlf/include/dmlf/remote_execution_client.hpp
  libs/dmlf/include/dmlf/remote_execution_host.hpp
  libs/dmlf/src/local_executor.cpp
  libs/dmlf/src/remote_execution_client.cpp
  libs/dmlf/src/remote_execution_host.cpp
  libs/dmlf/tests/dmlf_muddle/dmlf_muddle.cpp
Labels: S-ready-to-merge

#1820 Add DKG support to the manifest
  libs/constellation/src/constellation.cpp
  libs/shards/CMakeLists.txt
  libs/shards/include/shards/manifest.hpp
  libs/shards/include/shards/service_identifier.hpp
  libs/shards/src/manifest.cpp
  libs/shards/src/service_identifier.cpp
  libs/shards/tests/CMakeLists.txt
  libs/shards/tests/integration/.gitkeep
  libs/shards/tests/unit/manifest_entry_tests.cpp
  libs/shards/tests/unit/manifest_parse_tests.cpp
  libs/shards/tests/unit/manifest_tests.cpp
  libs/shards/tests/unit/service_identifier_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1821 Miscellaneous changes
  libs/chain/include/chain/transaction.hpp
  libs/chain/src/json_transaction.cpp
  libs/chain/src/transaction_builder.cpp
  libs/chain/src/transaction_layout.cpp
  libs/core/include/core/serializers/array_interface.hpp
  libs/crypto/include/crypto/ecdsa.hpp
  libs/crypto/include/crypto/verifier.hpp
  libs/dmlf/tests/dmlf_muddle/dmlf_muddle.cpp
  libs/ledger/benchmark/in_memory_storage.cpp
  libs/ledger/benchmark/in_memory_storage.hpp
  libs/ledger/include/ledger/chaincode/contract.hpp
  libs/ledger/include/ledger/chaincode/smart_contract.hpp
  libs/ledger/include/ledger/execution_manager.hpp
  libs/ledger/include/ledger/execution_manager_interface.hpp
  libs/ledger/include/ledger/executor.hpp
  libs/ledger/include/ledger/storage_unit/cached_storage_adapter.hpp
  libs/ledger/include/ledger/storage_unit/storage_unit_client.hpp
  libs/ledger/include/ledger/storage_unit/storage_unit_interface.hpp
  libs/ledger/src/chaincode/contract.cpp
  libs/ledger/src/chaincode/smart_contract.cpp
  libs/ledger/src/chaincode/token_contract.cpp
  libs/ledger/src/execution_manager.cpp
  libs/ledger/src/executor.cpp
  libs/ledger/src/genesis_file_creator.cpp
  libs/ledger/src/storage_unit/cached_storage_adapter.cpp
  libs/ledger/src/storage_unit/storage_unit_client.cpp
  libs/ledger/tests/chain/fake_execution_manager.cpp
  libs/ledger/tests/chain/fake_execution_manager.hpp
  libs/ledger/tests/chain/fake_storage_unit.cpp
  libs/ledger/tests/chain/fake_storage_unit.hpp
  libs/ledger/tests/chain/mock_execution_manager.hpp
  libs/ledger/tests/chain/mock_storage_unit.hpp
  libs/ledger/tests/chaincode/fake_storage_unit.hpp
  libs/ledger/tests/chaincode/mock_storage_unit.hpp
  libs/ledger/tests/unit/cached_storage_adapter_tests.cpp
  libs/math/include/math/exceptions/exceptions.hpp
  libs/ml/include/ml/exceptions/exceptions.hpp
  libs/muddle/include/muddle/question_struct.hpp
  libs/muddle/src/muddle_status.cpp
  libs/muddle/src/packet.cpp
  libs/storage/include/storage/document.hpp
  libs/storage/include/storage/document_store_protocol.hpp
  libs/storage/include/storage/new_revertible_document_store.hpp
  libs/storage/src/new_revertible_document_store.cpp
  libs/storage/src/resource_mapper.cpp
  scripts/detect-circular-dependencies.py
  scripts/end_to_end_test/run_end_to_end_test.py
Labels: S-ready-for-review, S-ready-to-merge

#1818 update readme with alpha connect info
  README.md
Labels: S-ready-for-review, S-ready-to-merge

#1816 Fix @init return bug
  libs/http/src/http_client.cpp
  libs/ledger/include/ledger/tx_status_http_interface.hpp
  libs/ledger/src/chaincode/smart_contract_manager.cpp
  libs/ledger/src/tx_status_http_interface.cpp
  scripts/end_to_end_test/run_end_to_end_test.py
  scripts/end_to_end_test/smart_contract_tests/ledger_context.py
  scripts/install-test-dependencies.sh
Labels: S-ready-for-review, S-ready-to-merge

#1825 Fixed broken tests for adagrad and rmsprop
  libs/ml/include/ml/model/dnn_regressor.hpp
  libs/ml/tests/unit/model/dnn_classifier_test.cpp
  libs/ml/tests/unit/model/dnn_regressor_test.cpp
  libs/ml/tests/unit/model/sequential_test.cpp
Labels: S-ready-to-merge

#1827 Fixed Embedding bug causing 0 peers distributed w2v not to train
  libs/ml/include/ml/ops/embeddings.hpp
Labels: A-ml, S-ready-to-merge

#1794 Feature/simd overflow checks
  libs/math/tests/unit/fixed_point/fixed_point.cpp
  libs/math/tests/unit/vectors/avx_tests.cpp
  libs/vectorise/include/vectorise/arch/avx/info.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_fixed32.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_fixed64.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_int32.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_int64.hpp
  libs/vectorise/include/vectorise/arch/sse/info.hpp
  libs/vectorise/include/vectorise/arch/sse/register_double.hpp
  libs/vectorise/include/vectorise/arch/sse/register_fixed16_16.hpp
  libs/vectorise/include/vectorise/arch/sse/register_fixed32_32.hpp
  libs/vectorise/include/vectorise/arch/sse/register_float.hpp
  libs/vectorise/include/vectorise/arch/sse/register_int32.hpp
  libs/vectorise/include/vectorise/avx.hpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
  libs/vectorise/include/vectorise/info_avx.hpp
  libs/vectorise/include/vectorise/info_sse.hpp
  libs/vectorise/include/vectorise/sse.hpp
Labels: A-maths, C-feature, C-improvement, C-optimisation, S-ready-for-review, S-ready-to-merge

#1829 committee rename
  apps/CMakeLists.txt
  apps/beacon/CMakeLists.txt
  apps/beacon/main.cpp
  apps/constellation/config_builder.cpp
  apps/constellation/settings.cpp
  apps/constellation/settings.hpp
  libs/beacon/benchmark/entropy_gen_bench.cpp
  libs/beacon/include/beacon/beacon_complaints_manager.hpp
  libs/beacon/include/beacon/beacon_manager.hpp
  libs/beacon/include/beacon/block_entropy.hpp
  libs/beacon/include/beacon/events.hpp
  libs/beacon/src/beacon_complaints_manager.cpp
  libs/beacon/src/beacon_service.cpp
  libs/beacon/tests/unit/full_cycle.cpp
  libs/beacon/tests/unit/trusted_dealer_test.cpp
  libs/constellation/include/constellation/constellation.hpp
  libs/constellation/src/constellation.cpp
  libs/crypto/benchmark/bls_signing_and_verification.cpp
  libs/crypto/include/crypto/mcl_dkg.hpp
  libs/crypto/src/mcl_dkg.cpp
  libs/crypto/tests/unit/mcl_dkg_tests.cpp
  libs/dkg/examples/dkg/main.cpp
  libs/dkg/include/dkg/dkg_messages.hpp
  libs/ledger/include/ledger/consensus/consensus.hpp
  libs/ledger/include/ledger/consensus/stake_manager.hpp
  libs/ledger/include/ledger/consensus/stake_snapshot.hpp
  libs/ledger/src/consensus/consensus.cpp
  libs/ledger/src/consensus/stake_manager.cpp
  libs/ledger/src/consensus/stake_snapshot.cpp
  libs/ledger/src/genesis_file_creator.cpp
  libs/ledger/tests/unit/stake_manager_tests.cpp
  libs/ledger/tests/unit/stake_snapshot_tests.cpp
  libs/muddle/src/punishment_broadcast_channel.cpp
  libs/muddle/src/rbc.cpp
  libs/network/tests/rbc/rbc_tests.cpp
  scripts/generate-genesis-file.py
Labels: S-ready-for-review, S-ready-to-merge

#1834 dmlf tidying
  libs/dmlf/CMakeLists.txt
  libs/dmlf/examples/mnist_distributed_learning/main.cpp
  libs/dmlf/include/dmlf/distributed_learning/distributed_learning_client.hpp
  libs/ml/include/ml/utilities/utils.hpp
  libs/ml/include/ml/utilities/word2vec_utilities.hpp
  libs/ml/src/utilities/utils.cpp
Labels: S-ready-to-merge

#1832 Variable reset gradient comment
  libs/ml/include/ml/ops/variable.hpp
Labels: A-ml, S-ready-to-merge

#1833 Use consistent naming for DRB cabinet
  libs/beacon/include/beacon/beacon_service.hpp
  libs/beacon/src/beacon_service.cpp
  libs/beacon/tests/unit/dkg_resilience.cpp
  libs/beacon/tests/unit/full_cycle.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1838 Initial clang-tidy-cache support
  scripts/fetchai_code_quality/internal/toolchains.py
Labels: S-ready-for-review, S-ready-to-merge

#1849 Reassign DMLF muddle test
  libs/dmlf/tests/CMakeLists.txt
Labels: S-ready-for-review, S-ready-to-merge

#1843 reworked distributed boston example to read config file instead of ta…
  libs/dmlf/examples/boston_housing_distributed_learning/main.cpp
Labels: S-ready-to-merge

#1854 VM type info fixes
  libs/vm/include/vm/analyser.hpp
  libs/vm/include/vm/array.hpp
  libs/vm/include/vm/common.hpp
  libs/vm/include/vm/compiler.hpp
  libs/vm/include/vm/generator.hpp
  libs/vm/include/vm/map.hpp
  libs/vm/src/analyser.cpp
  libs/vm/src/generator.cpp
  libs/vm/src/matrix.cpp
  libs/vm/src/sharded_state.cpp
  libs/vm/src/state.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1858 Removed Ops::embeddings::updated_rows as it is unused
  libs/ml/include/ml/ops/embeddings.hpp
  libs/ml/include/ml/saveparams/saveable_params.hpp
  libs/ml/include/ml/serializers/ml_types.hpp
Labels: S-ready-for-review, S-ready-to-merge

#1856 Dev/var converter for params
  libs/dmlf/include/dmlf/execution/basic_vm_engine.hpp
  libs/dmlf/include/dmlf/var_converter.hpp
  libs/dmlf/src/basic_vm_engine.cpp
  libs/dmlf/src/var_converter.cpp
  libs/dmlf/tests/CMakeLists.txt
  libs/dmlf/tests/var_converter/var_converter_test.cpp
  libs/vm/include/vm/module.hpp
Labels: S-ready-to-merge

#1857 Spelling corrections
  apps/muddle-node/main.cpp
  cmake/BuildTools.cmake
  libs/beacon/src/beacon_setup_service.cpp
  libs/bloom-filter/tests/CMakeLists.txt
  libs/constellation/src/constellation.cpp
  libs/crypto/src/key_generator.cpp
  libs/dmlf/src/basic_vm_engine.cpp
  libs/http/src/http_client.cpp
  libs/json/tests/CMakeLists.txt
  libs/ledger/include/ledger/chaincode/contract.hpp
  libs/ledger/include/ledger/dag/dag.hpp
  libs/ledger/include/ledger/storage_unit/object_store_protocol.hpp
  libs/ledger/include/ledger/storage_unit/transient_object_store.hpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/src/chaincode/chain_code_cache.cpp
  libs/ledger/src/chaincode/factory.cpp
  libs/ledger/src/chaincode/smart_contract.cpp
  libs/ledger/src/chaincode/token_contract.cpp
  libs/ledger/src/consensus/stake_manager.cpp
  libs/ledger/src/consensus/stake_snapshot.cpp
  libs/ledger/src/dag/dag.cpp
  libs/ledger/src/execution_manager.cpp
  libs/ledger/src/executor.cpp
  libs/ledger/src/genesis_file_creator.cpp
  libs/ledger/src/tx_query_http_interface.cpp
  libs/ledger/src/upow/naive_synergetic_miner.cpp
  libs/ledger/src/upow/synergetic_execution_manager.cpp
  libs/moment/src/clocks.cpp
  libs/muddle/src/dispatcher.cpp
  libs/muddle/src/muddle_register.cpp
  libs/muddle/src/peer_list.cpp
  libs/muddle/src/peer_selector.cpp
  libs/muddle/src/router.cpp
  libs/network/include/network/p2pservice/p2p_http_interface.hpp
  libs/network/include/network/service/protocol.hpp
  libs/network/src/service/client_interface.cpp
  libs/shards/src/manifest.cpp
  libs/shards/src/shard_management_service.cpp
  libs/shards/tests/unit/manifest_parse_tests.cpp
  libs/storage/tests/unit/versioned_kvi_tests.cpp
  libs/telemetry/include/telemetry/registry.hpp
  libs/telemetry/src/histogram_map.cpp
  libs/variant/include/variant/detail/element_pool.hpp
  libs/variant/src/variant.cpp
  libs/vm-modules/src/core/structured_data.cpp
  libs/yaml/tests/CMakeLists.txt
Labels: S-ready-for-review, S-ready-to-merge

#1859 Dev/vm state too small buffer fix
  libs/dmlf/src/basic_vm_engine.cpp
  libs/dmlf/src/vm_state.cpp
  libs/dmlf/tests/execution/basic_engine_tests.cpp
Labels: S-ready-for-review

#1860 MsgPack compliance for VM arrays, maps and strings.
  libs/core/include/core/serializers/array_interface.hpp
  libs/core/include/core/serializers/main_serializer.hpp
  libs/core/include/core/serializers/main_serializer_definition.hpp
  libs/core/include/core/serializers/map_interface.hpp
  libs/core/src/serializers/main_serializer.cpp
  libs/vm-modules/examples/parameter_pack/main.cpp
  libs/vm-modules/tests/unit/parameter_serialization.cpp
  libs/vm/include/vm/array.hpp
  libs/vm/include/vm/execution_task.hpp
  libs/vm/include/vm/map.hpp
  libs/vm/include/vm/object.hpp
  libs/vm/include/vm/vm.hpp
  libs/vm/src/module.cpp
  libs/vm/src/object.cpp
  libs/vm/src/vm.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1852 OneHot math function implemented with tests
  libs/math/include/math/one_hot.hpp
  libs/math/tests/unit/gtest/one_hot.cpp
Labels: A-maths, S-ready-to-merge

#1851 Maxpool op with tests
  libs/ml/include/ml/meta/ml_type_traits.hpp
  libs/ml/include/ml/ops/max_pool.hpp
  libs/ml/include/ml/saveparams/saveable_params.hpp
  libs/ml/include/ml/serializers/ml_types.hpp
  libs/ml/include/ml/utilities/graph_builder.hpp
  libs/ml/tests/unit/ops/max_pool.cpp
Labels: A-ml, S-ready-to-merge

#1862 Pass contract owner address to @init
  libs/ledger/src/chaincode/smart_contract_manager.cpp
  scripts/end_to_end_test/end_to_end_test.yaml
  scripts/end_to_end_test/smart_contract_tests/init_owner_address.py
Labels: C-bug, S-ready-for-review, S-ready-to-merge

#1850 Simplify contract factories
  libs/ledger/include/ledger/chaincode/chain_code_cache.hpp
  libs/ledger/include/ledger/chaincode/chain_code_factory.hpp
  libs/ledger/include/ledger/chaincode/factory.hpp
  libs/ledger/include/ledger/chaincode/smart_contract_factory.hpp
  libs/ledger/include/ledger/upow/naive_synergetic_miner.hpp
  libs/ledger/include/ledger/upow/synergetic_executor.hpp
  libs/ledger/src/chaincode/chain_code_cache.cpp
  libs/ledger/src/chaincode/chain_code_factory.cpp
  libs/ledger/src/chaincode/contract_http_interface.cpp
  libs/ledger/src/chaincode/smart_contract_manager.cpp
  libs/ledger/src/state_adapter.cpp
  libs/ledger/src/upow/naive_synergetic_miner.cpp
  libs/ledger/src/upow/synergetic_contract_factory.cpp
  libs/ledger/src/upow/synergetic_executor.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1853 Dmlf training client model rework
  libs/dmlf/examples/boston_housing_distributed_learning/main.cpp
  libs/dmlf/examples/boston_housing_multiprocess_distributed_learning/main.cpp
  libs/dmlf/examples/mnist_distributed_learning/main.cpp
  libs/dmlf/examples/mnist_multiprocess_distributed_learning/main.cpp
  libs/dmlf/examples/word2vec_distributed_learning/main.cpp
  libs/dmlf/examples/word2vec_multiprocess_distributed_learning/main.cpp
  libs/dmlf/include/dmlf/distributed_learning/client_params.hpp
  libs/dmlf/include/dmlf/distributed_learning/distributed_learning_client.hpp
  libs/dmlf/include/dmlf/distributed_learning/utilities/boston_housing_client_utilities.hpp
  libs/dmlf/include/dmlf/distributed_learning/utilities/mnist_client_utilities.hpp
  libs/dmlf/include/dmlf/distributed_learning/utilities/utilities.hpp
  libs/dmlf/include/dmlf/distributed_learning/word2vec_client.hpp
  libs/dmlf/include/dmlf/distributed_learning/word2vec_training_params.hpp
  libs/ml/include/ml/model/model.hpp
  libs/ml/include/ml/model/sequential.hpp
  libs/ml/include/ml/optimisation/types.hpp
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
Labels: A-ml, S-ready-to-merge

#1842 Added assert to catch crossentropy backprop input of zero, added test…
  libs/math/include/math/exceptions/exceptions.hpp
  libs/ml/include/ml/core/node.hpp
  libs/ml/include/ml/ops/loss_functions/cross_entropy_loss.hpp
Labels: S-ready-to-merge

#1840 Add Etch Remote Execution Node and Client
  libs/dmlf/examples/etch_client/config_client.json
  libs/dmlf/examples/etch_client/main.cpp
  libs/dmlf/examples/etch_node/config_node_1.json
  libs/dmlf/examples/etch_node/main.cpp
  libs/dmlf/include/dmlf/execution/local_executor.hpp
  libs/dmlf/include/dmlf/execution_workload.hpp
  libs/dmlf/include/dmlf/remote_execution_host.hpp
  libs/dmlf/src/local_executor.cpp
  libs/dmlf/src/remote_execution_client.cpp
  libs/dmlf/src/remote_execution_host.cpp
  libs/dmlf/tests/dmlf_muddle/dmlf_muddle.cpp
Labels: S-ready-to-merge

#1814 Improvements/beacon setup timeouts
  libs/beacon/include/beacon/beacon_manager.hpp
  libs/beacon/include/beacon/beacon_setup_service.hpp
  libs/beacon/src/beacon_complaints_manager.cpp
  libs/beacon/src/beacon_manager.cpp
  libs/beacon/src/beacon_service.cpp
  libs/beacon/src/beacon_setup_service.cpp
  libs/beacon/src/trusted_dealer_beacon_service.cpp
  libs/beacon/tests/unit/dkg_resilience.cpp
  libs/crypto/include/crypto/mcl_dkg.hpp
  libs/crypto/src/mcl_dkg.cpp
  libs/crypto/tests/unit/mcl_dkg_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1864 Dev/vm basic complex types
  libs/dmlf/src/basic_vm_engine.cpp
  libs/dmlf/tests/execution/basic_engine_tests.cpp
Labels: S-ready-to-merge

#1872 Added namespace to Bert utilities and other tidying
  libs/ml/examples/bert_for_finetune/main.cpp
  libs/ml/examples/bert_save_load_pretrained_model_example/main.cpp
  libs/ml/examples/bert_simple_cls_example/main.cpp
  libs/ml/examples/crypto_price_prediction/main.cpp
  libs/ml/include/ml/utilities/bert_utilities.hpp
Labels: S-ready-for-review, S-ready-to-merge

#1867 Etch model serialisation
  libs/ml/include/ml/model/model.hpp
  libs/ml/include/ml/optimisation/adam_optimiser.hpp
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/include/vm_modules/ml/optimisation/optimiser.hpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/tests/unit/ml.cpp
Labels: S-ready-to-merge

#1875 MsgPack compliance for ledger Variant
  libs/core/include/core/serializers/binary_interface.hpp
  libs/core/include/core/serializers/counter.hpp
  libs/core/include/core/serializers/group_definitions.hpp
  libs/core/include/core/serializers/main_serializer.hpp
  libs/core/include/core/serializers/main_serializer_definition.hpp
  libs/dmlf/include/dmlf/execution/execution_result.hpp
  libs/dmlf/tests/execution/local_executor_tests.cpp
  libs/variant/include/variant/variant.hpp
  libs/variant/tests/unit/serialization.cpp
  libs/vm-modules/tests/unit/parameter_serialization.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1861 One Hot Op with tests
  libs/math/include/math/one_hot.hpp
  libs/math/tests/unit/gtest/one_hot.cpp
  libs/ml/include/ml/meta/ml_type_traits.hpp
  libs/ml/include/ml/ops/one_hot.hpp
  libs/ml/include/ml/saveparams/saveable_params.hpp
  libs/ml/include/ml/serializers/ml_types.hpp
  libs/ml/include/ml/utilities/graph_builder.hpp
  libs/ml/tests/unit/ops/one_hot.cpp
Labels: A-ml, S-ready-to-merge

#1876 Persistent state fix
  libs/vm/include/vm/generator.hpp
  libs/vm/src/generator.cpp
Labels: S-ready-for-review, S-ready-to-merge
