Repository fetchai/ledger, pull requests merged in 2019-11, with the labels that each got.

#1865 Bugfix/http destruction
  libs/http/include/http/connection.hpp
  libs/http/include/http/http_connection_manager.hpp
  libs/http/include/http/server.hpp
  libs/http/src/http_connection_manager.cpp
  libs/http/tests/unit/destruction_test.cpp
Labels: S-ready-to-merge

#1881 Possible due to network races to segv during DKG
  libs/beacon/src/beacon_setup_service.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1877 Bug fix in beacon tests
  libs/beacon/include/beacon/beacon_setup_service.hpp
  libs/beacon/src/beacon_setup_service.cpp
  libs/beacon/tests/unit/dkg_resilience.cpp
Labels: S-ready-to-merge

#1870 Make (Un)lockResource idempotent
  libs/storage/include/storage/document_store_protocol.hpp
Labels: S-ready-for-review, S-ready-to-merge

#1871 Construct identifier from hex-encoded digest
  libs/ledger/src/upow/synergetic_executor.cpp
Labels: C-bug, S-ready-for-review, S-ready-to-merge

#1883 Bug fix/flaky beacon test
  libs/beacon/include/beacon/beacon_setup_service.hpp
  libs/beacon/src/beacon_setup_service.cpp
  libs/beacon/tests/unit/dkg_resilience.cpp
Labels: S-ready-to-merge

#1889 Enable Clang Tidy Cache
  Jenkinsfile
Labels: S-ready-for-review, S-ready-to-merge

#1882 Math Test sanitising
  cmake/BuildTools.cmake
  libs/math/include/math/combinatorics.hpp
  libs/math/tests/unit/activation_functions/gelu.cpp
  libs/math/tests/unit/activation_functions/relu.cpp
  libs/math/tests/unit/activation_functions/sigmoid.cpp
  libs/math/tests/unit/activation_functions/softmax.cpp
  libs/math/tests/unit/basic_math/normalize_array_tests.cpp
  libs/math/tests/unit/basic_math/standard_functions_test.cpp
  libs/math/tests/unit/clustering/knn_test.cpp
  libs/math/tests/unit/combinatorics/combinatorics.cpp
  libs/math/tests/unit/correlation/pearson.cpp
  libs/math/tests/unit/distance/cosine.cpp
  libs/math/tests/unit/distance/entropy_tests.cpp
  libs/math/tests/unit/distance/euclidean_distance.cpp
  libs/math/tests/unit/distance/hamming_tests.cpp
  libs/math/tests/unit/distance/manhattan_tests.cpp
  libs/math/tests/unit/distance/minkowski.cpp
  libs/math/tests/unit/distance/pairwise_distance.cpp
  libs/math/tests/unit/distance/perplexity.cpp
  libs/math/tests/unit/gtest/one_hot.cpp
  libs/math/tests/unit/matrix_operations/matrix_operations.cpp
  libs/math/tests/unit/metrics/cross_entropy_loss.cpp
  libs/math/tests/unit/metrics/kl_divergence_tests.cpp
  libs/math/tests/unit/metrics/l2_loss.cpp
  libs/math/tests/unit/metrics/l2_norm.cpp
  libs/math/tests/unit/metrics/mean_absolute_error.cpp
  libs/math/tests/unit/metrics/mean_squared_error.cpp
  libs/math/tests/unit/tensor/basic_tests.cpp
  libs/math/tests/unit/tensor/constructor.cpp
  libs/math/tests/unit/tensor/serializer.cpp
  libs/math/tests/unit/tensor/tensor_concat.cpp
  libs/math/tests/unit/tensor/tensor_indexing.cpp
  libs/math/tests/unit/tensor/tensor_operations.cpp
  libs/math/tests/unit/tensor/view_test.cpp
  libs/math/tests/unit/test_types.hpp
  libs/math/tests/unit/trigonometry/trig.cpp
Labels: A-maths, S-ready-to-merge

#1878 Vm dataloader multiple inputs
  libs/vm-modules/include/vm_modules/ml/dataloaders/dataloader.hpp
  libs/vm-modules/include/vm_modules/ml/training_pair.hpp
  libs/vm-modules/src/core/structured_data.cpp
  libs/vm-modules/src/math/tensor.cpp
  libs/vm-modules/src/ml/dataloaders/dataloader.cpp
  libs/vm-modules/src/ml/training_pair.cpp
  libs/vm-modules/tests/unit/ml.cpp
  scripts/etch-language-tests/ml/graph.etch
  scripts/etch-language-tests/ml/optimiser.etch
  scripts/etch-language-tests/ml/serialisation/dataloader.etch
Labels: A-ml, A-vm, S-ready-to-merge

#1884 Math TOP K function with tests
  libs/math/include/math/top_k.hpp
  libs/math/tests/unit/gtest/top_k.cpp
Labels: A-maths, S-ready-to-merge

#1887 Bugfix/http destruction nh
  libs/http/include/http/abstract_connection.hpp
  libs/http/include/http/connection.hpp
  libs/http/include/http/http_connection_manager.hpp
  libs/http/include/http/server.hpp
  libs/http/src/http_connection_manager.cpp
  libs/http/src/json_client.cpp
  libs/http/tests/unit/destruction_test.cpp
  libs/network/include/network/details/network_manager_implementation.hpp
Labels: S-ready-for-review, S-ready-to-merge

#1892 Cyclic library dependencies detection using general graph
  scripts/detect-circular-dependencies.py
  scripts/fetchai_code_quality/__init__.py
  scripts/fetchai_code_quality/internal/graph.py
  scripts/fetchai_code_quality/internal/test/graph_test.py
Labels: S-ready-to-merge

#1894 One Hot math tests improved
  libs/math/tests/unit/gtest/one_hot.cpp
Labels: A-maths, S-ready-for-review

#1839 Use hex encoding for digest
  apps/chain-tool/main.cpp
  libs/chain/src/transaction_builder.cpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/miner/basic_miner.cpp
  libs/ledger/src/storage_unit/storage_unit_client.cpp
  libs/ledger/src/tx_query_http_interface.cpp
  libs/ledger/src/tx_status_http_interface.cpp
  libs/ledger/src/upow/naive_synergetic_miner.cpp
  libs/muddle/src/rpc/client.cpp
  libs/muddle/src/rpc/server.cpp
  libs/network/src/service/client_interface.cpp
  scripts/install-test-dependencies.sh
Labels: S-ready-for-review, S-ready-to-merge

#1879 Fix nullptr executor synergetic execution manager
  libs/ledger/include/ledger/storage_unit/transient_object_store.hpp
  libs/ledger/include/ledger/upow/synergetic_execution_manager.hpp
  libs/ledger/src/upow/synergetic_execution_manager.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1847 Deployment updates
  .gitignore
  apps/CMakeLists.txt
  apps/constellation/main.cpp
  apps/constellation/settings.cpp
  apps/muddle-probe/CMakeLists.txt
  apps/muddle-probe/main.cpp
  libs/beacon/include/beacon/beacon_manager.hpp
  libs/beacon/include/beacon/beacon_service.hpp
  libs/beacon/include/beacon/beacon_setup_service.hpp
  libs/beacon/src/beacon_manager.cpp
  libs/beacon/src/beacon_service.cpp
  libs/beacon/src/beacon_setup_service.cpp
  libs/beacon/tests/unit/trusted_dealer_test.cpp
  libs/constellation/src/constellation.cpp
  libs/ledger/include/ledger/consensus/consensus.hpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_service.hpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/src/consensus/consensus.cpp
  libs/ledger/src/consensus/stake_manager.cpp
  libs/ledger/src/dag/dag.cpp
  libs/ledger/src/genesis_file_creator.cpp
  libs/ledger/src/protocols/main_chain_rpc_service.cpp
  libs/ledger/src/storage_unit/transaction_store_sync_service.cpp
  libs/ledger/src/upow/synergetic_execution_manager.cpp
  libs/muddle/include/muddle/muddle_interface.hpp
  libs/muddle/internal/muddle.hpp
  libs/muddle/internal/muddle_fake.hpp
  libs/muddle/internal/router.hpp
  libs/muddle/src/direct_message_service.cpp
  libs/muddle/src/muddle.cpp
  libs/muddle/src/muddle_register.cpp
  libs/muddle/src/muddle_status.cpp
  libs/muddle/src/router.cpp
  libs/network/include/network/p2pservice/p2p_http_interface.hpp
  libs/network/include/network/tcp/client_implementation.hpp
  libs/network/src/tcp/client_implementation.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1897 Vm contract to contract
  libs/vm/include/vm/analyser.hpp
  libs/vm/include/vm/common.hpp
  libs/vm/include/vm/compiler.hpp
  libs/vm/include/vm/generator.hpp
  libs/vm/include/vm/ir.hpp
  libs/vm/include/vm/module.hpp
  libs/vm/include/vm/node.hpp
  libs/vm/include/vm/opcodes.hpp
  libs/vm/include/vm/parser.hpp
  libs/vm/include/vm/token.hpp
  libs/vm/include/vm/tokeniser.hpp
  libs/vm/include/vm/vm.hpp
  libs/vm/scripts/tokeniser.l
  libs/vm/src/analyser.cpp
  libs/vm/src/generator.cpp
  libs/vm/src/ir.cpp
  libs/vm/src/ir_builder.cpp
  libs/vm/src/parser.cpp
  libs/vm/src/tokeniser.cpp
  libs/vm/src/vm.cpp
  libs/vm/src/vm_handlers.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1902 Compare not against genesis
  libs/ledger/include/ledger/chain/block.hpp
  libs/ledger/src/chain/block.cpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/src/protocols/main_chain_rpc_service.cpp
Labels: A-ledger, C-improvement, S-ready-for-review

#1890 Features/ml top k op
  libs/math/include/math/top_k.hpp
  libs/math/tests/unit/gtest/top_k.cpp
  libs/ml/include/ml/meta/ml_type_traits.hpp
  libs/ml/include/ml/ops/top_k.hpp
  libs/ml/include/ml/saveparams/saveable_params.hpp
  libs/ml/include/ml/serializers/ml_types.hpp
  libs/ml/include/ml/utilities/graph_builder.hpp
  libs/ml/tests/unit/ops/top_k.cpp
Labels: A-ml, S-ready-to-merge

#1905 Vm contract invocation handler
  libs/vm/include/vm/generator.hpp
  libs/vm/include/vm/variant.hpp
  libs/vm/include/vm/vm.hpp
  libs/vm/src/vm_handlers.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1891 Synergetic contracts end to end test
  libs/core/include/core/periodic_runnable.hpp
  libs/core/include/core/runnable.hpp
  libs/core/include/core/state_machine.hpp
  libs/core/src/periodic_runnable.cpp
  libs/core/src/reactor.cpp
  libs/ledger/include/ledger/upow/synergetic_execution_manager.hpp
  libs/ledger/src/upow/synergetic_execution_manager.cpp
  libs/muddle/internal/promise_runnable.hpp
  libs/muddle/src/promise_runnable.cpp
  scripts/end_to_end_test/end_to_end_synergetic_test.yaml
  scripts/end_to_end_test/run_end_to_end_test.py
  scripts/end_to_end_test/smart_contract_tests/synergetic_utils.py
  scripts/fetchai_netutils/fetch/cluster/chain.py
  scripts/fetchai_netutils/fetch/cluster/instance.py
  scripts/fetchai_netutils/fetch/testing/testcase.py
Labels: S-ready-for-review, S-ready-to-merge

#1912 Mark slow tests as such
  libs/http/tests/CMakeLists.txt
  libs/messenger/tests/CMakeLists.txt
Labels: S-ready-for-review, S-ready-to-merge

#1911 Feature/genesis file updates2
  libs/ledger/include/ledger/consensus/consensus.hpp
  libs/ledger/src/genesis_file_creator.cpp
  scripts/end_to_end_test/end_to_end_test.yaml
  scripts/end_to_end_test/input_files/create-input-files.py
  scripts/fetchai_netutils/fetch/cluster/instance.py
  scripts/fetchai_netutils/fetch/testing/testcase.py
  scripts/generate-genesis-file.py
  scripts/install-test-dependencies.sh
Labels: S-ready-for-review, S-ready-to-merge

#1914 Reduce logging from http for doug's stuff
  libs/http/include/http/server.hpp
Labels: S-ready-for-review, S-ready-to-merge

#1913 updated branding
  libs/version/src/cli_header.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1915 Refactor of hypercube database
  libs/semanticsearch/CMakeLists.txt
  libs/semanticsearch/include/semanticsearch/advertisement_register.hpp
  libs/semanticsearch/include/semanticsearch/index/base_types.hpp
  libs/semanticsearch/include/semanticsearch/index/database_index_interface.hpp
  libs/semanticsearch/include/semanticsearch/index/in_memory_db_index.hpp
  libs/semanticsearch/include/semanticsearch/index/semantic_subscription.hpp
  libs/semanticsearch/include/semanticsearch/index/subscription_group.hpp
  libs/semanticsearch/include/semanticsearch/module/model_interface_builder.hpp
  libs/semanticsearch/include/semanticsearch/semantic_search_module.hpp
  libs/semanticsearch/include/semanticsearch/vocabular_advertisement.hpp
  libs/semanticsearch/src/semanticsearch/advertisement_register.cpp
  libs/semanticsearch/src/semanticsearch/index/in_memory_db_index.cpp
  libs/semanticsearch/src/semanticsearch/index/subscription_group.cpp
  libs/semanticsearch/src/semanticsearch/query/query_executor.cpp
  libs/semanticsearch/tests/CMakeLists.txt
  libs/semanticsearch/tests/unit/index.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1917 contract variable bug fixes
  libs/vm/include/vm/vm.hpp
  libs/vm/src/vm_handlers.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1922 oef build appear broken on mac and linux, temp disable
  apps/CMakeLists.txt
  cmake/BuildTargets.cmake
Labels: S-ready-for-review, S-ready-to-merge

#1920 Model conv layers etch
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/tests/unit/ml.cpp
Labels: S-ready-to-merge

#1926 String mutability fix
  libs/vm-modules/tests/unit/string_tests.cpp
  libs/vm/include/vm/module/member_function_invoke.hpp
  libs/vm/include/vm/object.hpp
  libs/vm/include/vm/string.hpp
  libs/vm/src/string.cpp
  scripts/etch-language-tests/strings/reverse.etch
  scripts/etch-language-tests/strings/trim.etch
Labels: S-ready-for-review, S-ready-to-merge

#1928 Remove unused member variable
  libs/vm-modules/src/ledger/transaction.cpp
  libs/vm/include/vm/string.hpp
  libs/vm/include/vm/vm.hpp
  libs/vm/src/string.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1929 Ensure consistency of String length member
  libs/dmlf/src/basic_vm_engine.cpp
  libs/ledger/src/chaincode/smart_contract.cpp
  libs/vm-modules/src/core/panic.cpp
  libs/vm-modules/src/core/print.cpp
  libs/vm-modules/src/core/structured_data.cpp
  libs/vm-modules/src/crypto/sha256.cpp
  libs/vm-modules/src/math/read_csv.cpp
  libs/vm-modules/src/math/tensor.cpp
  libs/vm-modules/src/ml/dataloaders/dataloader.cpp
  libs/vm-modules/src/ml/graph.cpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/src/ml/optimisation/optimiser.cpp
  libs/vm-modules/src/ml/state_dict.cpp
  libs/vm-modules/src/ml/utilities/mnist_utilities.cpp
  libs/vm-modules/src/ml/utilities/scaler.cpp
  libs/vm-modules/tests/unit/state_tests.cpp
  libs/vm/include/vm/address.hpp
  libs/vm/include/vm/string.hpp
  libs/vm/src/sharded_state.cpp
  libs/vm/src/state.cpp
  libs/vm/src/string.cpp
  libs/vm/src/vm_handlers.cpp
  libs/vm/tests/unit/variant.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1918 Remove block body concept
  apps/chain-tool/main.cpp
  libs/ledger/include/ledger/chain/block.hpp
  libs/ledger/include/ledger/chain/block_db_record.hpp
  libs/ledger/include/ledger/execution_manager.hpp
  libs/ledger/include/ledger/execution_manager_interface.hpp
  libs/ledger/include/ledger/miner/annealer_miner.hpp
  libs/ledger/include/ledger/miner/basic_miner.hpp
  libs/ledger/include/ledger/protocols/notarisation_service.hpp
  libs/ledger/src/chain/block.cpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/src/consensus/consensus.cpp
  libs/ledger/src/consensus/stake_manager.cpp
  libs/ledger/src/execution_manager.cpp
  libs/ledger/src/genesis_file_creator.cpp
  libs/ledger/src/miner/basic_miner.cpp
  libs/ledger/src/protocols/main_chain_rpc_service.cpp
  libs/ledger/src/protocols/notarisation_service.cpp
  libs/ledger/src/testing/block_generator.cpp
  libs/ledger/src/upow/synergetic_execution_manager.cpp
  libs/ledger/tests/chain/block_coordinator_tests.cpp
  libs/ledger/tests/chain/fake_block_packer.cpp
  libs/ledger/tests/chain/fake_execution_manager.cpp
  libs/ledger/tests/chain/fake_execution_manager.hpp
  libs/ledger/tests/chain/main_chain_subtree_tests.cpp
  libs/ledger/tests/chain/main_chain_tests.cpp
  libs/ledger/tests/chain/mock_execution_manager.hpp
  libs/ledger/tests/consensus/main_chain_tests.cpp
  libs/ledger/tests/executors/test_block.hpp
  libs/ledger/tests/notarisation/notarisation_tests.cpp
  libs/ledger/tests/unit/basic_miner_tests.cpp
  libs/ledger/tests/unit/stake_manager_tests.cpp
  libs/network/include/network/p2pservice/p2p_http_interface.hpp
Labels: S-ready-for-review, S-ready-to-merge

#1924 First version update store
  libs/dmlf/include/dmlf/colearn/colearn_update.hpp
  libs/dmlf/include/dmlf/colearn/update_store.hpp
  libs/dmlf/src/colearn_update.cpp
  libs/dmlf/src/update_store.cpp
  libs/dmlf/tests/CMakeLists.txt
  libs/dmlf/tests/colearn/update_store_test.cpp
Labels: S-ready-to-merge

#1930 Fix chain-tool startup crash
  apps/chain-tool/main.cpp
Labels: C-bug, S-ready-for-review, S-ready-to-merge

#1935 Remove embeddings transpose
  libs/ml/include/ml/layers/skip_gram.hpp
  libs/ml/include/ml/ops/embeddings.hpp
  libs/ml/include/ml/ops/matrix_multiply.hpp
  libs/ml/include/ml/saveparams/saveable_params.hpp
  libs/ml/include/ml/serializers/ml_types.hpp
Labels: S-ready-to-merge

#1822 CONTRIBUTING file and code style guidelines
  CONTRIBUTING.md
  docs/cplusplus-style-guide.md
Labels: S-ready-for-review, S-ready-to-merge

#1940 Simple extension of JSON parser testing
  libs/json/tests/unit/document_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1937 etch type system improvements
  libs/vm/include/vm/analyser.hpp
  libs/vm/include/vm/ir.hpp
  libs/vm/include/vm/node.hpp
  libs/vm/src/analyser.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1931 Fix with multi lane syncing
  libs/constellation/src/constellation.cpp
  libs/ledger/include/ledger/chain/block_coordinator.hpp
  libs/ledger/include/ledger/transaction_status_cache_impl.hpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/tests/chain/block_coordinator_tests.cpp
  scripts/end_to_end_test/end_to_end_test.yaml
  scripts/end_to_end_test/run_end_to_end_test.py
  scripts/fetchai_netutils/fetch/testing/testcase.py
Labels: C-bug, S-ready-for-review, S-ready-to-merge

#1944 Check promises are not null in networking stack
  libs/network/src/service/client_interface.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1946 disable POS E2E temporarily
  scripts/end_to_end_test/end_to_end_test.yaml
Labels: S-ready-for-review, S-ready-to-merge

#1941 Add oef-base to oef team so we can bring it up to standard
  .github/CODEOWNERS
Labels: S-ready-for-review, S-ready-to-merge

#1948 Put dag behind synergetic flag
  libs/constellation/src/constellation.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1945 Improvement/clean genesis
  apps/chain-tool/main.cpp
  libs/chain/include/chain/constants.hpp
  libs/chain/src/constants.cpp
  libs/core/include/core/byte_array/const_byte_array.hpp
  libs/ledger/include/ledger/chain/block.hpp
  libs/ledger/include/ledger/chain/block_db_record.hpp
  libs/ledger/include/ledger/chain/main_chain.hpp
  libs/ledger/include/ledger/execution_manager.hpp
  libs/ledger/src/chain/block.cpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/chain/consensus/dummy_miner.cpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/src/chaincode/smart_contract_manager.cpp
  libs/ledger/src/testing/block_generator.cpp
  libs/ledger/src/upow/naive_synergetic_miner.cpp
  libs/ledger/tests/chain/block_coordinator_tests.cpp
  libs/ledger/tests/chain/fake_execution_manager.hpp
  libs/ledger/tests/chain/main_chain_tests.cpp
  libs/ledger/tests/executors/test_block.hpp
  libs/network/include/network/service/server_interface.hpp
Labels: A-ledger, C-improvement, S-ready-for-review, S-ready-to-merge

#1896 Dev/vm return array
  libs/dmlf/include/dmlf/execution/basic_vm_engine.hpp
  libs/dmlf/include/dmlf/execution/execution_error_message.hpp
  libs/dmlf/src/basic_vm_engine.cpp
  libs/dmlf/tests/execution/basic_engine_tests.cpp
  libs/dmlf/tests/var_converter/var_converter_test.cpp
Labels: S-ready-to-merge

#1953 Left right operator fix
  libs/vm/include/vm/object.hpp
  libs/vm/include/vm/string.hpp
  libs/vm/include/vm/vm.hpp
  libs/vm/src/analyser.cpp
  libs/vm/src/generator.cpp
  libs/vm/src/string.cpp
Labels: S-ready-to-merge

#1952 Simplify calls to make_shared in VM
  libs/vm/include/vm/node.hpp
Labels: S-ready-for-review, S-ready-to-merge

#1909 Sparse gradient for Embedding updates
  libs/ml/benchmark/CMakeLists.txt
  libs/ml/benchmark/embeddings/embeddings.cpp
  libs/ml/examples/word2vec_SGNS_dataloader/main.cpp
  libs/ml/include/ml/core/graph.hpp
  libs/ml/include/ml/meta/ml_type_traits.hpp
  libs/ml/include/ml/ops/embeddings.hpp
  libs/ml/include/ml/ops/trainable.hpp
  libs/ml/include/ml/ops/variable.hpp
  libs/ml/include/ml/ops/weights.hpp
  libs/ml/include/ml/optimisation/adam_optimiser.hpp
  libs/ml/include/ml/optimisation/lazy_adam_optimiser.hpp
  libs/ml/include/ml/optimisation/sgd_optimiser.hpp
  libs/ml/include/ml/utilities/sparse_tensor_utilities.hpp
  libs/ml/tests/unit/optimisation/sparse_optimisers.cpp
Labels: A-ml, S-ready-to-merge

#1927 TX Malleability Fixes
  libs/chain/CMakeLists.txt
  libs/chain/include/chain/transaction.hpp
  libs/chain/include/chain/transaction_builder.hpp
  libs/chain/src/transaction.cpp
  libs/chain/src/transaction_builder.cpp
  libs/chain/src/transaction_serializer.cpp
  libs/chain/tests/unit/address_serialisation_tests.cpp
  libs/chain/tests/unit/address_tests.cpp
  libs/chain/tests/unit/integer_encoding_tests.cpp
  libs/chain/tests/unit/json_transaction_tests.cpp
  libs/chain/tests/unit/transaction_layout_tests.cpp
  libs/chain/tests/unit/transaction_serializer_tests.cpp
  scripts/install-test-dependencies.sh
Labels: S-ready-for-review, S-ready-to-merge

#1947 Feature/persist consensus storage
  apps/constellation/main.cpp
  libs/beacon/include/beacon/aeon.hpp
  libs/beacon/include/beacon/beacon_manager.hpp
  libs/beacon/include/beacon/beacon_service.hpp
  libs/beacon/include/beacon/block_entropy.hpp
  libs/beacon/src/beacon_service.cpp
  libs/beacon/tests/unit/trusted_dealer_test.cpp
  libs/constellation/src/constellation.cpp
  libs/core/include/core/reactor.hpp
  libs/core/src/reactor.cpp
  libs/ledger/include/ledger/genesis_loading/genesis_file_creator.hpp
  libs/ledger/src/genesis_file_creator.cpp
  libs/ledger/src/protocols/main_chain_rpc_service.cpp
  libs/version/src/cli_header.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1959 Skipgram fix
  libs/ml/include/ml/layers/skip_gram.hpp
Labels: A-ml, S-ready-to-merge

#1893 Feature/implement fp128
  libs/core/include/core/serializers/base_types.hpp
  libs/core/tests/integration/containers/array_tests.cpp
  libs/dmlf/tests/execution/basic_engine_tests.cpp
  libs/math/include/math/activation_functions/gelu.hpp
  libs/math/include/math/comparison.hpp
  libs/math/include/math/correlation/jaccard.hpp
  libs/math/include/math/tensor.hpp
  libs/math/src/math/linalg/blas/gemm_nn_novector.cpp
  libs/math/src/math/linalg/blas/gemm_nn_vector.cpp
  libs/math/src/math/linalg/blas/gemm_nt_novector.cpp
  libs/math/src/math/linalg/blas/gemm_nt_vector.cpp
  libs/math/src/math/linalg/blas/gemm_tn_novector.cpp
  libs/math/src/math/linalg/blas/gemm_tn_vector.cpp
  libs/math/src/math/linalg/blas/gemm_tt_novector.cpp
  libs/math/src/math/linalg/blas/gemm_tt_vector.cpp
  libs/math/src/math/linalg/blas/gemv_n_novector.cpp
  libs/math/src/math/linalg/blas/gemv_n_vector.cpp
  libs/math/src/math/linalg/blas/gemv_t_novector.cpp
  libs/math/src/math/linalg/blas/gemv_t_vector.cpp
  libs/math/tests/unit/activation_functions/softmax.cpp
  libs/math/tests/unit/fixed_point/fixed_point.cpp
  libs/math/tests/unit/test_types.hpp
  libs/math/tests/unit/vectors/vector_tests.cpp
  libs/ml/tests/unit/model/sequential_test.cpp
  libs/vectorise/include/vectorise/containers/array.hpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
  libs/vectorise/include/vectorise/platform.hpp
  libs/vectorise/include/vectorise/uint/int.hpp
  libs/vectorise/include/vectorise/uint/uint.hpp
  libs/vectorise/tests/CMakeLists.txt
  libs/vectorise/tests/int/int.cpp
Labels: A-maths, C-feature, C-improvement, S-ready-to-merge

#1960 math TopK any axis
  libs/math/include/math/top_k.hpp
  libs/math/tests/unit/gtest/top_k.cpp
  libs/ml/include/ml/ops/top_k.hpp
  libs/ml/tests/unit/ops/top_k.cpp
Labels: A-maths, S-ready-to-merge

#1938 Dev/update store2
  libs/dmlf/include/dmlf/colearn/colearn_update.hpp
  libs/dmlf/include/dmlf/colearn/update_store.hpp
  libs/dmlf/include/dmlf/colearn/update_store_interface.hpp
  libs/dmlf/src/colearn_update.cpp
  libs/dmlf/src/update_store.cpp
  libs/dmlf/tests/colearn/update_store_test.cpp
Labels: S-ready-to-merge

#1932 Fix missing hash related crashes in DAG
  libs/ledger/include/ledger/chaincode/smart_contract_factory.hpp
  libs/ledger/include/ledger/dag/dag.hpp
  libs/ledger/include/ledger/dag/dag_epoch.hpp
  libs/ledger/include/ledger/dag/dag_hash.hpp
  libs/ledger/include/ledger/dag/dag_interface.hpp
  libs/ledger/include/ledger/dag/dag_node.hpp
  libs/ledger/include/ledger/dag/dag_sync_service.hpp
  libs/ledger/src/dag/dag.cpp
  libs/ledger/src/dag/dag_epoch.cpp
  libs/ledger/src/dag/dag_hash.cpp
  libs/ledger/tests/dag/dag_tests.cpp
  scripts/end_to_end_test/end_to_end_synergetic_test.yaml
  scripts/end_to_end_test/run_end_to_end_test.py
Labels: S-ready-for-review, S-ready-to-merge

#1950 Dev/collearn proc loop2
  libs/dmlf/include/dmlf/colearn/muddle_learner_networker_impl.hpp
  libs/dmlf/include/dmlf/networkers/abstract_learner_networker.hpp
  libs/dmlf/include/dmlf/queue.hpp
  libs/dmlf/include/dmlf/queue_interface.hpp
  libs/dmlf/src/colearn/muddle_learner_networker_impl.cpp
  libs/dmlf/src/networkers/abstract_learner_networker.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1919 Adding random number generator to base dataloader for random access mode
  libs/core/include/core/random/lfg.hpp
  libs/core/tests/unit/random/shuffle_tests.cpp
  libs/ml/examples/crypto_price_prediction/main.cpp
  libs/ml/include/ml/dataloaders/commodity_dataloader.hpp
  libs/ml/include/ml/dataloaders/dataloader.hpp
  libs/ml/include/ml/dataloaders/tensor_dataloader.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/sgns_w2v_dataloader.hpp
  libs/ml/tests/unit/clustering/tsne_tests.cpp
  libs/ml/tests/unit/dataloader/tensor_dataloader.cpp
  libs/ml/tests/unit/layers/convolution_1d.cpp
  libs/ml/tests/unit/layers/convolution_2d.cpp
  libs/ml/tests/unit/model/dnn_classifier_test.cpp
  libs/ml/tests/unit/model/dnn_regressor_test.cpp
  libs/ml/tests/unit/model/sequential_test.cpp
  libs/ml/tests/unit/ops/activations/dropout.cpp
  libs/ml/tests/unit/ops/activations/randomised_relu.cpp
  libs/ml/tests/unit/optimisation/optimisers.cpp
  libs/ml/tests/unit/optimisation/sparse_optimisers.cpp
  libs/vm-modules/tests/unit/ml.cpp
Labels: S-ready-to-merge

#1939 graph every op serialise test - wip
  libs/math/include/math/metrics/cross_entropy.hpp
  libs/ml/include/ml/ops/avg_pool_2d.hpp
  libs/ml/include/ml/ops/convolution_2d.hpp
  libs/ml/include/ml/ops/log.hpp
  libs/ml/include/ml/ops/matrix_multiply.hpp
  libs/ml/include/ml/ops/max_pool.hpp
  libs/ml/include/ml/ops/max_pool_2d.hpp
  libs/ml/include/ml/saveparams/saveable_params.hpp
  libs/ml/include/ml/serializers/ml_types.hpp
  libs/ml/tests/unit/graph/graph_every_op.cpp
Labels: S-ready-to-merge

#1970 Remove unnecessary call to UnInitialise
  libs/vm/include/vm/analyser.hpp
  libs/vm/include/vm/compiler.hpp
Labels: S-ready-to-merge

#1888 Rearrange and add null support to msgpack
  libs/core/include/core/serializers/counter.hpp
  libs/core/include/core/serializers/group_definitions.hpp
  libs/core/include/core/serializers/main_serializer_definition.hpp
  libs/core/src/serializers/main_serializer.cpp
  libs/core/tests/serializers/variants.cpp
  libs/muddle/tests/integration/rbc_tests.cpp
  libs/muddle/tests/unit/rbc_messages.cpp
  libs/network/tests/CMakeLists.txt
  libs/network/tests/integration/tcp_client_server_stress_tests.cpp
  libs/network/tests/integration/tcp_client_stress_tests.cpp
  libs/network/tests/integration/thread_manager_stress_tests.cpp
  libs/network/tests/integration/thread_pool_tests.cpp
  libs/network/tests/unit/callable_tests.cpp
  libs/network/tests/unit/p2ptrust_bayrank.cpp
  libs/network/tests/unit/p2ptrust_tests.cpp
  libs/network/tests/unit/peer_tests.cpp
  libs/network/tests/unit/uri_tests.cpp
  libs/variant/include/variant/variant.hpp
  libs/variant/tests/unit/serialization.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1955 TX malleability End 2 End test
  scripts/end_to_end_test/end_to_end_test.yaml
  scripts/end_to_end_test/smart_contract_tests/malleability_test.py
  scripts/install-test-dependencies.sh
Labels: S-ready-to-merge

#1961 Bugfix/boolean mask
  libs/math/include/math/matrix_operations.hpp
  libs/math/tests/unit/matrix_operations/matrix_operations.cpp
Labels: C-bug, S-ready-to-merge

#1971 Fix multidigit FixedPoint tokenisation bug
  libs/vm-modules/tests/unit/fixed_point.cpp
  libs/vm/include/vm/tokeniser.hpp
  libs/vm/scripts/tokeniser.l
  libs/vm/src/tokeniser.cpp
Labels: C-bug, S-ready-to-merge

#1977 Catch promise timeout to obj store protocol
  apps/oef-core/MtCore.cpp
  libs/dmlf/examples/etch_client/main.cpp
  libs/dmlf/examples/etch_node/main.cpp
  libs/dmlf/tests/colearn_muddle/colearn_muddle.cpp
  libs/dmlf/tests/muddle/muddle_test.cpp
  libs/ledger/src/genesis_file_creator.cpp
  libs/ledger/src/storage_unit/storage_unit_client.cpp
  libs/ledger/src/transaction_processor.cpp
  libs/ledger/tests/chain/transaction_status_cache_tests.cpp
  libs/math/tests/unit/basic_math/big_number_tests.cpp
  libs/oef-base/include/oef-base/threading/FutureCombiner.hpp
  libs/oef-base/include/oef-base/threading/StateMachineTask.hpp
  libs/oef-base/include/oef-base/threading/TNonBlockingWorkerTask.hpp
  libs/oef-base/include/oef-base/threading/Threadpool.hpp
  libs/oef-base/src/comms/EndpointBase.cpp
  libs/oef-base/src/conversation/OutboundConversationWorkerTask.cpp
  libs/oef-base/src/threading/Taskpool.cpp
  libs/oef-core/examples/mt-core/MtCore.cpp
  libs/oef-core/examples/mt-core/main.cpp
  libs/oef-core/include/oef-core/comms/public_key_utils.hpp
  libs/oef-core/src/comms/EndpointSSL.cpp
  libs/oef-core/src/oef-functions/InitialHandshakeTaskFactory.cpp
  libs/oef-search/examples/search-node/main.cpp
  libs/oef-search/include/oef-search/dap_comms/DapConversationTask.hpp
  libs/oef-search/include/oef-search/functions/ReplyMethods.hpp
  libs/oef-search/src/dap_manager/NodeExecutorFactory.cpp
  libs/oef-search/src/functions/DirectorTaskFactory.cpp
  libs/oef-search/src/functions/SearchTaskFactory.cpp
  libs/semanticsearch/src/semanticsearch/query/query_executor.cpp
  libs/semanticsearch/tests/unit/index.cpp
  libs/vm-modules/src/core/structured_data.cpp
  libs/vm-modules/src/math/bignumber.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1969 COLE-58 Easier muddle-colearn setup
  libs/dmlf/include/dmlf/colearn/muddle_learner_networker_impl.hpp
  libs/dmlf/src/colearn/muddle_learner_networker_impl.cpp
  libs/dmlf/tests/colearn_muddle/colearn_muddle.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1951 Sparse updates for distributed learning
  libs/dmlf/include/dmlf/collective_learning/client_algorithm.hpp
  libs/dmlf/include/dmlf/collective_learning/client_word2vec_algorithm.hpp
  libs/dmlf/include/dmlf/collective_learning/translator.hpp
  libs/dmlf/include/dmlf/update.hpp
  libs/ml/include/ml/core/graph.hpp
  libs/ml/include/ml/ops/trainable.hpp
  libs/ml/include/ml/ops/variable.hpp
  libs/ml/include/ml/ops/weights.hpp
  libs/ml/include/ml/optimisation/sgd_optimiser.hpp
  libs/ml/include/ml/utilities/sparse_tensor_utilities.hpp
  libs/ml/tests/unit/utilities/sparse.cpp
Labels: A-ml, S-ready-to-merge

#1976 Expose instance context to member fn estimators
  libs/meta/include/meta/tuple.hpp
  libs/meta/tests/unit/tuple_tests.cpp
  libs/vm-modules/tests/unit/vm_charge_tests.cpp
  libs/vm/include/vm/module.hpp
  libs/vm/include/vm/module/binding_interfaces.hpp
  libs/vm/include/vm/module/free_function_invoke.hpp
  libs/vm/include/vm/module/member_function_invoke.hpp
  libs/vm/include/vm/module/prepare_invocation.hpp
Labels: S-ready-for-review, S-ready-to-merge

#1964 Bug/fixed point conversion basic vm engine [COLE-57]
  libs/dmlf/include/dmlf/execution/basic_vm_engine.hpp
  libs/dmlf/src/basic_vm_engine.cpp
  libs/dmlf/tests/execution/basic_engine_tests.cpp
Labels: S-ready-to-merge

#1973 Fix bugs related to removing blocks
  libs/ledger/include/ledger/chain/block_coordinator.hpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/chain/main_chain.cpp
  scripts/end_to_end_test/smart_contract_tests/synergetic_utils.py
Labels: S-ready-for-review, S-ready-to-merge

#1984 Fix for segfault in beacon tests
  libs/beacon/tests/unit/dkg_resilience.cpp
Labels: S-ready-to-merge

#1986 Telemetry Fixes
  libs/http/src/middleware/telemetry.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1975 Validation Checks for Multi-Sig Wallets
  libs/chain/include/chain/transaction.hpp
  libs/chain/include/chain/transaction_layout.hpp
  libs/chain/include/chain/transaction_layout_rpc_serializers.hpp
  libs/chain/src/transaction.cpp
  libs/chain/src/transaction_builder.cpp
  libs/chain/src/transaction_layout.cpp
  libs/chain/src/transaction_serializer.cpp
  libs/chain/tests/unit/transaction_layout_tests.cpp
  libs/chain/tests/unit/transaction_serializer_tests.cpp
  libs/ledger/include/ledger/chaincode/deed.hpp
  libs/ledger/include/ledger/chaincode/token_contract.hpp
  libs/ledger/include/ledger/chaincode/wallet_record.hpp
  libs/ledger/include/ledger/execution_item.hpp
  libs/ledger/include/ledger/execution_result.hpp
  libs/ledger/include/ledger/executor.hpp
  libs/ledger/include/ledger/transaction_validator.hpp
  libs/ledger/include/ledger/tx_status_http_interface.hpp
  libs/ledger/src/chaincode/deed.cpp
  libs/ledger/src/chaincode/token_contract.cpp
  libs/ledger/src/chaincode/wallet_record.cpp
  libs/ledger/src/execution_manager.cpp
  libs/ledger/src/executor.cpp
  libs/ledger/src/miner/basic_miner.cpp
  libs/ledger/src/transaction_validator.cpp
  libs/ledger/src/tx_query_http_interface.cpp
  libs/ledger/src/tx_status_http_interface.cpp
  libs/ledger/tests/unit/transaction_layout_queue_tests.cpp
  libs/ledger/tests/unit/transaction_validator_tests.cpp
  libs/vm-modules/include/vm_modules/ledger/transaction.hpp
  libs/vm-modules/src/ledger/transaction.cpp
  scripts/generate_coverage.py
Labels: C-bug, S-ready-for-review, S-ready-to-merge

#1981 Bugfix: ml-224, UInt256 issues and testing
  libs/math/tests/unit/basic_math/big_number_tests.cpp
  libs/vectorise/include/vectorise/uint/uint.hpp
  libs/vm-modules/tests/unit/big_number_wrapper_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1990 Revert to default SSL certification verification
  libs/http/src/https_client.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1978 Muddle Secure Message Support
  libs/crypto/include/crypto/block_cipher.hpp
  libs/crypto/include/crypto/ecdh.hpp
  libs/crypto/include/crypto/ecdsa.hpp
  libs/crypto/include/crypto/openssl_ecdsa_private_key.hpp
  libs/crypto/include/crypto/secure_channel.hpp
  libs/crypto/internal/aes.hpp
  libs/crypto/src/aes.cpp
  libs/crypto/src/block_cipher.cpp
  libs/crypto/src/ecdh.cpp
  libs/crypto/src/secure_channel.cpp
  libs/crypto/tests/CMakeLists.txt
  libs/crypto/tests/unit/aes_tests.cpp
  libs/crypto/tests/unit/block_cipher_tests.cpp
  libs/crypto/tests/unit/ecdh_tests.cpp
  libs/crypto/tests/unit/secure_channel_tests.cpp
  libs/muddle/include/muddle/packet.hpp
  libs/muddle/internal/muddle.hpp
  libs/muddle/internal/router.hpp
  libs/muddle/src/muddle.cpp
  libs/muddle/src/muddle_interface.cpp
  libs/muddle/src/router.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1979 Filter txs by validity
  libs/ledger/include/ledger/chain/block.hpp
  libs/ledger/src/miner/basic_miner.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1988 UInt64 etch type initialization fixed
  libs/vm/src/generator.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1982 Implemented StridedSlice
  libs/math/include/math/tensor.hpp
  libs/math/include/math/tensor_slice_iterator.hpp
  libs/ml/include/ml/exceptions/exceptions.hpp
  libs/ml/include/ml/meta/ml_type_traits.hpp
  libs/ml/include/ml/ops/strided_slice.hpp
  libs/ml/include/ml/saveparams/saveable_params.hpp
  libs/ml/include/ml/serializers/ml_types.hpp
  libs/ml/include/ml/utilities/graph_builder.hpp
  libs/ml/tests/unit/ops/strided_slice.cpp
Labels: A-ml, S-ready-for-review, S-ready-to-merge

#1991 Improve ledger recovery at genesis
  libs/beacon/src/beacon_service.cpp
  libs/constellation/include/constellation/constellation.hpp
  libs/constellation/src/constellation.cpp
  libs/ledger/include/ledger/genesis_loading/genesis_file_creator.hpp
  libs/ledger/src/consensus/consensus.cpp
  libs/ledger/src/genesis_file_creator.cpp
  libs/muddle/internal/router.hpp
  libs/muddle/src/router.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1987 fix SetLogLevel
  libs/logging/src/logging.cpp
Labels: S-ready-to-merge

#1996 Correct packet header packing so it is backwards compatible
  libs/muddle/include/muddle/packet.hpp
Labels: S-ready-for-review, S-ready-to-merge

#1997 Genesis state file consistent storage location
  libs/constellation/include/constellation/constellation.hpp
  libs/constellation/src/constellation.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1998 Avoid unneccessary python backtraces when running ci tool
  scripts/ci-tool.py
  scripts/fetchai_netutils/fetch/testing/testcase.py
Labels: S-ready-for-review, S-ready-to-merge

#1968 Etch large literals
  libs/vm/include/vm/analyser.hpp
  libs/vm/include/vm/common.hpp
  libs/vm/include/vm/fixed.hpp
  libs/vm/include/vm/generator.hpp
  libs/vm/include/vm/opcodes.hpp
  libs/vm/include/vm/token.hpp
  libs/vm/include/vm/tokeniser.hpp
  libs/vm/include/vm/vm.hpp
  libs/vm/scripts/tokeniser.l
  libs/vm/src/analyser.cpp
  libs/vm/src/fixed.cpp
  libs/vm/src/generator.cpp
  libs/vm/src/parser.cpp
  libs/vm/src/tokeniser.cpp
  libs/vm/src/vm.cpp
  libs/vm/src/vm_handlers.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1999 Bugfix/ml 224 uint256 issues
  libs/math/tests/unit/basic_math/big_number_tests.cpp
  libs/vectorise/include/vectorise/uint/uint.hpp
  libs/vm-modules/src/math/bignumber.cpp
  libs/vm-modules/tests/unit/big_number_wrapper_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2001 Added accuracy metric
  libs/ml/include/ml/meta/ml_type_traits.hpp
  libs/ml/include/ml/ops/loss_functions/mean_square_error_loss.hpp
  libs/ml/include/ml/ops/metrics/categorical_accuracy.hpp
  libs/ml/include/ml/saveparams/saveable_params.hpp
  libs/ml/include/ml/serializers/ml_types.hpp
  libs/ml/tests/unit/ops/metrics/categorical_accuracy.cpp
Labels: S-ready-to-merge

#1901 Benchmark aggregate signatures and implementation improvements
  libs/beacon/include/beacon/notarisation_manager.hpp
  libs/beacon/src/notarisation_manager.cpp
  libs/crypto/benchmark/aggregate_signing.cpp
  libs/crypto/benchmark/bls_signing_and_verification.cpp
  libs/crypto/include/crypto/mcl_dkg.hpp
  libs/crypto/src/mcl_dkg.cpp
  libs/crypto/tests/unit/mcl_dkg_tests.cpp
  libs/ledger/include/ledger/protocols/notarisation_service.hpp
  libs/ledger/src/protocols/notarisation_service.cpp
Labels: S-ready-for-review, S-ready-to-merge

#1962 Update entropy benchmark with most recent seen entropy
  libs/beacon/benchmark/entropy_gen_bench.cpp
  libs/beacon/src/beacon_setup_service.cpp
  libs/beacon/tests/unit/trusted_dealer_test.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2005 Dev/pick more than one starting peer
  libs/dmlf/src/networkers/muddle_learner_networker.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2002 Simple improvement to end-to-end tests.
  scripts/ci-tool.py
  scripts/end_to_end_test/run_end_to_end_test.py
  scripts/fetchai_netutils/fetch/testing/testcase.py
Labels: A-ci, C-improvement, S-ready-for-review, S-ready-to-merge

#2007 catch manifest query promise timeout
  libs/shards/src/shard_management_service.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2009 Miscellaneous changes
  libs/muddle/tests/unit/promise_tests.cpp
  libs/oef-core/src/comms/OefAgentEndpoint.cpp
  libs/oef-core/src/karma/KarmaPolicyBasic.cpp
  libs/oef-core/src/oef-functions/OefFunctionsTaskFactory.cpp
  libs/oef-core/src/tasks/OefLoginTimeoutTask.cpp
  libs/vm/include/vm/analyser.hpp
  libs/vm/include/vm/compiler.hpp
  libs/vm/include/vm/module.hpp
Labels: S-ready-for-review, S-ready-to-merge

#2003 add new id for the Colab Learning broadcast channel
  libs/core/include/core/service_ids.hpp
Labels: S-ready-for-review, S-ready-to-merge

#2011 Extending StructuredData with support for Address, Uint256 and Buffer
  libs/core/include/core/byte_array/encoders.hpp
  libs/core/src/byte_array/encoders.cpp
  libs/math/tests/unit/basic_math/big_number_tests.cpp
  libs/vectorise/include/vectorise/uint/uint.hpp
  libs/vm-modules/include/vm_modules/core/structured_data.hpp
  libs/vm-modules/src/core/structured_data.cpp
  libs/vm-modules/src/vm_factory.cpp
  libs/vm-modules/tests/unit/state_tests.cpp
  libs/vm-modules/tests/unit/vm_test_toolkit.hpp
Labels: A-api, C-feature, C-proposal, S-ready-for-review, S-ready-to-merge

#2008 Tokenisation: prevent leading zeros and dangling decimal points
  libs/vm-modules/tests/unit/core_etch_tests.cpp
  libs/vm-modules/tests/unit/parameter_serialization.cpp
  libs/vm-modules/tests/unit/vm_test_toolkit.hpp
  libs/vm/include/vm/tokeniser.hpp
  libs/vm/scripts/tokeniser.l
  libs/vm/src/tokeniser.cpp
Labels: S-ready-for-review

#2018 Extend option to run tests selectively to slow, unit, integration
  scripts/ci-tool.py
Labels: S-ready-for-review, S-ready-to-merge

#2014 Dev/colearn uses muddle bcast
  libs/dmlf/include/dmlf/colearn/muddle_learner_networker_impl.hpp
  libs/dmlf/include/dmlf/colearn/muddle_outbound_update_task.hpp
  libs/dmlf/src/colearn/muddle_learner_networker_impl.cpp
  libs/dmlf/src/colearn/muddle_outbound_update_task.cpp
  libs/dmlf/tests/colearn_muddle/colearn_muddle.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2023 fix bug with contract function invocation
  libs/vm/src/analyser.cpp
Labels: S-ready-for-review

#1985 Implement limit for DKG transaction time
  libs/beacon/include/beacon/beacon_setup_service.hpp
  libs/beacon/src/beacon_setup_service.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2027 Add option for millisecond epoch
  libs/moment/include/moment/clocks.hpp
  libs/moment/src/clocks.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2000 Deprecate old learner networkers implementations - Add AbstractMessageController API [COLE-72][COLE-73]
  libs/dmlf/examples/boston_housing_distributed_learning/main.cpp
  libs/dmlf/examples/boston_housing_multiprocess_distributed_learning/main.cpp
  libs/dmlf/examples/mnist_distributed_learning/main.cpp
  libs/dmlf/examples/mnist_multiprocess_distributed_learning/main.cpp
  libs/dmlf/examples/word2vec_distributed_learning/main.cpp
  libs/dmlf/examples/word2vec_multiprocess_distributed_learning/main.cpp
  libs/dmlf/include/dmlf/colearn/abstract_message_controller.hpp
  libs/dmlf/include/dmlf/colearn/muddle_learner_networker_impl.hpp
  libs/dmlf/include/dmlf/colearn/muddle_outbound_update_task.hpp
  libs/dmlf/include/dmlf/collective_learning/client_algorithm.hpp
  libs/dmlf/include/dmlf/collective_learning/client_algorithm_controller.hpp
  libs/dmlf/include/dmlf/collective_learning/client_word2vec_algorithm.hpp
  libs/dmlf/include/dmlf/collective_learning/collective_learning_client.hpp
  libs/dmlf/include/dmlf/collective_learning/utilities/boston_housing_client_utilities.hpp
  libs/dmlf/include/dmlf/collective_learning/utilities/mnist_client_utilities.hpp
  libs/dmlf/include/dmlf/collective_learning/utilities/type_map.hpp
  libs/dmlf/include/dmlf/collective_learning/utilities/typed_update_adaptor.hpp
  libs/dmlf/include/dmlf/deprecated/abstract_learner_networker.hpp
  libs/dmlf/include/dmlf/deprecated/filepassing_learner_networker.hpp
  libs/dmlf/include/dmlf/deprecated/local_learner_networker.hpp
  libs/dmlf/include/dmlf/deprecated/muddle_learner_networker.hpp
  libs/dmlf/include/dmlf/deprecated/queue.hpp
  libs/dmlf/include/dmlf/deprecated/queue_interface.hpp
  libs/dmlf/include/dmlf/deprecated/shuffle_algorithm_interface.hpp
  libs/dmlf/include/dmlf/deprecated/simple_cycling_algorithm.hpp
  libs/dmlf/include/dmlf/deprecated/type_map.hpp
  libs/dmlf/include/dmlf/deprecated/update.hpp
  libs/dmlf/include/dmlf/deprecated/update_interface.hpp
  libs/dmlf/src/colearn/muddle_learner_networker_impl.cpp
  libs/dmlf/src/deprecated/abstract_learner_networker.cpp
  libs/dmlf/src/deprecated/filepassing_learner_networker.cpp
  libs/dmlf/src/deprecated/local_learner_networker.cpp
  libs/dmlf/src/deprecated/muddle_learner_networker.cpp
  libs/dmlf/src/deprecated/shuffle_algorithm_interface.cpp
  libs/dmlf/src/deprecated/simple_cycling_algorithm.cpp
  libs/dmlf/tests/CMakeLists.txt
  libs/dmlf/tests/colearn_muddle/colearn_muddle.cpp
  libs/dmlf/tests/deprecated/local_tests.cpp
  libs/dmlf/tests/deprecated/muddle_test.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2030 guard against loose blocks when verifying
  libs/ledger/include/ledger/consensus/consensus.hpp
  libs/ledger/src/consensus/consensus.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2017 Remove POW code and refactor
  libs/constellation/include/constellation/constellation.hpp
  libs/constellation/src/constellation.cpp
  libs/ledger/include/ledger/chain/block.hpp
  libs/ledger/include/ledger/chain/block_coordinator.hpp
  libs/ledger/include/ledger/chain/consensus/bad_miner.hpp
  libs/ledger/include/ledger/chain/consensus/dummy_miner.hpp
  libs/ledger/include/ledger/chain/consensus/proof_of_work.hpp
  libs/ledger/include/ledger/chain/main_chain.hpp
  libs/ledger/include/ledger/consensus/consensus.hpp
  libs/ledger/include/ledger/consensus/consensus_interface.hpp
  libs/ledger/include/ledger/consensus/simulated_pow_consensus.hpp
  libs/ledger/include/ledger/genesis_loading/genesis_file_creator.hpp
  libs/ledger/src/chain/block.cpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/chain/consensus/bad_miner.cpp
  libs/ledger/src/chain/consensus/dummy_miner.cpp
  libs/ledger/src/chain/consensus/proof_of_work.cpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/src/consensus/consensus.cpp
  libs/ledger/src/consensus/simulated_pow_consensus.cpp
  libs/ledger/src/genesis_file_creator.cpp
  libs/ledger/src/protocols/main_chain_rpc_service.cpp
  libs/ledger/src/testing/block_generator.cpp
  libs/ledger/tests/CMakeLists.txt
  libs/ledger/tests/chain/block_coordinator_tests.cpp
  libs/ledger/tests/chain/main_chain_subtree_tests.cpp
  libs/ledger/tests/chain/main_chain_tests.cpp
  libs/ledger/tests/consensus/main_chain_tests.cpp
  libs/ledger/tests/consensus/proof_of_work_tests.cpp
  libs/ledger/tests/consensus/simulated_pow_tests.cpp
  libs/ledger/tests/notarisation/notarisation_tests.cpp
  libs/network/include/network/p2pservice/p2p_http_interface.hpp
  scripts/end_to_end_test/run_end_to_end_test.py
Labels: S-ready-for-review, S-ready-to-merge

#2032 Single line comment fix
  libs/vm/include/vm/tokeniser.hpp
  libs/vm/scripts/tokeniser.l
  libs/vm/src/tokeniser.cpp
Labels: S-ready-to-merge

#2020 Peer Selector Override
  libs/ledger/src/storage_unit/transaction_store_sync_service.cpp
  libs/muddle/internal/direct_message_service.hpp
  libs/muddle/internal/peer_selector.hpp
  libs/muddle/src/muddle_status.cpp
  libs/muddle/src/peer_selector.cpp
  libs/muddle/src/promise_runnable.cpp
  libs/muddle/tests/unit/fake_muddle_endpoint.cpp
  libs/muddle/tests/unit/fake_muddle_endpoint.hpp
  libs/muddle/tests/unit/mock_muddle_endpoint.hpp
  libs/muddle/tests/unit/peer_selector_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2025 Switch Wallet Record to MapSerialiser
  libs/ledger/include/ledger/chaincode/wallet_record.hpp
Labels: S-ready-for-review, S-ready-to-merge

#2034 fix timing in pow test
  libs/ledger/src/consensus/simulated_pow_consensus.cpp
  libs/ledger/tests/consensus/simulated_pow_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2022 bugfixes to model workflow & serialisation
  libs/ml/include/ml/model/model.hpp
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/tests/unit/ml.cpp
Labels: S-ready-to-merge

#2016 Bugfix/ml 224 uint256 issues
  libs/math/tests/unit/basic_math/big_number_tests.cpp
  libs/vectorise/include/vectorise/uint/uint.hpp
  libs/vm-modules/include/vm_modules/math/bignumber.hpp
  libs/vm-modules/src/math/bignumber.cpp
  libs/vm-modules/tests/unit/big_number_wrapper_tests.cpp
  libs/vm/include/vm/common.hpp
Labels: A-maths, A-vm, S-ready-for-review, S-ready-to-merge

#2026 Feature/ml 145 fp128 etch bindings
  libs/math/tests/unit/fixed_point/fixed_point.cpp
  libs/meta/include/meta/type_traits.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_fixed64.hpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
  libs/vectorise/include/vectorise/fixed_point/type_traits.hpp
  libs/vectorise/include/vectorise/platform.hpp
  libs/vectorise/include/vectorise/uint/int.hpp
  libs/vm-modules/examples/fixedpoint/fixed_point.etch
  libs/vm-modules/include/vm_modules/core/structured_data.hpp
  libs/vm-modules/src/core/print.cpp
  libs/vm-modules/src/core/structured_data.cpp
  libs/vm-modules/src/core/type_convert.cpp
  libs/vm-modules/src/math/abs.cpp
  libs/vm-modules/src/math/exp.cpp
  libs/vm-modules/src/math/log.cpp
  libs/vm-modules/src/math/pow.cpp
  libs/vm-modules/src/math/sqrt.cpp
  libs/vm-modules/src/math/trigonometry.cpp
  libs/vm-modules/tests/unit/fixed_point.cpp
  libs/vm-modules/tests/unit/state_tests.cpp
  libs/vm/include/vm/array.hpp
  libs/vm/include/vm/fixed.hpp
  libs/vm/include/vm/generator.hpp
  libs/vm/include/vm/object.hpp
  libs/vm/src/analyser.cpp
  libs/vm/src/fixed.cpp
  libs/vm/src/module.cpp
  libs/vm/tests/unit/variant.cpp
Labels: A-maths, A-vm, C-feature, S-ready-for-review, S-ready-to-merge

#2004 VMModel AddLayer refactoring
  libs/vm-modules/include/vm_modules/ml/graph.hpp
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/tests/unit/ml.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2038 bugfixed + character handling by tensor
  libs/math/include/math/tensor.hpp
Labels: S-ready-for-review, S-ready-to-merge

#2006 VMTensor .At() and .setAt() methods refactoring
  libs/vm-modules/include/vm_modules/math/tensor.hpp
  libs/vm-modules/src/math/tensor.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2040 Feature/print hex fixedpoint compile option
  CMakeLists.txt
  cmake/BuildTargets.cmake
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
Labels: A-maths, C-feature, S-ready-for-review, S-ready-to-merge

#2039 Extracted all VMModel-related tests in a separate file
  libs/vm-modules/tests/unit/ml.cpp
  libs/vm-modules/tests/unit/ml_model_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2024 Add metrics for model
  libs/ml/include/ml/meta/ml_type_traits.hpp
  libs/ml/include/ml/model/model.hpp
  libs/ml/include/ml/ops/metrics/types.hpp
  libs/ml/include/ml/serializers/ml_types.hpp
  libs/ml/include/ml/utilities/graph_builder.hpp
  libs/ml/tests/unit/graph/graph_every_op.cpp
  libs/ml/tests/unit/layers/PRelu.cpp
  libs/ml/tests/unit/model/dnn_classifier_test.cpp
  libs/vm-modules/src/ml/model/model.cpp
Labels: S-ready-to-merge

#2035 bugfix disabled test fixtures
  libs/math/tests/unit/basic_math/big_number_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2031 Dev/stochastic as shufflealg
  libs/dmlf/examples/boston_housing_distributed_learning/main.cpp
  libs/dmlf/examples/boston_housing_multiprocess_distributed_learning/main.cpp
  libs/dmlf/examples/mnist_distributed_learning/main.cpp
  libs/dmlf/examples/mnist_multiprocess_distributed_learning/main.cpp
  libs/dmlf/examples/word2vec_distributed_learning/main.cpp
  libs/dmlf/examples/word2vec_multiprocess_distributed_learning/main.cpp
  libs/dmlf/include/dmlf/colearn/muddle_learner_networker_impl.hpp
  libs/dmlf/include/dmlf/deprecated/abstract_learner_networker.hpp
  libs/dmlf/include/dmlf/shuffle_algorithm_interface.hpp
  libs/dmlf/include/dmlf/simple_cycling_algorithm.hpp
  libs/dmlf/include/dmlf/stochastic_reception_algorithm.hpp
  libs/dmlf/src/colearn/muddle_learner_networker_impl.cpp
  libs/dmlf/src/colearn/muddle_outbound_update_task.cpp
  libs/dmlf/src/deprecated/simple_cycling_algorithm.cpp
  libs/dmlf/src/shuffle_algorithm_interface.cpp
  libs/dmlf/tests/colearn_muddle/colearn_muddle.cpp
  libs/dmlf/tests/deprecated/local_tests.cpp
  libs/dmlf/tests/deprecated/muddle_test.cpp
Labels: S-ready-to-merge

#2021 Dev/update store smart [Cole-50][Cole-43]
  libs/dmlf/include/dmlf/colearn/colearn_update.hpp
  libs/dmlf/include/dmlf/colearn/update_store.hpp
  libs/dmlf/include/dmlf/colearn/update_store_interface.hpp
  libs/dmlf/src/colearn_update.cpp
  libs/dmlf/src/update_store.cpp
  libs/dmlf/tests/colearn/update_store_test.cpp
Labels: S-ready-to-merge

#2044 adding ml team members as CODEOWNERS for dmlf
  .github/CODEOWNERS
Labels: S-ready-to-merge

#2042 Memleak fix in Nodes by using weak_ptr instead of shared_ptr
  libs/ml/include/ml/core/graph.hpp
  libs/ml/include/ml/core/node.hpp
Labels: A-ml, S-ready-for-review, S-ready-to-merge
