Repository fetchai/ledger, pull requests merged in 2019-12, with the labels that each got.

#2048 Etch unterminated comments fix
  libs/vm/include/vm/token.hpp
  libs/vm/include/vm/tokeniser.hpp
  libs/vm/scripts/tokeniser.l
  libs/vm/src/parser.cpp
  libs/vm/src/tokeniser.cpp
Labels: S-ready-to-merge

#1965 Misc dmlf example improvements
  libs/dmlf/examples/boston_housing_multiprocess_distributed_learning/main.cpp
  libs/dmlf/examples/mnist_distributed_learning/main.cpp
  libs/dmlf/examples/mnist_multiprocess_distributed_learning/main.cpp
  libs/dmlf/examples/word2vec_distributed_learning/main.cpp
  libs/dmlf/examples/word2vec_multiprocess_distributed_learning/main.cpp
  libs/dmlf/include/dmlf/collective_learning/client_algorithm.hpp
  libs/dmlf/include/dmlf/collective_learning/client_params.hpp
  libs/dmlf/include/dmlf/collective_learning/client_word2vec_algorithm.hpp
  libs/dmlf/include/dmlf/collective_learning/utilities/mnist_client_utilities.hpp
  libs/dmlf/include/dmlf/collective_learning/utilities/utilities.hpp
  libs/dmlf/include/dmlf/deprecated/muddle_learner_networker.hpp
  libs/dmlf/src/deprecated/muddle_learner_networker.cpp
  libs/dmlf/tests/deprecated/muddle_test.cpp
  libs/ml/include/ml/dataloaders/tensor_dataloader.hpp
  libs/ml/include/ml/model/model.hpp
Labels: S-ready-for-review, S-ready-to-merge

#2041 VMModel error handling improved and tests added
  libs/ml/include/ml/model/sequential.hpp
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/tests/unit/ml_model_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2050 Dev/improve stochastic shuffle interface
  libs/dmlf/include/dmlf/colearn/muddle_learner_networker_impl.hpp
  libs/dmlf/src/colearn/muddle_learner_networker_impl.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2052 Dev/clamp bcast props
  libs/dmlf/include/dmlf/colearn/muddle_learner_networker_impl.hpp
  libs/dmlf/src/colearn/muddle_learner_networker_impl.cpp
Labels: S-ready-for-review

#2046 Use injected host and port in e2e test
  scripts/end_to_end_test/smart_contract_tests/malleability_test.py
Labels: S-ready-for-review, S-ready-to-merge

#2047 Make StorageInterface::Get const
  libs/ledger/benchmark/in_memory_storage.cpp
  libs/ledger/benchmark/in_memory_storage.hpp
  libs/ledger/include/ledger/storage_unit/cached_storage_adapter.hpp
  libs/ledger/include/ledger/storage_unit/fake_storage_unit.hpp
  libs/ledger/include/ledger/storage_unit/storage_unit_client.hpp
  libs/ledger/include/ledger/storage_unit/storage_unit_interface.hpp
  libs/ledger/src/storage_unit/cached_storage_adapter.cpp
  libs/ledger/src/storage_unit/fake_storage_unit.cpp
  libs/ledger/src/storage_unit/storage_unit_client.cpp
  libs/ledger/tests/chain/mock_storage_unit.hpp
  libs/ledger/tests/chaincode/mock_storage_unit.hpp
  libs/ledger/tests/unit/cached_storage_adapter_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2057 Improvement/Log levels to ci-tool
  libs/muddle/src/rbc.cpp
  scripts/ci-tool.py
Labels: A-ci, C-improvement, S-ready-for-review, S-ready-to-merge

#1923 Improvement/ stutter block removal
  libs/ledger/include/ledger/chain/main_chain.hpp
  libs/ledger/include/ledger/consensus/consensus.hpp
  libs/ledger/include/ledger/protocols/notarisation_service.hpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/src/consensus/consensus.cpp
  libs/ledger/src/protocols/notarisation_service.cpp
  libs/ledger/tests/chain/main_chain_tests.cpp
  libs/ledger/tests/notarisation/notarisation_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2056 Test recent comment-related changes
  libs/vm-modules/tests/unit/core_language/comments_tests.cpp
  libs/vm-modules/tests/unit/core_language/core_etch_tests.cpp
Labels: S-ready-for-review

#2055 Dev/colearn uri [COLE-63]
  libs/dmlf/include/dmlf/colearn/colearn_uri.hpp
  libs/dmlf/include/dmlf/colearn/update_store.hpp
  libs/dmlf/include/dmlf/colearn/update_store_interface.hpp
  libs/dmlf/src/colearn/colearn_uri.cpp
  libs/dmlf/src/update_store.cpp
  libs/dmlf/tests/colearn/colearn_uri_test.cpp
  libs/dmlf/tests/colearn/update_store_test.cpp
Labels: S-ready-to-merge

#1907 Adaptive Bloom filter based on valid_until
  libs/bloom-filter/include/bloom_filter/bloom_filter.hpp
  libs/bloom-filter/include/bloom_filter/progressive_bloom_filter.hpp
  libs/bloom-filter/src/bloom_filter.cpp
  libs/bloom-filter/src/progressive_bloom_filter.cpp
  libs/bloom-filter/tests/unit/progressive_bloom_filter_tests.cpp
  libs/chain/include/chain/transaction.hpp
  libs/chain/include/chain/transaction_validity_period.hpp
  libs/chain/src/transaction.cpp
  libs/constellation/src/constellation.cpp
  libs/core/include/core/byte_array/const_byte_array.hpp
  libs/core/include/core/feature_flags.hpp
  libs/core/include/core/serializers/main_serializer_definition.hpp
  libs/core/include/core/serializers/map_interface.hpp
  libs/ledger/benchmark/main_chain_benchs.cpp
  libs/ledger/include/ledger/chain/block.hpp
  libs/ledger/include/ledger/chain/main_chain.hpp
  libs/ledger/include/ledger/miner/transaction_layout_queue.hpp
  libs/ledger/include/ledger/transaction_validator.hpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/src/miner/basic_miner.cpp
  libs/ledger/src/miner/transaction_layout_queue.cpp
  libs/ledger/src/transaction_validator.cpp
  libs/ledger/tests/chain/block_coordinator_tests.cpp
  libs/ledger/tests/chain/main_chain_subtree_tests.cpp
  libs/ledger/tests/chain/main_chain_tests.cpp
  libs/ledger/tests/notarisation/notarisation_tests.cpp
  libs/ledger/tests/unit/basic_miner_tests.cpp
  libs/vm/src/generator.cpp
  scripts/ci-tool.py
  scripts/fetchai_netutils/fetch/cluster/apps/swarm.py
  scripts/fetchai_netutils/fetch/cluster/instance.py
  scripts/fetchai_netutils/fetch/cluster/monitor.py
Labels: S-ready-for-review

#2064 VMModel serialisation fix for large models
  libs/vm-modules/src/ml/model/model.cpp
Labels: S-ready-for-review

#2062 Bug/flaky update test
  libs/dmlf/tests/colearn/update_store_test.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2061 Dev/add json helper to dmlfimpl
  libs/dmlf/include/dmlf/colearn/muddle_learner_networker_impl.hpp
  libs/dmlf/src/colearn/muddle_learner_networker_impl.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2067 Feature/ml 283 replace double conversions
  libs/math/tests/unit/fixed_point/fixed_point.cpp
  libs/vectorise/CMakeLists.txt
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
  libs/vectorise/src/fixed_point/fixed_point.cpp
Labels: A-maths, C-improvement, S-ready-to-merge

#1994 Improvement/forward sync
  libs/constellation/src/constellation.cpp
  libs/ledger/CMakeLists.txt
  libs/ledger/include/ledger/chain/block.hpp
  libs/ledger/include/ledger/chain/main_chain.hpp
  libs/ledger/include/ledger/chain/time_travelogue.hpp
  libs/ledger/include/ledger/consensus/simulated_pow_consensus.hpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_protocol.hpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_service.hpp
  libs/ledger/src/chain/block.cpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/src/consensus/simulated_pow_consensus.cpp
  libs/ledger/src/protocols/main_chain_rpc_service.cpp
  libs/ledger/tests/chain/block_coordinator_tests.cpp
  libs/ledger/tests/chain/main_chain_tests.cpp
  libs/ledger/tests/consensus/simulated_pow_tests.cpp
  libs/logging/CMakeLists.txt
Labels: A-ledger, C-improvement, S-ready-for-review

#2075 Etch simple structs
  libs/vm/include/vm/analyser.hpp
  libs/vm/include/vm/common.hpp
  libs/vm/include/vm/generator.hpp
  libs/vm/include/vm/ir.hpp
  libs/vm/include/vm/ir_builder.hpp
  libs/vm/include/vm/node.hpp
  libs/vm/include/vm/opcodes.hpp
  libs/vm/include/vm/parser.hpp
  libs/vm/include/vm/token.hpp
  libs/vm/include/vm/tokeniser.hpp
  libs/vm/include/vm/user_defined_object.hpp
  libs/vm/include/vm/vm.hpp
  libs/vm/scripts/tokeniser.l
  libs/vm/src/analyser.cpp
  libs/vm/src/generator.cpp
  libs/vm/src/ir.cpp
  libs/vm/src/ir_builder.cpp
  libs/vm/src/parser.cpp
  libs/vm/src/tokeniser.cpp
  libs/vm/src/user_defined_object.cpp
  libs/vm/src/vm.cpp
  libs/vm/src/vm_handlers.cpp
Labels: S-do-not-merge, S-work-in-progress

#2082 Replacing exceptions with logging: Examples, VMOptimiser
  libs/vm-modules/examples/boston_house_prices/main.cpp
  libs/vm-modules/examples/commodity_prediction/main.cpp
  libs/vm-modules/examples/crypto_price_prediction/main.cpp
  libs/vm-modules/examples/mnist/main.cpp
  libs/vm-modules/examples/vm_factory/03_example.cpp
  libs/vm-modules/src/ml/optimisation/optimiser.cpp
  libs/vm-modules/tests/unit/ml.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2074 force removal of python api to guarantee version install
  scripts/install-test-dependencies.sh
Labels: S-ready-for-review

#2086 Do not cache failed contract lookups
  libs/ledger/src/chaincode/chain_code_cache.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2087 Refactor c2c invocation handler; add unexpected type_id check
  libs/vm/src/vm_handlers.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2065 Added throw after allocating SharedArray fails
  libs/vectorise/include/vectorise/memory/shared_array.hpp
Labels: S-ready-for-review

#2090 Disables and fixes some tests that were misbehaving
  libs/dmlf/tests/colearn/update_store_test.cpp
Labels: S-ready-for-review

#2091 Call VM::RuntimeError instead of throwing in ML classes
  libs/math/include/math/tensor.hpp
  libs/vm-modules/include/vm_modules/ml/optimisation/optimiser.hpp
  libs/vm-modules/src/math/tensor.cpp
  libs/vm-modules/src/ml/dataloaders/dataloader.cpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/src/ml/utilities/scaler.cpp
  libs/vm-modules/tests/unit/math.cpp
  libs/vm-modules/tests/unit/ml.cpp
  libs/vm-modules/tests/unit/ml_scaler_tests.cpp
Labels: S-ready-for-review

#2096 implement guard for charge total overflow
  libs/vm-modules/tests/unit/vm_charge_tests.cpp
  libs/vm/src/vm.cpp
Labels: S-ready-for-review

#1904 Development workflow documentation
  CONTRIBUTING.md
  docs/branching-model.md
  docs/cplusplus-style-guide.md
  docs/release-strategy.md
Labels: S-ready-for-review

#2069 Etch compile-time annotation checks
  libs/vm-modules/tests/unit/core_language/annotation_tests.cpp
  libs/vm-modules/tests/unit/core_language/core_etch_tests.cpp
  libs/vm/include/vm/analyser.hpp
  libs/vm/src/analyser.cpp
  libs/vm/src/parser.cpp
Labels: S-do-not-merge, S-work-in-progress

#2108 Bugfix c2c return type_id check
  libs/vm/src/vm_handlers.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2100 Fix for ML-329 Tensor.At() on wrong indices
  libs/math/include/math/tensor.hpp
  libs/vm-modules/tests/unit/math/tensor_tests.cpp
  libs/vm-modules/tests/unit/ml_scaler_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2083 VMTensor benchmarks and VMModel Estimator coeficients tuning
  libs/vm-modules/benchmark/tensor/tensor.cpp
  libs/vm-modules/include/vm_modules/math/tensor/tensor_estimator.hpp
  libs/vm-modules/src/math/tensor/tensor_estimator.cpp
  libs/vm-modules/tests/unit/math/tensor_estimator_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2094 Feature/ml 282 implement fixedpoint string parser
  libs/math/tests/unit/fixed_point/fixed_point.cpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
  libs/vm-modules/tests/unit/core_language/core_etch_tests.cpp
  libs/vm-modules/tests/unit/state_tests.cpp
  libs/vm/include/vm/tokeniser.hpp
  libs/vm/scripts/tokeniser.l
  libs/vm/src/generator.cpp
  libs/vm/src/tokeniser.cpp
Labels: A-maths, C-feature, C-improvement, S-ready-for-review

#2099 Bug/fix api status chain
  libs/ledger/include/ledger/chain/main_chain.hpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/tests/chain/main_chain_tests.cpp
Labels: A-ledger, C-bug, S-ready-for-review, S-ready-to-merge

#2124 Follow-up changes to c259e93
  libs/ledger/include/ledger/chaincode/contract.hpp
  libs/ledger/src/executor.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2119 VMModel::Fit, SerialiseTo coeficients added
  libs/vm-modules/benchmark/model/model.cpp
  libs/vm-modules/include/vm_modules/ml/model/model_estimator.hpp
  libs/vm-modules/src/ml/model/model_estimator.cpp
  libs/vm-modules/tests/unit/ml/model_estimator_tests.cpp
Labels: S-ready-for-review

#2128 Do not cache State existed() value
  libs/vm/src/state.cpp
  scripts/end_to_end_test/end_to_end_test.yaml
  scripts/end_to_end_test/smart_contract_tests/simple_state_test.py
Labels: S-ready-for-review, S-ready-to-merge

#2070 Initial implementation of c2c calls
  libs/ledger/benchmark/executor_bench.cpp
  libs/ledger/include/ledger/chaincode/contract_context.hpp
  libs/ledger/include/ledger/chaincode/smart_contract_factory.hpp
  libs/ledger/include/ledger/transaction_verifier.hpp
  libs/ledger/src/chaincode/contract_context.cpp
  libs/ledger/src/chaincode/contract_http_interface.cpp
  libs/ledger/src/chaincode/smart_contract.cpp
  libs/ledger/src/chaincode/smart_contract_manager.cpp
  libs/ledger/src/executor.cpp
  libs/ledger/src/fees/fee_manager.cpp
  libs/ledger/src/transaction_validator.cpp
  libs/ledger/src/transaction_verifier.cpp
  libs/ledger/src/upow/naive_synergetic_miner.cpp
  libs/ledger/src/upow/synergetic_executor.cpp
  libs/ledger/tests/chaincode/contract_test.hpp
  libs/ledger/tests/unit/transaction_validator_tests.cpp
  libs/vm/include/vm/vm.hpp
  libs/vm/src/vm.cpp
  scripts/end_to_end_test/end_to_end_test.yaml
  scripts/end_to_end_test/smart_contract_tests/c2c_argument_passing_test.py
  scripts/end_to_end_test/smart_contract_tests/c2c_balance.py
  scripts/end_to_end_test/smart_contract_tests/c2c_call_cycle_test.py
  scripts/end_to_end_test/smart_contract_tests/c2c_multiple_calls.py
  scripts/end_to_end_test/smart_contract_tests/c2c_nested_call_depth_limit_test.py
  scripts/end_to_end_test/smart_contract_tests/c2c_nested_call_test.py
  scripts/end_to_end_test/smart_contract_tests/c2c_self_call_test.py
  scripts/end_to_end_test/smart_contract_tests/c2c_single_call_test.py
  scripts/end_to_end_test/smart_contract_tests/c2c_transfer.py
  scripts/end_to_end_test/smart_contract_tests/c2c_with_context_test.py
  scripts/install-test-dependencies.sh
Labels: S-ready-for-review, S-ready-to-merge

#2114 Added metrics to etch VMModel::CompileSequential
  libs/ml/include/ml/model/model.hpp
  libs/ml/include/ml/ops/loss_functions/softmax_cross_entropy_loss.hpp
  libs/vm-modules/examples/boston_house_prices/script/boston.etch
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/include/vm_modules/ml/model/model_estimator.hpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/src/ml/model/model_estimator.cpp
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
  libs/vm-modules/tests/unit/ml/model_estimator_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2116 VMTensor Transpose and Reshape improvements, estimation and estimator tests
  libs/math/include/math/tensor.hpp
  libs/vm-modules/include/vm_modules/math/tensor/tensor.hpp
  libs/vm-modules/src/math/tensor/tensor.cpp
  libs/vm-modules/src/math/tensor/tensor_estimator.cpp
  libs/vm-modules/tests/unit/math/tensor_estimator_tests.cpp
  libs/vm-modules/tests/unit/math/tensor_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2131 tensor dot, argmax, and copy
  libs/vm-modules/include/vm_modules/math/tensor/tensor.hpp
  libs/vm-modules/include/vm_modules/math/tensor/tensor_estimator.hpp
  libs/vm-modules/src/math/tensor/tensor.cpp
  libs/vm-modules/src/math/tensor/tensor_estimator.cpp
  libs/vm-modules/src/ml/graph.cpp
  libs/vm-modules/tests/unit/math/tensor_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2138 Finish removal of vm::Matrix
  libs/vm/include/vm/matrix.hpp
  libs/vm/src/matrix.cpp
  libs/vm/src/module.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2139 Refactor/ml 286 datatype init with strings
  libs/math/include/math/base_types.hpp
  libs/ml/examples/commodity_prediction/main.cpp
  libs/ml/examples/mnist/main.cpp
  libs/ml/examples/word2vec_SGNS_dataloader/main.cpp
  libs/ml/include/ml/clustering/tsne.hpp
  libs/ml/include/ml/ops/activations/elu.hpp
  libs/ml/include/ml/ops/loss_functions/cross_entropy_loss.hpp
  libs/ml/include/ml/ops/metrics/categorical_accuracy.hpp
  libs/ml/tests/unit/clustering/tsne_tests.cpp
  libs/ml/tests/unit/ops/activations/dropout.cpp
  libs/vm-modules/tests/unit/ml/model_estimator_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2121 ml-286 remove leftover doubles/floats from vm code
  libs/vm-modules/include/vm_modules/math/tensor/tensor_estimator.hpp
  libs/vm-modules/include/vm_modules/ml/model/model_estimator.hpp
  libs/vm-modules/src/math/tensor/tensor_estimator.cpp
  libs/vm-modules/src/ml/model/model_estimator.cpp
  libs/vm-modules/tests/unit/math/tensor_estimator_tests.cpp
  libs/vm-modules/tests/unit/ml/model_estimator_tests.cpp
Labels: A-vm, S-ready-for-review, S-ready-to-merge

#2142 Defloating blas
  libs/math/src/math/linalg/blas/gemm_nn_novector.cpp
  libs/math/src/math/linalg/blas/gemm_nn_vector.cpp
  libs/math/src/math/linalg/blas/gemm_nt_novector.cpp
  libs/math/src/math/linalg/blas/gemm_nt_vector.cpp
  libs/math/src/math/linalg/blas/gemm_tn_novector.cpp
  libs/math/src/math/linalg/blas/gemm_tn_vector.cpp
  libs/math/src/math/linalg/blas/gemm_tt_novector.cpp
  libs/math/src/math/linalg/blas/gemm_tt_vector.cpp
  libs/math/src/math/linalg/blas/gemv_n_novector.cpp
  libs/math/src/math/linalg/blas/gemv_n_vector.cpp
  libs/math/src/math/linalg/blas/gemv_t_novector.cpp
  libs/math/src/math/linalg/blas/gemv_t_vector.cpp
Labels: S-ready-to-merge

#2146 Fixing overzealous checks in Model::Predict
  libs/ml/include/ml/model/model.hpp
  libs/ml/tests/unit/model/sequential_test.cpp
Labels: S-ready-to-merge

#2141 Feature/tensor fromstring fixedpoint
  libs/math/include/math/tensor.hpp
  libs/math/tests/unit/activation_functions/softmax.cpp
  libs/math/tests/unit/fixed_point/fixed_point.cpp
  libs/math/tests/unit/linalg/blas/gemm_nn_novector.cpp
  libs/ml/tests/unit/ops/activations/logsoftmax.cpp
  libs/ml/tests/unit/ops/activations/softmax.cpp
  libs/ml/tests/unit/ops/prelu_op.cpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
  libs/vm-modules/tests/unit/math/tensor_tests.cpp
Labels: A-maths, C-bug, C-improvement, S-ready-for-review, S-ready-to-merge

#2145 Benchmarks and coefs for new tensor operators
  libs/vm-modules/benchmark/tensor/tensor.cpp
  libs/vm-modules/include/vm_modules/math/tensor/tensor_estimator.hpp
  libs/vm-modules/src/math/tensor/tensor_estimator.cpp
Labels: S-ready-to-merge

#2144 Refactor/ml 286 datatype init with strings
  libs/ml/examples/bert_simple_cls_example/main.cpp
  libs/ml/tests/unit/graph/graph.cpp
  libs/ml/tests/unit/layers/fully_connected.cpp
  libs/ml/tests/unit/layers/scaled_dot_product_attention.cpp
  libs/ml/tests/unit/layers/self_attention_encoder.cpp
  libs/ml/tests/unit/model/dnn_regressor_test.cpp
  libs/ml/tests/unit/optimisation/optimisers.cpp
  libs/ml/tests/unit/regularisers/main.cpp
  libs/ml/tests/unit/serializers/ml_types.cpp
  libs/vm-modules/src/math/tensor/tensor.cpp
  libs/vm-modules/tests/unit/math/tensor_tests.cpp
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2120 Add ML estimators consistency unit tests [COLE-93]
  libs/vm-modules/src/ml/dataloaders/dataloader.cpp
  libs/vm-modules/src/ml/model/model_estimator.cpp
  libs/vm-modules/tests/unit/ml/ml_estimator_tests.cpp
  libs/vm-modules/tests/unit/ml/model_estimator_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2127 Added FP64 for LFG generator and refactored weight init
  libs/core/include/core/random/lfg.hpp
  libs/ml/include/ml/ops/weights.hpp
  libs/ml/include/ml/optimisation/adam_optimiser.hpp
  libs/ml/include/ml/optimisation/lazy_adam_optimiser.hpp
  libs/ml/tests/unit/model/dnn_classifier_test.cpp
  libs/ml/tests/unit/model/dnn_regressor_test.cpp
  libs/ml/tests/unit/model/sequential_test.cpp
  libs/ml/tests/unit/optimisation/optimisers.cpp
  libs/ml/tests/unit/optimisation/sparse_optimisers.cpp
Labels: A-ml, S-ready-for-review, S-ready-to-merge

#2152 Vm prevent overflows
  libs/vm/include/vm/module/base.hpp
  libs/vm/include/vm/module/free_function_invoke.hpp
  libs/vm/include/vm/module/member_function_invoke.hpp
  libs/vm/include/vm/object.hpp
  libs/vm/include/vm/vm.hpp
  libs/vm/src/object.cpp
  libs/vm/src/vm.cpp
  libs/vm/src/vm_handlers.cpp
Labels: S-ready-to-merge

#2163 Defloat Etch
  libs/dmlf/include/dmlf/execution/basic_vm_engine.hpp
  libs/dmlf/src/basic_vm_engine.cpp
  libs/dmlf/tests/execution/basic_engine_tests.cpp
  libs/ledger/src/chaincode/smart_contract.cpp
  libs/ledger/tests/chaincode/smart_contract_tests.cpp
  libs/math/tests/unit/basic_math/big_number_tests.cpp
  libs/math/tests/unit/fixed_point/fixed_point.cpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
  libs/vectorise/include/vectorise/uint/uint.hpp
  libs/vm-modules/include/vm_modules/math/bignumber.hpp
  libs/vm-modules/src/core/print.cpp
  libs/vm-modules/src/core/structured_data.cpp
  libs/vm-modules/src/core/type_convert.cpp
  libs/vm-modules/src/math/abs.cpp
  libs/vm-modules/src/math/bignumber.cpp
  libs/vm-modules/src/math/exp.cpp
  libs/vm-modules/src/math/log.cpp
  libs/vm-modules/src/math/pow.cpp
  libs/vm-modules/src/math/random.cpp
  libs/vm-modules/src/math/sqrt.cpp
  libs/vm-modules/src/math/trigonometry.cpp
  libs/vm-modules/tests/unit/core_language/core_etch_tests.cpp
  libs/vm-modules/tests/unit/fixed_point.cpp
  libs/vm-modules/tests/unit/math/big_number_wrapper_tests.cpp
  libs/vm-modules/tests/unit/math/math.cpp
  libs/vm-modules/tests/unit/math/tensor_tests.cpp
  libs/vm-modules/tests/unit/parameter_serialization.cpp
  libs/vm-modules/tests/unit/state_tests.cpp
  libs/vm-modules/tests/unit/vm_modules_tests.cpp
  libs/vm/include/vm/analyser.hpp
  libs/vm/include/vm/array.hpp
  libs/vm/include/vm/common.hpp
  libs/vm/include/vm/generator.hpp
  libs/vm/include/vm/map.hpp
  libs/vm/include/vm/object.hpp
  libs/vm/include/vm/token.hpp
  libs/vm/include/vm/tokeniser.hpp
  libs/vm/include/vm/variant.hpp
  libs/vm/include/vm/vm.hpp
  libs/vm/scripts/tokeniser.l
  libs/vm/src/analyser.cpp
  libs/vm/src/generator.cpp
  libs/vm/src/module.cpp
  libs/vm/src/parser.cpp
  libs/vm/src/tokeniser.cpp
  libs/vm/tests/unit/variant.cpp
  scripts/etch-language-tests/maths/abs.etch
  scripts/etch-language-tests/maths/trig.etch
Labels: S-ready-for-review, S-ready-to-merge

#2143 Enable charge estimators for object operators
  libs/vm-modules/include/vm_modules/math/bignumber.hpp
  libs/vm-modules/src/math/bignumber.cpp
  libs/vm-modules/tests/unit/ml/ml_estimator_tests.cpp
  libs/vm-modules/tests/unit/vm_charge_tests.cpp
  libs/vm/include/vm/address.hpp
  libs/vm/include/vm/estimate_charge.hpp
  libs/vm/include/vm/fixed.hpp
  libs/vm/include/vm/object.hpp
  libs/vm/include/vm/string.hpp
  libs/vm/include/vm/vm.hpp
  libs/vm/src/fixed.cpp
  libs/vm/src/object.cpp
  libs/vm/src/string.cpp
  libs/vm/src/vm.cpp
  libs/vm/src/vm_handlers.cpp
Labels: S-ready-to-merge, S-work-in-progress

#2151 Use ordered map in vm::Map
  libs/vm/include/vm/map.hpp
Labels: S-ready-for-review, S-ready-to-merge

#2165 Feature/deprecate wealth2
  apps/constellation/config_builder.cpp
  apps/constellation/settings.cpp
  apps/constellation/settings.hpp
  libs/constellation/include/constellation/constellation.hpp
  libs/ledger/include/ledger/chaincode/token_contract.hpp
  libs/ledger/include/ledger/fees/fee_manager.hpp
  libs/ledger/src/chaincode/token_contract.cpp
  libs/ledger/src/executor.cpp
  libs/ledger/src/fees/fee_manager.cpp
  libs/ledger/src/transaction_validator.cpp
  libs/ledger/src/upow/synergetic_executor.cpp
  libs/ledger/tests/chaincode/token_contract_tests.cpp
  libs/ledger/tests/unit/transaction_validator_tests.cpp
  scripts/end_to_end_test/end_to_end_synergetic_test.yaml
  scripts/end_to_end_test/end_to_end_test.yaml
  scripts/end_to_end_test/end_to_end_test_dmlf.yaml
  scripts/end_to_end_test/end_to_end_test_pos.yaml
  scripts/end_to_end_test/run_end_to_end_test.py
  scripts/end_to_end_test/smart_contract_tests/balance.py
  scripts/end_to_end_test/smart_contract_tests/c2c_argument_passing_test.py
  scripts/end_to_end_test/smart_contract_tests/c2c_balance.py
  scripts/end_to_end_test/smart_contract_tests/c2c_call_cycle_test.py
  scripts/end_to_end_test/smart_contract_tests/c2c_multiple_calls.py
  scripts/end_to_end_test/smart_contract_tests/c2c_nested_call_depth_limit_test.py
  scripts/end_to_end_test/smart_contract_tests/c2c_nested_call_test.py
  scripts/end_to_end_test/smart_contract_tests/c2c_self_call_test.py
  scripts/end_to_end_test/smart_contract_tests/c2c_single_call_test.py
  scripts/end_to_end_test/smart_contract_tests/c2c_transfer.py
  scripts/end_to_end_test/smart_contract_tests/c2c_with_context_test.py
  scripts/end_to_end_test/smart_contract_tests/init_owner_address.py
  scripts/end_to_end_test/smart_contract_tests/ledger_context.py
  scripts/end_to_end_test/smart_contract_tests/malleability_test.py
  scripts/end_to_end_test/smart_contract_tests/simple_state_test.py
  scripts/end_to_end_test/smart_contract_tests/synergetic_mining.py
  scripts/end_to_end_test/smart_contract_tests/transfer.py
  scripts/fetchai_netutils/fetch/testing/testcase.py
  scripts/install-test-dependencies.sh
Labels: S-ready-to-merge

#2158 Feature/ml 344 enable etch tensor operators
  libs/vm-modules/include/vm_modules/math/tensor/tensor.hpp
  libs/vm-modules/include/vm_modules/math/tensor/tensor_estimator.hpp
  libs/vm-modules/src/math/tensor/tensor.cpp
  libs/vm-modules/src/math/tensor/tensor_estimator.cpp
  libs/vm-modules/tests/unit/math/tensor_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2162 Feature/ml 360 vm tensor fromstring can dynamically reshape
  libs/core/include/core/macros.hpp
  libs/math/include/math/tensor.hpp
  libs/math/tests/unit/tensor/constructor.cpp
  libs/ml/include/ml/dataloaders/mnist_loaders/mnist_loader.hpp
  libs/vm-modules/src/math/tensor/tensor.cpp
  libs/vm-modules/tests/unit/math/tensor_tests.cpp
  libs/vm_modules/include/vm_modules/math/tensor.hpp
  libs/vm_modules/src/math/tensor.cpp
  libs/vm_modules/src/ml/dataloaders/dataloader.cpp
Labels: S-ready-to-merge

#2159 ML-332 benchmarks for tensor operators
  libs/vm-modules/benchmark/tensor/tensor.cpp
  libs/vm-modules/include/vm_modules/math/tensor/tensor.hpp
  libs/vm-modules/include/vm_modules/math/tensor/tensor_estimator.hpp
  libs/vm-modules/src/math/tensor/tensor.cpp
  libs/vm-modules/src/math/tensor/tensor_estimator.cpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/tests/unit/math/tensor_estimator_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2161 Feature/ml 359 deepcopy uint256 fixed128
  libs/vm-modules/include/vm_modules/math/bignumber.hpp
  libs/vm-modules/src/math/bignumber.cpp
  libs/vm-modules/tests/unit/fixed_point.cpp
  libs/vm-modules/tests/unit/math/big_number_wrapper_tests.cpp
  libs/vm/include/vm/fixed.hpp
  libs/vm/src/fixed.cpp
  libs/vm/src/module.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2147 plus one ceiling for model and tensor estimators
  libs/vm-modules/include/vm_modules/math/tensor/tensor_estimator.hpp
  libs/vm-modules/include/vm_modules/ml/model/model_estimator.hpp
  libs/vm-modules/src/math/tensor/tensor_estimator.cpp
  libs/vm-modules/src/ml/model/model_estimator.cpp
  libs/vm-modules/tests/unit/math/tensor_estimator_tests.cpp
  libs/vm-modules/tests/unit/ml/model_estimator_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2166 Robustness Improvements for Main Chain Sync
  libs/constellation/include/constellation/constellation.hpp
  libs/constellation/src/constellation.cpp
  libs/ledger/include/ledger/chain/time_travelogue.hpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_client.hpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_client_interface.hpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_protocol.hpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_service.hpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/src/protocols/main_chain_rpc_client.cpp
  libs/ledger/src/protocols/main_chain_rpc_service.cpp
  libs/ledger/tests/chain/fake_muddle_endpoint.cpp
  libs/ledger/tests/chain/fake_muddle_endpoint.hpp
  libs/ledger/tests/chain/main_chain_service_tests.cpp
  libs/ledger/tests/chain/main_chain_tests.cpp
  libs/ledger/tests/chain/mock_consensus.hpp
  libs/ledger/tests/chain/mock_main_chain_rpc_client.hpp
  libs/ledger/tests/chain/mock_muddle_endpoint.hpp
  libs/ledger/tests/chain/mock_trust_system.hpp
  libs/network/include/network/generics/promise_of.hpp
Labels: S-ready-for-review, S-ready-to-merge

#2168 Handle contract lookup failure for queries
  libs/ledger/src/chaincode/contract_http_interface.cpp
  scripts/end_to_end_test/end_to_end_test.yaml
  scripts/end_to_end_test/smart_contract_tests/action_nonexistent_contract.py
  scripts/end_to_end_test/smart_contract_tests/query_nonexistent_contract.py
Labels: S-ready-for-review, S-ready-to-merge

#2149 Removing floats from the math library and tests
  libs/core/include/core/random/lfg.hpp
  libs/math/include/math/activation_functions/gelu.hpp
  libs/math/include/math/base_types.hpp
  libs/math/include/math/correlation/cosine.hpp
  libs/math/include/math/meta/math_type_traits.hpp
  libs/math/include/math/one_hot.hpp
  libs/math/include/math/tensor.hpp
  libs/math/include/math/utilities/ReadCSV.hpp
  libs/math/tests/unit/activation_functions/gelu.cpp
  libs/math/tests/unit/activation_functions/relu.cpp
  libs/math/tests/unit/activation_functions/sigmoid.cpp
  libs/math/tests/unit/activation_functions/softmax.cpp
  libs/math/tests/unit/base_types/base_types.cpp
  libs/math/tests/unit/basic_math/normalize_array_tests.cpp
  libs/math/tests/unit/basic_math/standard_functions_test.cpp
  libs/math/tests/unit/distance/entropy_tests.cpp
  libs/math/tests/unit/distance/perplexity.cpp
  libs/math/tests/unit/fundamental_operators/fundamental_operators.cpp
  libs/math/tests/unit/gtest/one_hot.cpp
  libs/math/tests/unit/matrix_operations/matrix_operations.cpp
  libs/math/tests/unit/metrics/cross_entropy_loss.cpp
  libs/math/tests/unit/metrics/kl_divergence_tests.cpp
  libs/math/tests/unit/metrics/mean_squared_error.cpp
  libs/math/tests/unit/serializers/fixed_point.cpp
  libs/math/tests/unit/tensor/basic_tests.cpp
  libs/math/tests/unit/tensor/constructor.cpp
  libs/math/tests/unit/tensor/tensor_indexing.cpp
  libs/math/tests/unit/trigonometry/trig.cpp
  libs/math/tests/unit/vectors/vector_tests.cpp
  libs/ml/examples/mnist/main.cpp
  libs/vectorise/include/vectorise/fixed_point/type_traits.hpp
  libs/vectorise/include/vectorise/meta/math_type_traits.hpp
Labels: S-ready-to-merge

#2173 Fixing bad merge
  libs/ml/include/ml/dataloaders/mnist_loaders/mnist_loader.hpp
  libs/vm_modules/include/vm_modules/math/tensor.hpp
  libs/vm_modules/src/math/tensor.cpp
  libs/vm_modules/src/ml/dataloaders/dataloader.cpp
Labels: S-ready-to-merge

#2169 Cap transaction charge limit
  libs/chain/include/chain/transaction.hpp
  libs/ledger/include/ledger/execution_result.hpp
  libs/ledger/src/chaincode/contract_http_interface.cpp
  libs/ledger/src/transaction_validator.cpp
  libs/ledger/src/tx_status_http_interface.cpp
  libs/ledger/tests/unit/transaction_validator_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2174 Restore client certificate verification
  libs/http/src/https_client.cpp
Labels: S-ready-to-merge

#2176 Reducing unit tests time
  libs/vm-modules/tests/unit/math/tensor_estimator_tests.cpp
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
  libs/vm-modules/tests/unit/ml/model_estimator_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2157 Add unit test for estimator state consistency [COLE-105]
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/src/ml/model/model_estimator.cpp
  libs/vm-modules/tests/unit/ml/model_estimator_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2130 Add YAML file to the ML Charge benchmark script
  scripts/ml_etch_bench/benchmarks.yaml
  scripts/ml_etch_bench/run_ml_etch_time_charge_bench.py
Labels: S-ready-to-merge

#2160 Feature/ml 355 fixedpoint string parser reject alpha
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
Labels: A-maths, C-improvement, P-high, S-ready-for-review, S-ready-to-merge

#2135 Feature/increased consensus testing
  libs/beacon/include/beacon/block_entropy.hpp
  libs/beacon/src/beacon_setup_service.cpp
  libs/beacon/src/block_entropy.cpp
  libs/beacon/src/trusted_dealer_beacon_service.cpp
  libs/ledger/include/ledger/chain/block.hpp
  libs/ledger/include/ledger/consensus/consensus.hpp
  libs/ledger/src/chain/block.cpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/consensus/consensus.cpp
  libs/ledger/tests/consensus/pos_tests.cpp
Labels: P-high, S-ready-to-merge

#2148 [Genesis] Extending genesis file with option to specify deed(s)
  libs/ledger/src/genesis_file_creator.cpp
Labels: P-high, S-ready-to-merge

#2167 Improved precision of AsFP64 for LFG generator
  libs/core/include/core/random/lfg.hpp
  libs/math/benchmark/trigonometry/trigonometry.cpp
  libs/math/include/math/tensor.hpp
  libs/math/tests/unit/activation_functions/relu.cpp
  libs/math/tests/unit/activation_functions/sigmoid.cpp
  libs/math/tests/unit/basic_math/standard_functions_test.cpp
  libs/math/tests/unit/fundamental_operators/fundamental_operators.cpp
  libs/math/tests/unit/tensor/basic_tests.cpp
  libs/math/tests/unit/test_types.hpp
  libs/ml/include/ml/clustering/tsne.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/sgns_w2v_dataloader.hpp
  libs/ml/include/ml/ops/activations/dropout.hpp
  libs/ml/include/ml/ops/activations/randomised_relu.hpp
  libs/ml/include/ml/ops/weights.hpp
  libs/ml/tests/unit/clustering/tsne_tests.cpp
  libs/ml/tests/unit/layers/fully_connected.cpp
  libs/ml/tests/unit/model/dnn_classifier_test.cpp
  libs/ml/tests/unit/model/dnn_regressor_test.cpp
  libs/ml/tests/unit/model/sequential_test.cpp
  libs/ml/tests/unit/ops/activations/randomised_relu.cpp
  libs/ml/tests/unit/optimisation/optimisers.cpp
  libs/ml/tests/unit/optimisation/sparse_optimisers.cpp
Labels: P-high, S-ready-for-review, S-ready-to-merge

#2170 Fixing network race conditions
  libs/beacon/include/beacon/beacon_complaints_manager.hpp
  libs/beacon/include/beacon/beacon_setup_service.hpp
  libs/beacon/include/beacon/event_manager.hpp
  libs/beacon/src/trusted_dealer_beacon_service.cpp
  libs/constellation/include/constellation/open_api_http_module.hpp
  libs/constellation/src/constellation.cpp
  libs/core/include/core/containers/queue.hpp
  libs/core/include/core/mutex.hpp
  libs/core/src/mutex.cpp
  libs/core/tests/unit/mutex.cpp
  libs/http/include/http/server.hpp
  libs/muddle/benchmark/rbc_bench.cpp
  libs/muddle/include/muddle/tracker_configuration.hpp
  libs/muddle/internal/kademlia/peer_info.hpp
  libs/muddle/internal/kademlia/peer_tracker.hpp
  libs/muddle/internal/kademlia/peer_tracker_protocol.hpp
  libs/muddle/internal/kademlia/table.hpp
  libs/muddle/internal/muddle_register.hpp
  libs/muddle/src/kademlia/peer_tracker.cpp
  libs/muddle/src/kademlia/table.cpp
  libs/muddle/src/muddle_register.cpp
  libs/muddle/src/muddle_status.cpp
  libs/muddle/src/router.cpp
  libs/muddle/tests/integration/network_helpers.hpp
  libs/muddle/tests/integration/peer_table_desired_recovery.cpp
  libs/muddle/tests/integration/peer_table_reboot.cpp
  libs/muddle/tests/integration/rbc_tests.cpp
  libs/muddle/tests/unit/table_recovery.cpp
  libs/network/include/network/details/thread_pool.hpp
  libs/network/include/network/generics/atomic_inflight_counter.hpp
  libs/network/include/network/generics/backgrounded_work.hpp
  libs/network/include/network/service/promise.hpp
  libs/network/include/network/tcp/client_connection.hpp
  libs/network/src/tcp/client_implementation.cpp
  libs/oef-base/include/oef-base/threading/Future.hpp
  libs/oef-base/include/oef-base/threading/FutureCombiner.hpp
  libs/oef-base/include/oef-base/threading/TaskChainParallel.hpp
  libs/oef-search/include/oef-search/dap_comms/DapParallelConversationTask.hpp
  libs/oef-search/include/oef-search/dap_manager/DapManager.hpp
  libs/oef-search/include/oef-search/dap_manager/DapStore.hpp
  libs/oef-search/src/dap_manager/visitors/PopulateActionsVisitorDescentPass.cpp
Labels: P-high, S-ready-for-review, S-ready-to-merge

#2180 Etch defensive checks
  libs/vm/include/vm/analyser.hpp
  libs/vm/include/vm/node.hpp
  libs/vm/include/vm/token.hpp
  libs/vm/include/vm/tokeniser.hpp
  libs/vm/scripts/tokeniser.l
  libs/vm/src/analyser.cpp
  libs/vm/src/parser.cpp
  libs/vm/src/tokeniser.cpp
Labels: P-high, S-ready-to-merge

#2140 Dropping unnecessary legacy `address` field from deed structure
  libs/ledger/include/ledger/chaincode/deed.hpp
  libs/ledger/include/ledger/chaincode/token_contract.hpp
  libs/ledger/include/ledger/chaincode/wallet_record.hpp
  libs/ledger/src/chaincode/deed.cpp
  libs/ledger/src/chaincode/token_contract.cpp
  libs/ledger/src/chaincode/wallet_record.cpp
  libs/ledger/tests/chaincode/token_contract_deed_tests.cpp
  libs/ledger/tests/chaincode/token_contract_tests.cpp
Labels: P-high, S-ready-to-merge

#2175 remove unneccessary address in block
  libs/ledger/include/ledger/chain/block.hpp
  libs/ledger/include/ledger/consensus/consensus.hpp
  libs/ledger/src/chain/block.cpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/src/consensus/consensus.cpp
  libs/ledger/src/execution_manager.cpp
  libs/ledger/src/genesis_file_creator.cpp
  libs/ledger/src/testing/block_generator.cpp
  libs/ledger/src/upow/synergetic_execution_manager.cpp
  libs/ledger/tests/chain/main_chain_tests.cpp
  libs/network/include/network/p2pservice/p2p_http_interface.hpp
Labels: P-high, S-ready-to-merge

#2181 ml-293 coeficients tuning for AddDense
  libs/vm-modules/include/vm_modules/ml/model/model_estimator.hpp
  libs/vm-modules/src/math/tensor/tensor_estimator.cpp
  libs/vm-modules/src/ml/model/model_estimator.cpp
  libs/vm-modules/tests/unit/ml/model_estimator_tests.cpp
Labels: A-vm, P-high, S-ready-for-review, S-ready-to-merge

#2183 Thread sanity
  libs/beacon/include/beacon/beacon_complaints_manager.hpp
  libs/beacon/include/beacon/beacon_setup_service.hpp
  libs/beacon/include/beacon/event_manager.hpp
  libs/beacon/src/trusted_dealer_beacon_service.cpp
  libs/constellation/include/constellation/open_api_http_module.hpp
  libs/constellation/src/constellation.cpp
  libs/core/include/core/containers/queue.hpp
  libs/core/include/core/mutex.hpp
  libs/core/src/mutex.cpp
  libs/core/tests/unit/mutex.cpp
  libs/http/include/http/server.hpp
  libs/muddle/benchmark/rbc_bench.cpp
  libs/muddle/include/muddle/packet.hpp
  libs/muddle/include/muddle/tracker_configuration.hpp
  libs/muddle/internal/kademlia/peer_info.hpp
  libs/muddle/internal/kademlia/peer_tracker.hpp
  libs/muddle/internal/kademlia/peer_tracker_protocol.hpp
  libs/muddle/internal/kademlia/table.hpp
  libs/muddle/internal/muddle_register.hpp
  libs/muddle/src/kademlia/peer_tracker.cpp
  libs/muddle/src/kademlia/table.cpp
  libs/muddle/src/muddle_register.cpp
  libs/muddle/src/muddle_status.cpp
  libs/muddle/src/router.cpp
  libs/muddle/tests/integration/network_helpers.hpp
  libs/muddle/tests/integration/peer_table_desired_recovery.cpp
  libs/muddle/tests/integration/peer_table_reboot.cpp
  libs/muddle/tests/integration/rbc_tests.cpp
  libs/muddle/tests/unit/table_recovery.cpp
  libs/network/include/network/details/thread_pool.hpp
  libs/network/include/network/generics/atomic_inflight_counter.hpp
  libs/network/include/network/generics/backgrounded_work.hpp
  libs/network/include/network/service/promise.hpp
  libs/network/include/network/tcp/client_connection.hpp
  libs/network/src/tcp/client_implementation.cpp
  libs/oef-base/include/oef-base/threading/Future.hpp
  libs/oef-base/include/oef-base/threading/FutureCombiner.hpp
  libs/oef-base/include/oef-base/threading/TaskChainParallel.hpp
  libs/oef-search/include/oef-search/dap_comms/DapParallelConversationTask.hpp
  libs/oef-search/include/oef-search/dap_manager/DapManager.hpp
  libs/oef-search/include/oef-search/dap_manager/DapStore.hpp
  libs/oef-search/src/dap_manager/visitors/PopulateActionsVisitorDescentPass.cpp
Labels: P-high, S-ready-to-merge

#2185 Correct mutex selection
  libs/core/include/core/mutex.hpp
  libs/core/src/mutex.cpp
  libs/core/tests/unit/mutex.cpp
Labels: P-high, S-ready-to-merge

#2182 Bugfix/startup walk back
  libs/constellation/src/constellation.cpp
  libs/ledger/include/ledger/consensus/consensus.hpp
  libs/ledger/include/ledger/consensus/consensus_interface.hpp
  libs/ledger/include/ledger/consensus/simulated_pow_consensus.hpp
  libs/ledger/include/ledger/consensus/stake_manager.hpp
  libs/ledger/include/ledger/consensus/stake_snapshot.hpp
  libs/ledger/include/ledger/genesis_loading/genesis_file_creator.hpp
  libs/ledger/src/consensus/consensus.cpp
  libs/ledger/src/consensus/simulated_pow_consensus.cpp
  libs/ledger/src/consensus/stake_manager.cpp
  libs/ledger/src/consensus/stake_snapshot.cpp
  libs/ledger/src/genesis_file_creator.cpp
  libs/ledger/tests/chain/mock_consensus.hpp
Labels: P-high, S-ready-to-merge

#2186 strip hex output from fixedpoint string
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
Labels: A-maths, C-bug, S-ready-to-merge

#2189 Etch more defensive checks
  libs/vm-modules/tests/unit/core_language/annotation_tests.cpp
  libs/vm-modules/tests/unit/core_language/core_etch_tests.cpp
  libs/vm/include/vm/analyser.hpp
  libs/vm/include/vm/generator.hpp
  libs/vm/src/analyser.cpp
  libs/vm/src/generator.cpp
  libs/vm/src/parser.cpp
Labels: P-high, S-ready-to-merge

#2192 Segfault on shutdown + more
  libs/muddle/internal/kademlia/peer_tracker.hpp
  libs/muddle/src/kademlia/peer_tracker.cpp
  libs/muddle/tests/integration/population_test.cpp
  libs/network/src/details/network_manager_implementation.cpp
Labels: P-high, S-ready-for-review, S-ready-to-merge

#2193 Correct Validation on blocks with missing confirmations
  libs/ledger/src/consensus/consensus.cpp
  libs/ledger/src/protocols/main_chain_rpc_service.cpp
Labels: P-high

#2172 Feature/ml 289 flatten temp
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/include/vm_modules/ml/model/model_estimator.hpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/src/ml/model/model_estimator.cpp
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2150 Removing floats from the ML library and tests
  libs/ml/benchmark/training/training.cpp
  libs/ml/examples/commodity_prediction/main.cpp
  libs/ml/examples/crypto_price_prediction/main.cpp
  libs/ml/examples/word2vec_SGNS_dataloader/main.cpp
  libs/ml/examples/word2vec_graph_evaluation/main.cpp
  libs/ml/include/ml/clustering/tsne.hpp
  libs/ml/include/ml/core/graph.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/sgns_w2v_dataloader.hpp
  libs/ml/include/ml/layers/scaled_dot_product_attention.hpp
  libs/ml/include/ml/ops/activations/elu.hpp
  libs/ml/include/ml/ops/activations/logsigmoid.hpp
  libs/ml/include/ml/ops/activations/sigmoid.hpp
  libs/ml/include/ml/ops/loss_functions/cross_entropy_loss.hpp
  libs/ml/include/ml/ops/metrics/categorical_accuracy.hpp
  libs/ml/include/ml/ops/one_hot.hpp
  libs/ml/include/ml/ops/tanh.hpp
  libs/ml/include/ml/ops/trainable.hpp
  libs/ml/include/ml/optimisation/adagrad_optimiser.hpp
  libs/ml/include/ml/optimisation/momentum_optimiser.hpp
  libs/ml/include/ml/optimisation/rmsprop_optimiser.hpp
  libs/ml/include/ml/state_dict.hpp
  libs/ml/tests/unit/layers/PRelu.cpp
  libs/ml/tests/unit/layers/convolution_1d.cpp
  libs/ml/tests/unit/layers/convolution_2d.cpp
  libs/ml/tests/unit/layers/fully_connected.cpp
  libs/ml/tests/unit/layers/layer_norm.cpp
  libs/ml/tests/unit/layers/scaled_dot_product_attention.cpp
  libs/ml/tests/unit/layers/skip_gram.cpp
  libs/ml/tests/unit/model/dnn_classifier_test.cpp
  libs/ml/tests/unit/model/dnn_regressor_test.cpp
  libs/ml/tests/unit/model/sequential_test.cpp
  libs/ml/tests/unit/ops/activations/dropout.cpp
  libs/ml/tests/unit/ops/activations/gelu.cpp
  libs/ml/tests/unit/ops/activations/randomised_relu.cpp
  libs/ml/tests/unit/optimisation/optimisers.cpp
  libs/ml/tests/unit/optimisation/sparse_optimisers.cpp
  libs/ml/tests/unit/serializers/ml_types.cpp
Labels: S-ready-to-merge

#2010 Endianess handling of UInt<T> <-> ByteArray conversion
  libs/core/include/core/byte_array/const_byte_array.hpp
  libs/core/src/byte_array/decoders.cpp
  libs/core/tests/unit/byte_array/encode_decode_tests.cpp
  libs/json/src/document.cpp
  libs/ledger/src/upow/work.cpp
  libs/math/tests/unit/basic_math/big_number_tests.cpp
  libs/variant/include/variant/variant.hpp
  libs/vectorise/include/vectorise/platform.hpp
  libs/vectorise/include/vectorise/uint/uint.hpp
  libs/vm-modules/include/vm_modules/core/byte_array_wrapper.hpp
  libs/vm-modules/include/vm_modules/crypto/sha256.hpp
  libs/vm-modules/include/vm_modules/math/bignumber.hpp
  libs/vm-modules/src/core/byte_array_wrapper.cpp
  libs/vm-modules/src/core/structured_data.cpp
  libs/vm-modules/src/crypto/sha256.cpp
  libs/vm-modules/src/ledger/transaction.cpp
  libs/vm-modules/src/math/bignumber.cpp
  libs/vm-modules/tests/unit/math/big_number_wrapper_tests.cpp
  libs/vm-modules/tests/unit/state_tests.cpp
  libs/vm/include/vm/array.hpp
  libs/vm/include/vm/map.hpp
  libs/vm/include/vm/module.hpp
  libs/vm/include/vm/module/base.hpp
  libs/vm/include/vm/object.hpp
  libs/vm/include/vm/variant.hpp
  libs/vm/include/vm/vm.hpp
  libs/vm/src/state.cpp
  scripts/etch-language-tests/uint256.etch
Labels: C-bug, C-improvement, C-proposal, S-ready-for-review

#2200 Fixing race condition occurring if networking manager outlives muddle.
  libs/muddle/include/muddle/tracker_configuration.hpp
  libs/muddle/src/muddle.cpp
  libs/muddle/tests/integration/population_test.cpp
  libs/network/src/details/network_manager_implementation.cpp
Labels: P-high, S-ready-for-review

#2197 Test/ml 353 misuse of etch ml model
  libs/vm-modules/src/math/tensor/tensor.cpp
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2188 ToString added for Slice and View
  libs/math/include/math/tensor.hpp
  libs/math/include/math/tensor_view.hpp
  libs/ml/include/ml/utilities/bert_utilities.hpp
  libs/ml/tests/unit/ops/layer_norm.cpp
Labels: P-low

#2223 fix post inc/dec operators
  libs/math/tests/unit/fixed_point/fixed_point.cpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
Labels: A-maths, C-bug, P-high, S-ready-to-merge

#2198 Dropout layer binding for VMModel
  libs/ml/include/ml/ops/activations/dropout.hpp
  libs/ml/include/ml/optimisation/optimiser.hpp
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/include/vm_modules/ml/model/model_estimator.hpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/src/ml/model/model_estimator.cpp
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2226 Adding gauge telemetry to all state machines
  libs/core/include/core/periodic_functor.hpp
  libs/core/include/core/periodic_runnable.hpp
  libs/core/include/core/state_machine.hpp
  libs/core/src/periodic_functor.cpp
  libs/core/src/periodic_runnable.cpp
  libs/muddle/src/kademlia/peer_tracker.cpp
  libs/muddle/src/muddle.cpp
  libs/shards/src/shard_management_service.cpp
Labels: S-ready-for-review

#2203 ML-211 Remove commodity dataloader
  libs/math/include/math/utilities/ReadCSV.hpp
  libs/ml/examples/commodity_prediction/main.cpp
  libs/ml/include/ml/dataloaders/commodity_dataloader.hpp
  libs/ml/include/ml/dataloaders/dataloader.hpp
  libs/vm-modules/examples/commodity_prediction/main.cpp
  libs/vm-modules/examples/commodity_prediction/script/commodity_prediction.etch
  libs/vm-modules/examples/commodity_prediction/script/graph_saver.etch
  libs/vm-modules/include/vm_modules/ml/dataloaders/dataloader.hpp
  libs/vm-modules/src/ml/dataloaders/dataloader.cpp
Labels: S-ready-to-merge

#2184 ML-306 Added test for changing batch size on etch model
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
Labels: S-ready-to-merge

#2218 add rand() support for fixedpoint types, with tests
  libs/vectorise/include/vectorise/fixed_point/type_traits.hpp
  libs/vm-modules/examples/fixedpoint/fixed_point.etch
  libs/vm-modules/src/math/random.cpp
  libs/vm-modules/tests/unit/math/math.cpp
Labels: A-maths, C-improvement, S-ready-for-review, S-ready-to-merge

#2217 add missing shift and associative operators
  libs/math/tests/unit/fixed_point/fixed_point.cpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
Labels: A-maths, C-improvement, S-ready-for-review, S-ready-to-merge

#2231 UInt256 "<= >=" tests added
  libs/vm-modules/tests/unit/math/big_number_wrapper_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2229 ML-337 Allow passing of options to python script in end-to-end tests
  scripts/end_to_end_test/run_end_to_end_test.py
Labels: S-ready-to-merge

#2202 Refactor: more defloating of fixedpoint initialisations
  libs/dmlf/include/dmlf/collective_learning/word2vec_training_params.hpp
  libs/ml/examples/bert_simple_cls_example/main.cpp
  libs/ml/examples/tsne/main.cpp
  libs/ml/tests/unit/layers/scaled_dot_product_attention.cpp
  libs/ml/tests/unit/model/dnn_classifier_test.cpp
  libs/ml/tests/unit/model/dnn_regressor_test.cpp
  libs/ml/tests/unit/model/sequential_test.cpp
  libs/ml/tests/unit/ops/activations/dropout.cpp
  libs/vm-modules/tests/unit/math/tensor_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2222 ML-383 VMTrainingPair removed and VMPair implemented
  libs/core/include/core/serializers/counter.hpp
  libs/core/include/core/serializers/group_definitions.hpp
  libs/core/include/core/serializers/main_serializer.hpp
  libs/core/include/core/serializers/main_serializer_definition.hpp
  libs/core/include/core/serializers/pair_interface.hpp
  libs/core/src/serializers/main_serializer.cpp
  libs/vm-modules/include/vm_modules/ml/dataloaders/dataloader.hpp
  libs/vm-modules/include/vm_modules/ml/training_pair.hpp
  libs/vm-modules/src/math/tensor/tensor.cpp
  libs/vm-modules/src/ml/dataloaders/dataloader.cpp
  libs/vm-modules/src/ml/ml.cpp
  libs/vm-modules/src/ml/optimisation/optimiser.cpp
  libs/vm-modules/src/ml/training_pair.cpp
  libs/vm-modules/tests/unit/ml/ml.cpp
  libs/vm-modules/tests/unit/ml/ml_estimator_tests.cpp
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
  libs/vm-modules/tests/unit/ops_tests.cpp
  libs/vm-modules/tests/unit/pair_tests.cpp
  libs/vm-modules/tests/unit/state_tests.cpp
  libs/vm/include/vm/analyser.hpp
  libs/vm/include/vm/map.hpp
  libs/vm/include/vm/pair.hpp
  libs/vm/src/analyser.cpp
  libs/vm/src/module.cpp
  libs/vm/src/parser.cpp
Labels: A-ml, A-vm, S-ready-for-review, S-ready-to-merge

#2228 Activation layer binding for VMModel
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/include/vm_modules/ml/model/model_estimator.hpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/src/ml/model/model_estimator.cpp
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2232 fix printing of small negative fractions (integer part == 0)
  libs/math/tests/unit/fixed_point/fixed_point.cpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
Labels: A-maths, C-bug, P-high, S-ready-for-review, S-ready-to-merge

#2195 Removed VMStateDict
  libs/vm-modules/include/vm_modules/ml/graph.hpp
  libs/vm-modules/include/vm_modules/ml/state_dict.hpp
  libs/vm-modules/src/ml/graph.cpp
  libs/vm-modules/src/ml/ml.cpp
  libs/vm-modules/src/ml/state_dict.cpp
  libs/vm-modules/tests/unit/ml/ml_estimator_tests.cpp
Labels: A-ml, A-vm, S-ready-for-review, S-ready-to-merge

#2243 ML-390: fixed values in conv tests
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2066 Feature/uint256 additional tests
  libs/vm-modules/tests/unit/math/big_number_wrapper_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2242 added benchmarks for activations backward operation
  libs/ml/benchmark/activations/activations.cpp
Labels: S-ready-for-review

#2237 Activation layer experimental estimators and tests
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2244 test/ML-377-enable-tests
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
Labels: S-ready-to-merge

#2246 Bugfix/ml 402 fix tensor reshape
  libs/math/tests/unit/tensor/tensor_operations.cpp
  libs/ml/include/ml/ops/reshape.hpp
  libs/ml/include/ml/saveparams/saveable_params.hpp
  libs/ml/include/ml/serializers/ml_types.hpp
  libs/ml/tests/unit/ops/reshape.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2252 Entries 'libs/libname/src/libname/' eliminated.
  libs/math/src/linalg/blas/gemm_nn_novector.cpp
  libs/math/src/linalg/blas/gemm_nn_vector.cpp
  libs/math/src/linalg/blas/gemm_nt_novector.cpp
  libs/math/src/linalg/blas/gemm_nt_vector.cpp
  libs/math/src/linalg/blas/gemm_tn_novector.cpp
  libs/math/src/linalg/blas/gemm_tn_vector.cpp
  libs/math/src/linalg/blas/gemm_tt_novector.cpp
  libs/math/src/linalg/blas/gemm_tt_vector.cpp
  libs/math/src/linalg/blas/gemv_n_novector.cpp
  libs/math/src/linalg/blas/gemv_n_vector.cpp
  libs/math/src/linalg/blas/gemv_t_novector.cpp
  libs/math/src/linalg/blas/gemv_t_vector.cpp
  libs/math/src/linalg/blas/scal_all.cpp
  libs/math/src/linalg/blas/swap_all.cpp
  libs/messenger/src/mailbox.cpp
  libs/messenger/src/messenger_api.cpp
  libs/messenger/src/messenger_protocol.cpp
  libs/messenger/src/messenger_prototype.cpp
  libs/semanticsearch/src/advertisement_register.cpp
  libs/semanticsearch/src/agent_directory.cpp
  libs/semanticsearch/src/index/in_memory_db_index.cpp
  libs/semanticsearch/src/index/subscription_group.cpp
  libs/semanticsearch/src/module/builtin_query_function.cpp
  libs/semanticsearch/src/module/model_interface_builder.cpp
  libs/semanticsearch/src/query/error_tracker.cpp
  libs/semanticsearch/src/query/query_compiler.cpp
  libs/semanticsearch/src/query/query_executor.cpp
  libs/semanticsearch/src/query/variant.cpp
  libs/semanticsearch/src/schema/model_register.cpp
  libs/semanticsearch/src/schema/semantic_reducer.cpp
  libs/semanticsearch/src/schema/vocabulary_instance.cpp
  libs/yaml/src/document.cpp
Labels: C-improvement, S-ready-for-review

#2248 CI Fixes for Release 1.0.x
  libs/ledger/include/ledger/chain/main_chain.hpp
  libs/ledger/include/ledger/consensus/consensus.hpp
  libs/ledger/src/consensus/consensus.cpp
  libs/ledger/src/genesis_file_creator.cpp
  libs/ledger/tests/chaincode/token_contract_tests.cpp
  libs/ledger/tests/consensus/pos_tests.cpp
  libs/shards/src/service_identifier.cpp
  scripts/end_to_end_test/run_end_to_end_test.py
  scripts/fetchai_netutils/fetch/cluster/instance.py
  scripts/fetchai_netutils/fetch/testing/testcase.py
  scripts/generate-genesis-file.py
Labels: S-ready-for-review
