Repository fetchai/ledger, pull requests merged in 2019-08, with the labels that each got.

#1438 Reduce for multiple dimensions at once
  libs/math/include/math/activation_functions/softmax.hpp
  libs/math/include/math/matrix_operations.hpp
  libs/math/include/math/tensor_reduce.hpp
  libs/math/tests/math/all_tests/matrix_operations/matrix_operations.cpp
  libs/ml/include/ml/ops/activations/softmax.hpp
  libs/ml/include/ml/ops/add.hpp
  libs/ml/tests/ml/ops/activations/softmax.cpp
  libs/ml/tests/ml/ops/add.cpp
Labels: A-maths, A-ml, S-ready-for-review

#1404 [VM] Enhance type deduction for bindings
  libs/ledger/src/upow/synergetic_contract.cpp
  libs/vm/include/vm/address.hpp
  libs/vm/include/vm/module.hpp
  libs/vm/include/vm/module/base.hpp
  libs/vm/include/vm/module/constructor_invoke.hpp
  libs/vm/include/vm/sharded_state.hpp
  libs/vm/include/vm/state.hpp
  libs/vm/src/module.cpp
  libs/vm/src/sharded_state.cpp
  libs/vm/src/state.cpp
  libs/vm/src/string.cpp
  libs/vm_modules/include/vm_modules/core/structured_data.hpp
  libs/vm_modules/include/vm_modules/math/bignumber.hpp
  libs/vm_modules/include/vm_modules/math/tensor.hpp
  libs/vm_modules/include/vm_modules/ml/training_pair.hpp
  libs/vm_modules/include/vm_modules/vm_factory.hpp
  libs/vm_modules/src/core/byte_array_wrapper.cpp
  libs/vm_modules/src/core/structured_data.cpp
  libs/vm_modules/src/crypto/sha256.cpp
  libs/vm_modules/src/math/abs.cpp
  libs/vm_modules/src/math/bignumber.cpp
  libs/vm_modules/src/math/exp.cpp
  libs/vm_modules/src/math/log.cpp
  libs/vm_modules/src/math/pow.cpp
  libs/vm_modules/src/math/random.cpp
  libs/vm_modules/src/math/sqrt.cpp
  libs/vm_modules/src/math/tensor.cpp
  libs/vm_modules/src/math/trigonometry.cpp
  libs/vm_modules/src/ml/dataloaders/dataloader.cpp
  libs/vm_modules/src/ml/graph.cpp
  libs/vm_modules/src/ml/optimisation/optimiser.cpp
  libs/vm_modules/src/ml/state_dict.cpp
  libs/vm_modules/src/ml/training_pair.cpp
  libs/vm_modules/src/ml/utilities/scaler.cpp
Labels: S-ready-for-review

#1447 Disable muddle stress tests due to timeouts
  libs/network/tests/muddle/muddle_stress_tests.cpp
Labels: S-ready-for-review

#1437 Scaled Dot Product Attention Layer
  libs/ml/include/ml/layers/fully_connected.hpp
  libs/ml/include/ml/layers/layers.hpp
  libs/ml/include/ml/layers/scaled_dot_product_attention.hpp
  libs/ml/include/ml/layers/self_attention.hpp
  libs/ml/tests/ml/layers/scaled_dot_product_attention.cpp
  libs/ml/tests/ml/layers/self_attention.cpp
  libs/ml/tests/ml/ops/graph.cpp
  libs/ml/tests/ml/optimisation/optimisers.cpp
Labels: S-ready-for-review

#1441 Timedistributed fc
  libs/ml/include/ml/layers/fully_connected.hpp
  libs/ml/tests/ml/layers/fully_connected.cpp
Labels: S-ready-for-review

#1446 Multihead attention
  libs/ml/include/ml/layers/multihead_attention.hpp
  libs/ml/include/ml/ops/concatenate.hpp
  libs/ml/include/ml/subgraph.hpp
  libs/ml/tests/ml/layers/multihead_attention.cpp
  libs/ml/tests/ml/ops/concatenate.cpp
Labels: S-ready-for-review

#1454 Switch operation
  libs/math/include/math/matrix_operations.hpp
  libs/math/tests/math/all_tests/matrix_operations/matrix_operations.cpp
  libs/ml/include/ml/ops/switch.hpp
  libs/ml/tests/ml/ops/switch.cpp
Labels: A-maths, A-ml

#1485 Committee renewal
  apps/CMakeLists.txt
  apps/beacon/CMakeLists.txt
  apps/beacon/main.cpp
  libs/beacon/CMakeLists.txt
  libs/beacon/examples/beacon_manager/main.cpp
  libs/beacon/include/beacon/aeon.hpp
  libs/beacon/include/beacon/beacon_manager.hpp
  libs/beacon/include/beacon/beacon_protocol.hpp
  libs/beacon/include/beacon/beacon_service.hpp
  libs/beacon/include/beacon/beacon_setup_protocol.hpp
  libs/beacon/include/beacon/beacon_setup_service.hpp
  libs/beacon/include/beacon/cabinet_member_details.hpp
  libs/beacon/include/beacon/entropy.hpp
  libs/beacon/include/beacon/event_manager.hpp
  libs/beacon/include/beacon/events.hpp
  libs/beacon/include/beacon/verification_vector_message.hpp
  libs/beacon/src/beacon_manager.cpp
  libs/beacon/src/beacon_protocol.cpp
  libs/beacon/src/beacon_service.cpp
  libs/beacon/src/beacon_setup_protocol.cpp
  libs/beacon/src/beacon_setup_service.cpp
  libs/core/include/core/serializers/binary_interface.hpp
  libs/core/include/core/service_ids.hpp
  libs/dkg/examples/dkg/main.cpp
  libs/network/src/tcp/tcp_server.cpp
Labels: S-ready-for-review

#1431 Feature/pos end to end
  .gitignore
  apps/constellation/constellation.cpp
  apps/constellation/health_check_http_module.hpp
  libs/dkg/examples/dkg/main.cpp
  libs/dkg/include/dkg/dkg_service.hpp
  libs/dkg/src/dkg_service.cpp
  libs/ledger/include/ledger/chain/block.hpp
  libs/ledger/include/ledger/consensus/stake_manager.hpp
  libs/ledger/src/chain/block.cpp
  libs/ledger/src/consensus/stake_manager.cpp
  scripts/ci/install-test-dependencies.sh
  scripts/end_to_end_test/end_to_end_test_pos.yaml
  scripts/end_to_end_test/input_files/create-input-files.py
  scripts/end_to_end_test/run_end_to_end_test.py
  scripts/generate-initial-state.py
Labels: S-work-in-progress

#1415 tensor dataloader serialisation
  libs/ml/include/ml/dataloaders/dataloader.hpp
  libs/ml/include/ml/dataloaders/tensor_dataloader.hpp
  libs/ml/tests/ml/dataloader/tensor_dataloader.cpp
  libs/vectorise/include/vectorise/fixed_point/serializers.hpp
Labels: S-ready-for-review

#1494 Refactor messages in RBC
  libs/dkg/include/dkg/dkg.hpp
  libs/dkg/include/dkg/dkg_messages.hpp
  libs/dkg/include/dkg/rbc.hpp
  libs/dkg/include/dkg/rbc_messages.hpp
  libs/dkg/src/dkg.cpp
  libs/dkg/src/rbc.cpp
  libs/dkg/src/rbc_envelope.cpp
  libs/dkg/tests/gtests/dkg_messages.cpp
  libs/dkg/tests/gtests/dkg_tests.cpp
  libs/dkg/tests/gtests/rbc_messages.cpp
  libs/dkg/tests/gtests/rbc_tests.cpp
  libs/network/include/network/muddle/rbc/reliable_broadcast.hpp
  libs/network/include/network/muddle/rbc/reliable_broadcast_protocol.hpp
Labels: S-ready-for-review

#1499 Deprecation of RBCEnvelope and fixing attack vector
  libs/dkg/include/dkg/rbc.hpp
  libs/dkg/include/dkg/rbc_envelope.hpp
  libs/dkg/include/dkg/rbc_messages.hpp
  libs/dkg/src/rbc.cpp
  libs/dkg/src/rbc_envelope.cpp
  libs/dkg/tests/gtests/rbc_messages.cpp
  libs/dkg/tests/gtests/rbc_tests.cpp
Labels: S-ready-for-review

#1511 Enforce W2V Dataloader comment with static assert
  libs/ml/include/ml/dataloaders/word2vec_loaders/w2v_dataloader.hpp
Labels: S-ready-for-review

#1509 Remove unnecessary file
  libs/core/tests/json/gtest/json_long_strings.hpp
  libs/core/tests/json/gtest/json_tests.cpp
Labels: S-ready-for-review

#1519 Remove redundant inline keywords
  libs/math/include/math/comparison.hpp
  libs/math/include/math/correlation/jaccard.hpp
  libs/math/include/math/correlation/pearson.hpp
  libs/math/include/math/distance/absolute.hpp
  libs/math/include/math/distance/braycurtis.hpp
  libs/math/include/math/distance/chebyshev.hpp
  libs/math/include/math/distance/cosine.hpp
  libs/math/include/math/distance/hamming.hpp
  libs/math/include/math/distance/jaccard.hpp
  libs/math/include/math/distance/manhattan.hpp
  libs/math/include/math/distance/minkowski.hpp
  libs/math/include/math/distance/pairwise_distance.hpp
  libs/math/include/math/distance/pearson.hpp
  libs/math/include/math/distance/square.hpp
  libs/math/include/math/matrix_operations.hpp
  libs/math/include/math/statistics/geometric_mean.hpp
  libs/math/include/math/statistics/normal.hpp
  libs/math/include/math/statistics/standard_deviation.hpp
  libs/math/include/math/statistics/variance.hpp
  libs/math/include/math/tensor_broadcast.hpp
  libs/math/include/math/tensor_reduce.hpp
  libs/moment/include/moment/deadline_timer.hpp
  libs/network/include/network/generics/promise_of.hpp
  libs/storage/include/storage/transient_object_store.hpp
  libs/variant/include/variant/detail/element_pool.hpp
  libs/vectorise/include/vectorise/platform.hpp
  libs/vm/include/vm/array.hpp
  libs/vm/include/vm/map.hpp
  libs/vm/include/vm/object.hpp
Labels: S-ready-for-review

#1521 Remove obsolete scripts
  scripts/add_header.py
  scripts/bindings/py_bindings.tpp
  scripts/bindings/write_bindings.py
  scripts/crypto/sha256.py
  scripts/jsonparser/convert.py
  scripts/replicate_include_directories.py
  scripts/string/encode_base64.py
  scripts/string/encode_hex.py
Labels: S-ready-for-review

#1517 Fix bug in Identifier (inconsistent state)
  libs/ledger/include/ledger/identifier.hpp
  libs/ledger/src/executor.cpp
  libs/ledger/src/identifier.cpp
Labels: S-ready-for-review

#1510 Swap TrimRight and TrimLeft; amend tests
  libs/core/src/string/trim.cpp
  libs/core/tests/unit/string_tests.cpp
Labels: S-ready-for-review

#1536 etch binding for tensor setting and getting for up to 4 dimensions
  libs/vm_modules/include/vm_modules/math/tensor.hpp
  libs/vm_modules/src/math/tensor.cpp
  libs/vm_modules/tests/unit/math.cpp
Labels: A-vm, S-ready-for-review

#1540 Exclude 3rd-party tests from build
  cmake/BuildTargets.cmake
Labels: S-ready-for-review

#1452 Train/test splitting for dataloaders
  libs/core/include/core/serializers/main_serializer.hpp
  libs/ml/examples/asynchronous_distributed_learning/main.cpp
  libs/ml/examples/centralised_distributed_learning/main.cpp
  libs/ml/examples/crypto_price_prediction/main.cpp
  libs/ml/examples/decentralised_distributed_learning/main.cpp
  libs/ml/examples/mnist_estimator/main.cpp
  libs/ml/examples/word2vec_SGNS_dataloader/main.cpp
  libs/ml/examples/word2vec_simple/main.cpp
  libs/ml/include/ml/dataloaders/code2vec_context_loaders/context_loader.hpp
  libs/ml/include/ml/dataloaders/commodity_dataloader.hpp
  libs/ml/include/ml/dataloaders/dataloader.hpp
  libs/ml/include/ml/dataloaders/mnist_loaders/mnist_loader.hpp
  libs/ml/include/ml/dataloaders/tensor_dataloader.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/sgns_w2v_dataloader.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/w2v_dataloader.hpp
  libs/ml/include/ml/estimators/dnn_classifier.hpp
  libs/ml/include/ml/estimators/estimator.hpp
  libs/ml/include/ml/optimisation/optimiser.hpp
  libs/ml/tests/ml/dataloader/skipgram_loader.cpp
  libs/ml/tests/ml/dataloader/tensor_dataloader.cpp
  libs/ml/tests/ml/optimisation/optimisers.cpp
Labels: A-ml, S-ready-for-review

#1548 Improve exception safety of mutex usage
  apps/constellation/open_api_http_module.cpp
  libs/core/include/core/containers/queue.hpp
  libs/core/include/core/logger.hpp
  libs/core/include/core/mutex.hpp
  libs/core/include/core/sync/tickets.hpp
  libs/core/src/logger.cpp
  libs/core/src/mutex.cpp
  libs/core/tests/containers/queue_tests.cpp
  libs/dkg/src/dkg.cpp
  libs/dkg/src/dkg_complaints_manager.cpp
  libs/dkg/src/rbc.cpp
  libs/http/include/http/connection.hpp
  libs/http/include/http/server.hpp
  libs/http/src/http_connection_manager.cpp
  libs/ledger/benchmark/transaction_verifier_bench.cpp
  libs/ledger/include/ledger/storage_unit/lane_identity.hpp
  libs/ledger/src/dag/dag_sync_service.cpp
  libs/ledger/tests/chaincode/fake_storage_unit.hpp
  libs/miner/include/miner/annealer_miner.hpp
  libs/ml/examples/asynchronous_distributed_learning/main.cpp
  libs/network/include/network/details/future_work_store.hpp
  libs/network/include/network/details/idle_work_store.hpp
  libs/network/include/network/generics/requesting_queue.hpp
  libs/network/include/network/management/abstract_connection.hpp
  libs/network/include/network/management/abstract_connection_register.hpp
  libs/network/include/network/management/client_manager.hpp
  libs/network/include/network/management/connection_register.hpp
  libs/network/include/network/muddle/muddle.hpp
  libs/network/include/network/muddle/peer_list.hpp
  libs/network/include/network/service/client_interface.hpp
  libs/network/include/network/service/feed_subscription_manager.hpp
  libs/network/include/network/service/protocol.hpp
  libs/network/include/network/service/server.hpp
  libs/network/include/network/service/service_client.hpp
  libs/network/include/network/tcp/client_connection.hpp
  libs/network/include/network/tcp/client_implementation.hpp
  libs/network/src/details/network_manager_implementation.cpp
  libs/network/src/details/thread_pool.cpp
  libs/network/src/service/client_interface.cpp
  libs/network/src/service/feed_subscription_manager.cpp
  libs/network/src/tcp/tcp_server.cpp
  libs/network/tests/muddle/router_tests.cpp
  libs/network/tests/network/tcp_client_server_stress_tests.cpp
  libs/network/tests/network/tcp_client_stress_tests.cpp
  libs/network/tests/thread_pool/thread_pool_tests.cpp
  libs/storage/include/storage/document_store.hpp
  libs/storage/include/storage/object_store.hpp
  libs/telemetry/include/telemetry/counter_map.hpp
  libs/telemetry/include/telemetry/gauge.hpp
  libs/telemetry/include/telemetry/histogram.hpp
  libs/telemetry/include/telemetry/histogram_map.hpp
  libs/telemetry/include/telemetry/registry.hpp
  libs/telemetry/src/counter_map.cpp
  libs/telemetry/src/gauge.cpp
  libs/telemetry/src/histogram.cpp
  libs/telemetry/src/histogram_map.cpp
  libs/telemetry/src/registry.cpp
  libs/vectorise/include/vectorise/threading/pool.hpp
Labels: S-ready-for-review

#1560 Don't move
  libs/core/src/byte_array/decoders.cpp
  libs/core/src/byte_array/encoders.cpp
  libs/core/tests/unit/string_tests.cpp
  libs/ml/include/ml/core/graph.hpp
  libs/network/src/muddle/router.cpp
  libs/network/tests/muddle/mrpc_stress_tests.cpp
  libs/network/tests/muddle/muddle_stress_tests.cpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
  libs/vectorise/include/vectorise/uint/uint.hpp
  libs/vm/include/vm/variant.hpp
  libs/vm/src/parser.cpp
Labels: C-bug, S-ready-for-review

#1561 Improve Sync Times
  apps/constellation/constellation.cpp
  libs/ledger/include/ledger/chain/block_coordinator.hpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/storage_unit/storage_unit_client.cpp
Labels: S-ready-for-review

#1506 Semi-synchronous distributed learning by passing gradients
  libs/ml/examples/asynchronous_distributed_learning/main.cpp
  libs/ml/examples/centralised_distributed_learning/main.cpp
  libs/ml/examples/decentralised_distributed_learning/main.cpp
  libs/ml/examples/distributed_learning/coordinator.hpp
  libs/ml/examples/distributed_learning/distributed_learning_client.hpp
  libs/ml/examples/distributed_learning/main.cpp
  libs/ml/include/ml/core/graph.hpp
  libs/ml/include/ml/ops/trainable.hpp
  libs/ml/include/ml/ops/weights.hpp
  libs/ml/include/ml/optimisation/adagrad_optimiser.hpp
  libs/ml/include/ml/optimisation/adam_optimiser.hpp
  libs/ml/include/ml/optimisation/momentum_optimiser.hpp
  libs/ml/include/ml/optimisation/rmsprop_optimiser.hpp
  libs/ml/include/ml/optimisation/sgd_optimiser.hpp
  libs/ml/tests/ml/ops/embeddings.cpp
  libs/ml/tests/ml/ops/weights.cpp
  libs/ml/tests/ml/training/basic_training.cpp
Labels: A-examples, A-ml, S-ready-for-review

#1572 remove redundant copy in main serializer
  libs/core/include/core/serializers/main_serializer_definition.hpp
  libs/core/src/serializers/main_serializer.cpp
Labels: S-ready-for-review

#1353 LDGR-321 init lists
  libs/vm/include/vm/analyser.hpp
  libs/vm/include/vm/common.hpp
  libs/vm/include/vm/generator.hpp
  libs/vm/include/vm/ir.hpp
  libs/vm/include/vm/opcodes.hpp
  libs/vm/include/vm/token.hpp
  libs/vm/include/vm/tokeniser.hpp
  libs/vm/include/vm/variant.hpp
  libs/vm/include/vm/vm.hpp
  libs/vm/scripts/buildtokeniser
  libs/vm/scripts/tokeniser.l
  libs/vm/src/analyser.cpp
  libs/vm/src/generator.cpp
  libs/vm/src/ir_builder.cpp
  libs/vm/src/parser.cpp
  libs/vm/src/state.cpp
  libs/vm/src/tokeniser.cpp
  libs/vm/src/vm.cpp
  libs/vm/src/vm_handlers.cpp
  libs/vm_modules/tests/unit/initializer_list_tests.cpp
Labels: A-vm, C-feature, S-ready-for-review

#1550 Dkg refactoring
  apps/beacon/main.cpp
  apps/constellation/constellation.cpp
  libs/beacon/include/beacon/aeon.hpp
  libs/beacon/include/beacon/beacon_manager.hpp
  libs/beacon/include/beacon/beacon_service.hpp
  libs/beacon/include/beacon/beacon_setup_protocol.hpp
  libs/beacon/include/beacon/beacon_setup_service.hpp
  libs/beacon/include/beacon/cabinet_member_details.hpp
  libs/beacon/include/beacon/entropy.hpp
  libs/beacon/include/beacon/public_key_message.hpp
  libs/beacon/src/beacon_manager.cpp
  libs/beacon/src/beacon_service.cpp
  libs/beacon/src/beacon_setup_protocol.cpp
  libs/beacon/src/beacon_setup_service.cpp
  libs/beacon/tests/dkg/dkg.cpp
  libs/beacon/tests/dkg/dkg_resilience.cpp
  libs/beacon/tests/dkg/full_cycle.cpp
  libs/core/include/core/service_ids.hpp
  libs/crypto/include/crypto/mcl_dkg.hpp
  libs/crypto/src/mcl_dkg.cpp
  libs/dkg/include/dkg/dkg_complaints_manager.hpp
  libs/dkg/src/dkg.cpp
  libs/dkg/src/dkg_complaints_manager.cpp
  libs/dkg/src/dkg_service.cpp
  libs/dkg/src/round.cpp
  libs/dkg/tests/gtests/dkg_tests.cpp
  libs/ledger/include/ledger/consensus/consensus.hpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/muddle/include/muddle/rbc.hpp
  libs/muddle/src/rbc.cpp
  libs/network/tests/rbc/rbc_tests.cpp
Labels: S-work-in-progress

#1385 Time travel across chains
  libs/ledger/include/ledger/chain/main_chain.hpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_protocol.hpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_service.hpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/src/protocols/main_chain_rpc_service.cpp
Labels: A-ledger, C-improvement, S-ready-for-review

#1587 Make a simple bert that can do a simple cls task
  libs/ml/examples/bert_simple_cls_example/main.cpp
  libs/ml/examples/bert_utilities.hpp
Labels: S-ready-for-review
