Repository fetchai/ledger, pull requests merged in 2019-07, with the labels that each got.

#1282 optimised embeddings and matrix multiply implementations
  libs/ml/include/ml/ops/embeddings.hpp
  libs/ml/include/ml/ops/matrix_multiply.hpp
Labels: S-ready-for-review

#1302 Core etch tests for range loops and Booleans operators
  libs/vm_modules/tests/unit/core_etch_tests.cpp
Labels: S-ready-for-review

#1292 L1 and L2 regularization implemented
  libs/ml/examples/mnist/main.cpp
  libs/ml/include/ml/graph.hpp
  libs/ml/include/ml/layers/fully_connected.hpp
  libs/ml/include/ml/ops/weights.hpp
  libs/ml/include/ml/regularisers/l1_regulariser.hpp
  libs/ml/include/ml/regularisers/l2_regulariser.hpp
  libs/ml/include/ml/regularisers/regularisation.hpp
  libs/ml/include/ml/regularisers/regulariser.hpp
  libs/ml/tests/CMakeLists.txt
  libs/ml/tests/ml/layers/fully_connected.cpp
  libs/ml/tests/ml/regularisers/main.cpp
Labels: A-ml, S-ready-for-review

#1233 Etch commodity example with training mode
  libs/ml/examples/commodity_prediction/main.cpp
  libs/ml/include/ml/dataloaders/ReadCSV.hpp
  libs/ml/include/ml/dataloaders/commodity_dataloader.hpp
  libs/ml/include/ml/dataloaders/mnist_loaders/mnist_loader.hpp
  libs/vm_modules/examples/commodity_prediction/main.cpp
  libs/vm_modules/examples/commodity_prediction/script/commodity_prediction.etch
  libs/vm_modules/examples/mnist/main.cpp
  libs/vm_modules/examples/mnist/script/mnist_optimiser.etch
  libs/vm_modules/include/vm_modules/ml/dataloaders/commodity_dataloader.hpp
  libs/vm_modules/include/vm_modules/ml/dataloaders/dataloader.hpp
  libs/vm_modules/include/vm_modules/ml/dataloaders/mnist_dataloader.hpp
  libs/vm_modules/include/vm_modules/ml/ml.hpp
  libs/vm_modules/include/vm_modules/ml/optimisation/adam_optimiser.hpp
  libs/vm_modules/include/vm_modules/vm_factory.hpp
Labels: S-ready-for-review

#1310 Shuffle unit test execution order in CI; fix storage tests
  cmake/BuildTools.cmake
  libs/storage/tests/gtest/key_value_index_tests.cpp
Labels: S-ready-for-review

#1311 Convolution 1D and 2D batch_dimension fix
  libs/ml/include/ml/layers/convolution_1d.hpp
  libs/ml/include/ml/layers/convolution_2d.hpp
  libs/ml/include/ml/ops/convolution_1d.hpp
  libs/ml/include/ml/ops/convolution_2d.hpp
Labels: S-ready-for-review

#1315 Ml prepare batch refactor
  libs/ml/examples/tsne/main.cpp
  libs/ml/include/ml/dataloaders/dataloader.hpp
  libs/ml/include/ml/dataloaders/mnist_loaders/mnist_loader.hpp
  libs/ml/include/ml/dataloaders/tensor_dataloader.hpp
  libs/ml/include/ml/optimisation/optimiser.hpp
  libs/ml/tests/ml/estimators/estimators.cpp
Labels: S-ready-for-review

#1319 Embeddings bugfix
  libs/ml/include/ml/ops/embeddings.hpp
Labels: S-ready-for-review

#1324 Tensor reshape update
  libs/math/include/math/tensor.hpp
  libs/math/include/math/tensor_broadcast.hpp
  libs/math/tests/math/all_tests/tensor_iterator/iterator.cpp
  libs/ml/include/ml/node.hpp
Labels: S-ready-for-review

#1327 Math library metric rework
  libs/math/benchmark/activation_functions/activations.cpp
  libs/math/include/math/activation_functions/elu.hpp
  libs/math/include/math/activation_functions/leaky_relu.hpp
  libs/math/include/math/activation_functions/relu.hpp
  libs/math/include/math/activation_functions/sigmoid.hpp
  libs/math/include/math/activation_functions/softmax.hpp
  libs/math/include/math/distance/absolute.hpp
  libs/math/include/math/metrics/cross_entropy.hpp
  libs/math/include/math/metrics/kl_divergence.hpp
  libs/math/include/math/metrics/l2_loss.hpp
  libs/math/include/math/metrics/l2_norm.hpp
  libs/math/include/math/metrics/mean_absolute_error.hpp
  libs/math/include/math/metrics/mean_square_error.hpp
  libs/math/include/math/tensor.hpp
  libs/math/tests/math/all_tests/activation_functions/relu.cpp
  libs/math/tests/math/all_tests/activation_functions/sigmoid.cpp
  libs/math/tests/math/all_tests/activation_functions/softmax.cpp
  libs/math/tests/math/all_tests/metrics/cross_entropy_loss.cpp
  libs/math/tests/math/all_tests/metrics/kl_divergence_tests.cpp
  libs/math/tests/math/all_tests/metrics/l2_loss.cpp
  libs/math/tests/math/all_tests/metrics/l2_norm.cpp
  libs/math/tests/math/all_tests/metrics/mean_absolute_error.cpp
  libs/math/tests/math/all_tests/metrics/mean_squared_error.cpp
  libs/ml/include/ml/clustering/tsne.hpp
  libs/ml/include/ml/ops/activations/elu.hpp
  libs/ml/include/ml/ops/activations/leaky_relu.hpp
  libs/ml/include/ml/ops/activations/logsigmoid.hpp
  libs/ml/include/ml/ops/activations/logsoftmax.hpp
  libs/ml/include/ml/ops/activations/randomized_relu.hpp
  libs/ml/include/ml/ops/activations/relu.hpp
  libs/ml/include/ml/ops/activations/sigmoid.hpp
  libs/ml/include/ml/ops/activations/softmax.hpp
  libs/ml/include/ml/ops/leaky_relu_op.hpp
  libs/ml/include/ml/ops/loss_functions/cross_entropy_loss.hpp
  libs/ml/include/ml/ops/loss_functions/mean_square_error_loss.hpp
  libs/ml/include/ml/ops/loss_functions/softmax_cross_entropy_loss.hpp
  libs/ml/tests/ml/training/basic_training.cpp
Labels: S-ready-for-review

#1325 Tweak test infrastructure
  scripts/ci-tool.py
  scripts/ci/install-test-dependencies.sh
  scripts/end_to_end_test/run_end_to_end_test.py
Labels: S-ready-for-review

#1328 Benchmarks for ops
  libs/ml/benchmark/ops/ops.cpp
Labels: S-ready-for-review

#1268 Sgns fix
  .gitignore
  libs/ml/examples/mnist_estimator/main.cpp
  libs/ml/examples/word2vec_SGNS/main.cpp
  libs/ml/examples/word2vec_SGNS_dataloader/main.cpp
  libs/ml/examples/word2vec_simple/main.cpp
  libs/ml/examples/word2vec_simple/w2v_model.hpp
  libs/ml/include/ml/dataloaders/dataloader.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/cbow_dataloader.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/sgns_w2v_dataloader.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/skipgram_dataloader.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/unigram_table.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/vocab.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/w2v_dataloader.hpp
  libs/ml/include/ml/estimators/dnn_classifier.hpp
  libs/ml/include/ml/estimators/estimator.hpp
  libs/ml/include/ml/graph.hpp
  libs/ml/include/ml/layers/skip_gram.hpp
  libs/ml/include/ml/node.hpp
  libs/ml/include/ml/ops/embeddings.hpp
  libs/ml/include/ml/optimisation/adagrad_optimiser.hpp
  libs/ml/include/ml/optimisation/adam_optimiser.hpp
  libs/ml/include/ml/optimisation/momentum_optimiser.hpp
  libs/ml/include/ml/optimisation/optimiser.hpp
  libs/ml/include/ml/optimisation/rmsprop_optimiser.hpp
  libs/ml/include/ml/optimisation/sgd_optimiser.hpp
  libs/ml/include/ml/optimisation/types.hpp
  libs/ml/tests/ml/dataloader/cbow_loader.cpp
  libs/ml/tests/ml/dataloader/skipgram_loader.cpp
  libs/ml/tests/ml/estimators/estimators.cpp
Labels: S-ready-for-review

#1335 Create fetch-version library
  CMakeLists.txt
  apps/constellation/CMakeLists.txt
  apps/constellation/bootstrap_monitor.cpp
  apps/constellation/main.cpp
  apps/etch/CMakeLists.txt
  apps/etch/main.cpp
  cmake/BuildTargets.cmake
  cmake/fetch_version.cpp.in
  libs/network/include/network/p2pservice/p2p_http_interface.hpp
  libs/storage/examples/lane_client.cpp
  libs/version/CMakeLists.txt
  libs/version/include/version/cli_header.hpp
  libs/version/include/version/fetch_version.hpp
  libs/version/src/cli_header.cpp
Labels: S-ready-for-review

#1313 Ensure naming consistency of Math/ML library
  libs/vm_modules/examples/abs/abs.etch
  libs/vm_modules/examples/abs/main.cpp
  libs/vm_modules/examples/commodity_prediction/script/commodity_prediction.etch
  libs/vm_modules/examples/mnist/script/mnist_optimiser.etch
  libs/vm_modules/examples/trigonometry/main.cpp
  libs/vm_modules/examples/trigonometry/trig.etch
  libs/vm_modules/include/vm_modules/math/random.hpp
  libs/vm_modules/include/vm_modules/math/tensor.hpp
  libs/vm_modules/include/vm_modules/ml/dataloaders/dataloader.hpp
  libs/vm_modules/include/vm_modules/ml/graph.hpp
  libs/vm_modules/include/vm_modules/ml/ops/loss_functions/cross_entropy_loss.hpp
  libs/vm_modules/include/vm_modules/ml/ops/loss_functions/mean_square_error_loss.hpp
  libs/vm_modules/include/vm_modules/ml/optimisation/adam_optimiser.hpp
  libs/vm_modules/include/vm_modules/ml/state_dict.hpp
  libs/vm_modules/include/vm_modules/ml/training_pair.hpp
  libs/vm_modules/tests/unit/math.cpp
  libs/vm_modules/tests/unit/vm_modules_tests.cpp
  scripts/etch-language-tests/maths/abs.etch
  scripts/etch-language-tests/maths/trig.etch
Labels: S-ready-for-review

#1343 Change Bloom filter feature flag semantics; add telemetry
  apps/constellation/constellation.cpp
  libs/core/include/core/bloom_filter.hpp
  libs/core/include/core/bloom_filter_interface.hpp
  libs/core/src/bloom_filter.cpp
  libs/core/src/bloom_filter_interface.cpp
  libs/core/tests/unit/bloom_filter_tests.cpp
  libs/ledger/benchmark/main_chain_benchs.cpp
  libs/ledger/include/ledger/chain/main_chain.hpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/tests/chain/block_coordinator_tests.cpp
  libs/ledger/tests/chain/main_chain_subtree_tests.cpp
  libs/ledger/tests/chain/main_chain_tests.cpp
  libs/miner/tests/basic_miner_tests.cpp
  libs/telemetry/include/telemetry/gauge.hpp
Labels: S-ready-for-review

#1344 Mark ml_dataloader_gtest as slow
  libs/ml/tests/CMakeLists.txt
Labels: S-ready-for-review

#1352 Tweak FixedPoint docs strings
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
Labels: S-ready-for-review

#1347 Feature/improve uint class
  .gitignore
  libs/math/tests/math/all_tests/basic_math/big_number_tests.cpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
  libs/vectorise/include/vectorise/platform.hpp
  libs/vectorise/include/vectorise/uint/uint.hpp
  libs/vm_modules/include/vm_modules/math/bignumber.hpp
Labels: A-maths, C-improvement, S-ready-for-review

#1341 Add initial executor benchmark
  libs/ledger/benchmark/executor_bench.cpp
  libs/ledger/benchmark/in_memory_storage.cpp
  libs/ledger/benchmark/in_memory_storage.hpp
  libs/ledger/benchmark/state_sentinel_bench.cpp
Labels: S-ready-for-review

#1351 Pass and return integers by value instead of const ref
  libs/core/include/core/bloom_filter.hpp
  libs/core/include/core/byte_array/const_byte_array.hpp
  libs/core/include/core/byte_array/tokenizer/token.hpp
  libs/core/include/core/commandline/parameter_parser.hpp
  libs/core/include/core/json/document.hpp
  libs/core/include/core/serializers/byte_array_buffer.hpp
  libs/core/include/core/serializers/counter.hpp
  libs/core/include/core/serializers/typed_byte_array_buffer.hpp
  libs/core/src/commandline/parameter_parser.cpp
  libs/core/tests/random/bit_statistics.hpp
  libs/crypto/include/crypto/fnv_detail.hpp
  libs/crypto/include/crypto/identity.hpp
  libs/http/include/http/connection.hpp
  libs/http/include/http/request.hpp
  libs/math/include/math/tensor.hpp
  libs/miner/include/miner/block_optimiser.hpp
  libs/miner/include/miner/instance/binary_problem.hpp
  libs/miner/include/miner/optimisation/binary_annealer.hpp
  libs/network/include/network/management/abstract_connection.hpp
  libs/network/include/network/service/abstract_callable.hpp
  libs/network/include/network/service/feed_subscription_manager.hpp
  libs/network/include/network/service/protocol.hpp
  libs/network/include/network/service/publication_feed.hpp
  libs/network/include/network/tcp/tcp_server.hpp
  libs/network/src/tcp/tcp_server.cpp
  libs/storage/examples/lane_client.cpp
  libs/storage/include/storage/cache_line_LRU_random_access_stack.hpp
  libs/storage/include/storage/cache_line_random_access_stack.hpp
  libs/storage/include/storage/cached_random_access_stack.hpp
  libs/storage/include/storage/file_object.hpp
  libs/storage/include/storage/key_value_index.hpp
  libs/storage/include/storage/mmap_random_access_stack.hpp
  libs/storage/include/storage/new_versioned_random_access_stack.hpp
  libs/storage/include/storage/random_access_stack.hpp
  libs/storage/include/storage/variant_stack.hpp
  libs/storage/include/storage/versioned_random_access_stack.hpp
  libs/storage/tests/gtest/file_object/fake_random_access_stack.hpp
  libs/vectorise/include/vectorise/memory/array.hpp
  libs/vectorise/include/vectorise/memory/parallel_dispatcher.hpp
  libs/vectorise/include/vectorise/memory/shared_array.hpp
  libs/vectorise/include/vectorise/uint/uint.hpp
  libs/vm_modules/examples/commodity_prediction/main.cpp
  libs/vm_modules/examples/mnist/main.cpp
  libs/vm_modules/include/vm_modules/math/bignumber.hpp
  libs/vm_modules/include/vm_modules/math/tensor.hpp
Labels: S-ready-for-review

#1339 Configuration Overhaul
  apps/constellation/CMakeLists.txt
  apps/constellation/config_builder.cpp
  apps/constellation/config_builder.hpp
  apps/constellation/constants.hpp
  apps/constellation/constellation.cpp
  apps/constellation/constellation.hpp
  apps/constellation/key_generator.cpp
  apps/constellation/key_generator.hpp
  apps/constellation/main.cpp
  apps/constellation/manifest_builder.cpp
  apps/constellation/manifest_builder.hpp
  apps/constellation/settings.cpp
  apps/constellation/settings.hpp
  libs/core/include/core/commandline/parameter_parser.hpp
  libs/core/include/core/containers/is_in.hpp
  libs/core/include/core/feature_flags.hpp
  libs/core/include/core/filesystem/read_file_contents.hpp
  libs/core/src/commandline/parameter_parser.cpp
  libs/core/src/feature_flags.cpp
  libs/core/src/filesystem/read_file_contents.cpp
  libs/ledger/tests/chaincode/smart_contract_tests.cpp
  libs/ledger/tests/unit/stake_update_queue_tests.cpp
  libs/network/include/network/uri.hpp
  libs/network/src/uri.cpp
  libs/settings/CMakeLists.txt
  libs/settings/include/settings/detail/csv_string_helpers.hpp
  libs/settings/include/settings/detail/environment_wrapper.hpp
  libs/settings/include/settings/setting.hpp
  libs/settings/include/settings/setting_base.hpp
  libs/settings/include/settings/setting_collection.hpp
  libs/settings/src/detail/environment_wrapper.cpp
  libs/settings/src/setting.cpp
  libs/settings/src/setting_base.cpp
  libs/settings/src/setting_collection.cpp
  libs/settings/tests/CMakeLists.txt
  libs/settings/tests/unit/mock_environment.hpp
  libs/settings/tests/unit/setting_collection_tests.cpp
  libs/settings/tests/unit/setting_tests.cpp
  scripts/ci-tool.py
Labels: S-ready-for-review

#1348 MSE Fix + weightings
  libs/math/include/math/metrics/mean_absolute_error.hpp
  libs/math/include/math/metrics/mean_square_error.hpp
  libs/ml/include/ml/ops/loss_functions/mean_square_error_loss.hpp
  libs/ml/tests/ml/ops/loss_functions/mean_square_error_loss.cpp
  libs/ml/tests/ml/optimisation/optimisers.cpp
Labels: S-ready-for-review

#1366 Tensor slice/view improvements
  libs/math/include/math/matrix_operations.hpp
  libs/math/include/math/tensor.hpp
  libs/math/include/math/tensor_view.hpp
  libs/ml/examples/word2vec_simple/word_analogy.hpp
  libs/ml/include/ml/dataloaders/commodity_dataloader.hpp
  libs/ml/include/ml/dataloaders/crypto_prediction_loaders/crypto_dataloader.hpp
  libs/ml/include/ml/dataloaders/dataloader.hpp
  libs/ml/include/ml/dataloaders/mnist_loaders/mnist_loader.hpp
  libs/ml/include/ml/dataloaders/tensor_dataloader.hpp
  libs/ml/include/ml/graph.hpp
  libs/ml/include/ml/ops/embeddings.hpp
  libs/ml/include/ml/ops/flatten.hpp
  libs/ml/include/ml/ops/leaky_relu_op.hpp
  libs/ml/include/ml/ops/matrix_multiply.hpp
  libs/ml/include/ml/optimisation/optimiser.hpp
  libs/ml/tests/ml/training/basic_training.cpp
Labels: S-ready-for-review

#1372 Ml slices to views
  libs/math/include/math/activation_functions/leaky_relu.hpp
  libs/math/include/math/matrix_operations.hpp
  libs/ml/examples/asynchronous_distributed_learning/main.cpp
  libs/ml/tests/ml/ops/embeddings.cpp
Labels: S-ready-for-review

#1386 Use std::call_once
  libs/dkg/src/dkg.cpp
Labels: S-ready-for-review

#1388 Added Slice operation for Slice
  libs/math/benchmark/tensor/tensor.cpp
  libs/math/include/math/matrix_operations.hpp
  libs/math/include/math/tensor.hpp
  libs/math/include/math/tensor_slice_iterator.hpp
  libs/math/include/math/tensor_squeeze.hpp
  libs/math/tests/math/all_tests/tensor/tensor_operations.cpp
Labels: A-maths, S-ready-for-review

#1358 Re-enable tests; fix build failures
  libs/core/tests/CMakeLists.txt
  libs/core/tests/containers/queue_tests.cpp
  libs/ledger/tests/executors/execution_manager_state_tests.cpp
  libs/ledger/tests/executors/execution_manager_tests.cpp
  libs/network/tests/CMakeLists.txt
  libs/network/tests/muddle/dispatcher_tests.cpp
  libs/network/tests/muddle/mrpc_stress_tests.cpp
  libs/network/tests/muddle/muddle_stress_tests.cpp
  libs/network/tests/muddle/peer_list_tests.cpp
  libs/network/tests/muddle/subscription_registrar_tests.cpp
  libs/network/tests/network/tcp_client_server_stress_tests.cpp
  libs/network/tests/network/tcp_client_stress_tests.cpp
  libs/network/tests/network/thread_manager_stress_tests.cpp
  libs/network/tests/thread_pool/thread_pool_tests.cpp
Labels: S-ready-for-review

#1414 Replace library shuffles
  libs/math/include/math/clustering/k_means.hpp
  libs/ml/examples/asynchronous_distributed_learning/main.cpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/basic_textloader.hpp
Labels: S-ready-for-review

#1420 Move vm_modules implementation to cpp files
  apps/etch/main.cpp
  libs/ml/include/ml/utilities/min_max_scaler.hpp
  libs/ml/include/ml/utilities/scaler.hpp
  libs/network/include/network/service/types.hpp
  libs/vm/src/state.cpp
  libs/vm_modules/examples/commodity_prediction/main.cpp
  libs/vm_modules/examples/crypto_price_prediction/main.cpp
  libs/vm_modules/include/vm_modules/core/byte_array_wrapper.hpp
  libs/vm_modules/include/vm_modules/core/panic.hpp
  libs/vm_modules/include/vm_modules/core/structured_data.hpp
  libs/vm_modules/include/vm_modules/core/type_convert.hpp
  libs/vm_modules/include/vm_modules/crypto/sha256.hpp
  libs/vm_modules/include/vm_modules/math/abs.hpp
  libs/vm_modules/include/vm_modules/math/bignumber.hpp
  libs/vm_modules/include/vm_modules/math/exp.hpp
  libs/vm_modules/include/vm_modules/math/log.hpp
  libs/vm_modules/include/vm_modules/math/math.hpp
  libs/vm_modules/include/vm_modules/math/pow.hpp
  libs/vm_modules/include/vm_modules/math/random.hpp
  libs/vm_modules/include/vm_modules/math/sqrt.hpp
  libs/vm_modules/include/vm_modules/math/tensor.hpp
  libs/vm_modules/include/vm_modules/math/trigonometry.hpp
  libs/vm_modules/include/vm_modules/ml/dataloaders/dataloader.hpp
  libs/vm_modules/include/vm_modules/ml/graph.hpp
  libs/vm_modules/include/vm_modules/ml/ml.hpp
  libs/vm_modules/include/vm_modules/ml/optimisation/optimiser.hpp
  libs/vm_modules/include/vm_modules/ml/state_dict.hpp
  libs/vm_modules/include/vm_modules/ml/training_pair.hpp
  libs/vm_modules/include/vm_modules/ml/utilities/scaler.hpp
  libs/vm_modules/include/vm_modules/polyfill/bitshifting.hpp
  libs/vm_modules/include/vm_modules/polyfill/bitwise_ops.hpp
  libs/vm_modules/include/vm_modules/vm_factory.hpp
  libs/vm_modules/src/core/byte_array_wrapper.cpp
  libs/vm_modules/src/core/panic.cpp
  libs/vm_modules/src/core/print.cpp
  libs/vm_modules/src/core/structured_data.cpp
  libs/vm_modules/src/core/type_convert.cpp
  libs/vm_modules/src/crypto/sha256.cpp
  libs/vm_modules/src/math/abs.cpp
  libs/vm_modules/src/math/bignumber.cpp
  libs/vm_modules/src/math/exp.cpp
  libs/vm_modules/src/math/log.cpp
  libs/vm_modules/src/math/math.cpp
  libs/vm_modules/src/math/pow.cpp
  libs/vm_modules/src/math/random.cpp
  libs/vm_modules/src/math/sqrt.cpp
  libs/vm_modules/src/math/tensor.cpp
  libs/vm_modules/src/math/trigonometry.cpp
  libs/vm_modules/src/ml/dataloaders/dataloader.cpp
  libs/vm_modules/src/ml/graph.cpp
  libs/vm_modules/src/ml/ml.cpp
  libs/vm_modules/src/ml/optimisation/optimiser.cpp
  libs/vm_modules/src/ml/state_dict.cpp
  libs/vm_modules/src/ml/training_pair.cpp
  libs/vm_modules/src/ml/utilities/scaler.cpp
  libs/vm_modules/src/polyfill/bitshifting.cpp
  libs/vm_modules/src/polyfill/bitwise_ops.cpp
  libs/vm_modules/src/vm_factory.cpp
  libs/vm_modules/tests/unit/custom_binding_tests.cpp
  libs/vm_modules/tests/unit/math.cpp
Labels: S-ready-for-review

#1396 Weight sharing
  libs/math/include/math/base_types.hpp
  libs/ml/include/ml/graph.hpp
  libs/ml/include/ml/layers/fully_connected.hpp
  libs/ml/include/ml/meta/ml_type_traits.hpp
  libs/ml/include/ml/node.hpp
  libs/ml/include/ml/ops/divide.hpp
  libs/ml/include/ml/ops/weights.hpp
  libs/ml/tests/ml/layers/fully_connected.cpp
  libs/ml/tests/ml/ops/graph.cpp
Labels: S-ready-for-review

#1413 N-dimensional Softmax
  libs/math/include/math/activation_functions/softmax.hpp
  libs/math/include/math/base_types.hpp
  libs/math/include/math/matrix_operations.hpp
  libs/math/include/math/tensor.hpp
  libs/math/include/math/tensor_broadcast.hpp
  libs/math/include/math/tensor_reduce.hpp
  libs/math/include/math/tensor_squeeze.hpp
  libs/math/tests/math/all_tests/activation_functions/softmax.cpp
  libs/math/tests/math/all_tests/matrix_operations/matrix_operations.cpp
  libs/ml/examples/code2vec/main.cpp
  libs/ml/include/ml/ops/activations/logsoftmax.hpp
  libs/ml/include/ml/ops/activations/softmax.hpp
  libs/ml/include/ml/ops/loss_functions/cross_entropy_loss.hpp
  libs/ml/include/ml/ops/loss_functions/softmax_cross_entropy_loss.hpp
  libs/ml/tests/ml/ops/activations/logsoftmax.cpp
  libs/ml/tests/ml/ops/activations/softmax.cpp
  libs/ml/tests/ml/ops/loss_functions/softmax_cross_entropy_loss.cpp
Labels: A-maths, A-ml, S-ready-for-review

#1429 Const broadcast implemented
  libs/math/include/math/fundamental_operators.hpp
  libs/math/include/math/tensor_broadcast.hpp
  libs/math/include/math/tensor_slice_iterator.hpp
  libs/math/tests/math/all_tests/tensor_iterator/broadcast.cpp
Labels: A-maths, S-ready-for-review
