Repository fetchai/ledger, pull requests merged in 2020-02, with the labels that each got.

#2359 Attach dummy Ledger Context to Synergetic Contracts
  libs/ledger/src/upow/synergetic_contract.cpp
Labels: S-ready-to-merge

#2365 added backward charge estimation to losses
  libs/ml/include/ml/charge_estimation/ops/constants.hpp
  libs/ml/include/ml/ops/loss_functions/cross_entropy_loss.hpp
  libs/ml/include/ml/ops/loss_functions/mean_square_error_loss.hpp
  libs/ml/include/ml/ops/loss_functions/softmax_cross_entropy_loss.hpp
  libs/ml/include/ml/ops/ops.hpp
  libs/ml/src/ops/loss_functions/cross_entropy_loss.cpp
  libs/ml/src/ops/loss_functions/mean_square_error_loss.cpp
  libs/ml/src/ops/loss_functions/softmax_cross_entropy_loss.cpp
Labels: S-ready-to-merge

#2374 Backport: Fix legacy issues with protobuf message size accessors
  cmake/BuildTargets.cmake
Labels: S-ready-for-review, S-ready-to-merge

#2383 Deploy Python tooling with pipenv
  Jenkinsfile
  Pipfile
  Pipfile.lock
  scripts/install-test-dependencies.sh
Labels: S-ready-to-merge

#2378 Sort clang-format config
  .clang-format
Labels: S-ready-to-merge

#2346 Etch binding for model.predict() estimation
  libs/ml/include/ml/layers/convolution_1d.hpp
  libs/ml/include/ml/layers/convolution_2d.hpp
  libs/ml/include/ml/saveparams/saveable_params.hpp
  libs/ml/include/ml/serializers/ml_types.hpp
  libs/ml/src/layers/convolution_1d.cpp
  libs/ml/src/layers/convolution_2d.cpp
  libs/ml/src/ops/placeholder.cpp
  libs/ml/tests/unit/graph/graph.cpp
  libs/ml/tests/unit/layers/convolution_1d.cpp
  libs/ml/tests/unit/layers/convolution_2d.cpp
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/include/vm_modules/use_estimator.hpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
  libs/vm-modules/tests/unit/ml/model_estimator_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2386 Dial down logging
  libs/ledger/src/consensus/consensus.cpp
Labels: S-ready-to-merge

#2387 Backport: Fix issues with alternative protobuf versions between macos and linux
  cmake/BuildTargets.cmake
  libs/oef-base/src/proto_comms/ProtoMessageSender.cpp
  libs/oef-base/src/proto_comms/ProtoPathMessageSender.cpp
Labels: S-ready-to-merge

#2385 Fix issues with alternative protobuf versions between macos and linux
  cmake/BuildTargets.cmake
  libs/oef-base/src/proto_comms/ProtoMessageSender.cpp
  libs/oef-base/src/proto_comms/ProtoPathMessageSender.cpp
Labels: S-ready-to-merge

#2375 Simplify FNV PIMPL; remove unused headers
  libs/crypto/include/crypto/fnv.hpp
  libs/crypto/src/fnv.cpp
Labels: S-ready-to-merge

#2381 dial down logging
  libs/ledger/src/consensus/consensus.cpp
Labels: S-ready-to-merge

#2379 added backward charge estimation for activations
  libs/ml/include/ml/charge_estimation/ops/constants.hpp
  libs/ml/include/ml/ops/activations/dropout.hpp
  libs/ml/include/ml/ops/activations/elu.hpp
  libs/ml/include/ml/ops/activations/gelu.hpp
  libs/ml/include/ml/ops/activations/leaky_relu.hpp
  libs/ml/include/ml/ops/activations/logsigmoid.hpp
  libs/ml/include/ml/ops/activations/logsoftmax.hpp
  libs/ml/include/ml/ops/activations/randomised_relu.hpp
  libs/ml/include/ml/ops/activations/relu.hpp
  libs/ml/include/ml/ops/activations/sigmoid.hpp
  libs/ml/include/ml/ops/activations/softmax.hpp
  libs/ml/src/ops/activations/dropout.cpp
  libs/ml/src/ops/activations/elu.cpp
  libs/ml/src/ops/activations/gelu.cpp
  libs/ml/src/ops/activations/leaky_relu.cpp
  libs/ml/src/ops/activations/logsigmoid.cpp
  libs/ml/src/ops/activations/logsoftmax.cpp
  libs/ml/src/ops/activations/randomised_relu.cpp
  libs/ml/src/ops/activations/relu.cpp
  libs/ml/src/ops/activations/sigmoid.cpp
  libs/ml/src/ops/activations/softmax.cpp
Labels: S-ready-to-merge

#2333 prevent out of order entropy gen
  libs/beacon/src/beacon_service.cpp
Labels: S-ready-to-merge

#2368 Fix teardown segfault if no genesis file
  libs/constellation/src/constellation.cpp
Labels: S-ready-to-merge

#2369 Fix serializer element count; typos
  libs/core/include/core/serializers/array_interface.hpp
  libs/core/include/core/serializers/map_interface.hpp
  libs/ledger/include/ledger/consensus/stake_manager.hpp
Labels: S-ready-to-merge

#2382 small optimisations in Log2/Sqrt, rework of multiplication of fp128 t…
  libs/math/benchmark/matrix_ops/matrix_ops.cpp
  libs/math/tests/unit/fixed_point/fixed_point.cpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
Labels: A-maths, C-optimisation, S-ready-to-merge

#2354 ML 432 bugfix to vmscaler
  libs/ml/src/utilities/min_max_scaler.cpp
  libs/ml/tests/unit/utilities/scaler.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2391 added backward charge estimation for pooling ops
  libs/ml/include/ml/ops/avg_pool_1d.hpp
  libs/ml/include/ml/ops/avg_pool_2d.hpp
  libs/ml/include/ml/ops/max_pool_1d.hpp
  libs/ml/include/ml/ops/max_pool_2d.hpp
  libs/ml/src/ops/avg_pool_1d.cpp
  libs/ml/src/ops/avg_pool_2d.cpp
  libs/ml/src/ops/max_pool_1d.cpp
  libs/ml/src/ops/max_pool_2d.cpp
Labels: S-ready-to-merge

#2308 solution for storing entropy to file for quick crash recovery
  libs/beacon/include/beacon/beacon_service.hpp
  libs/beacon/src/beacon_service.cpp
  libs/beacon/tests/unit/test_beacon_service.cpp
  libs/constellation/src/constellation.cpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_service.hpp
  libs/ledger/src/protocols/main_chain_rpc_service.cpp
Labels: S-ready-to-merge

#2392 ChargeBackward for the Graph
  libs/ml/include/ml/layers/fully_connected.hpp
  libs/ml/include/ml/ops/activations/dropout.hpp
  libs/ml/include/ml/ops/activations/elu.hpp
  libs/ml/include/ml/ops/activations/gelu.hpp
  libs/ml/include/ml/ops/activations/leaky_relu.hpp
  libs/ml/include/ml/ops/activations/logsigmoid.hpp
  libs/ml/include/ml/ops/activations/logsoftmax.hpp
  libs/ml/include/ml/ops/activations/randomised_relu.hpp
  libs/ml/include/ml/ops/activations/relu.hpp
  libs/ml/include/ml/ops/activations/sigmoid.hpp
  libs/ml/include/ml/ops/activations/softmax.hpp
  libs/ml/include/ml/ops/avg_pool_1d.hpp
  libs/ml/include/ml/ops/avg_pool_2d.hpp
  libs/ml/include/ml/ops/loss_functions/cross_entropy_loss.hpp
  libs/ml/include/ml/ops/loss_functions/mean_square_error_loss.hpp
  libs/ml/include/ml/ops/loss_functions/softmax_cross_entropy_loss.hpp
  libs/ml/include/ml/ops/max_pool_1d.hpp
  libs/ml/include/ml/ops/max_pool_2d.hpp
  libs/ml/include/ml/ops/ops.hpp
  libs/ml/src/layers/fully_connected.cpp
  libs/ml/src/ops/activations/dropout.cpp
  libs/ml/src/ops/activations/elu.cpp
  libs/ml/src/ops/activations/gelu.cpp
  libs/ml/src/ops/activations/leaky_relu.cpp
  libs/ml/src/ops/activations/logsigmoid.cpp
  libs/ml/src/ops/activations/logsoftmax.cpp
  libs/ml/src/ops/activations/randomised_relu.cpp
  libs/ml/src/ops/activations/relu.cpp
  libs/ml/src/ops/activations/sigmoid.cpp
  libs/ml/src/ops/activations/softmax.cpp
  libs/ml/src/ops/avg_pool_1d.cpp
  libs/ml/src/ops/avg_pool_2d.cpp
  libs/ml/src/ops/loss_functions/cross_entropy_loss.cpp
  libs/ml/src/ops/loss_functions/mean_square_error_loss.cpp
  libs/ml/src/ops/loss_functions/softmax_cross_entropy_loss.cpp
  libs/ml/src/ops/max_pool_1d.cpp
  libs/ml/src/ops/max_pool_2d.cpp
  libs/ml/tests/unit/graph/graph.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2371 ML-252 added embeddings
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/include/vm_modules/ml/model/model_estimator.hpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/src/ml/model/model_estimator.cpp
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
Labels: S-ready-to-merge

#1974 Opcode profiling
  apps/constellation/main.cpp
  libs/vm-modules/benchmark/CMakeLists.txt
  libs/vm-modules/benchmark/opcode/main.cpp
  libs/vm-modules/benchmark/opcode/opcode_bench.cpp
  libs/vm/CMakeLists.txt
  libs/vm/include/vm/vm.hpp
  libs/vm/src/vm.cpp
  scripts/benchmark/opcode_timing.py
  scripts/benchmark/vm_benchmark_plots.py
  scripts/benchmark/vm_benchmark_tables.py
  scripts/benchmark/vm_least_squares.py
Labels: S-ready-to-merge

#2397 Improvement/more telemetry backport
  libs/ledger/include/ledger/chain/main_chain.hpp
  libs/ledger/src/chain/main_chain.cpp
Labels: S-ready-to-merge

#2179 Set opcode charges based on benchmark times
  libs/vm-modules/src/math/bignumber.cpp
  libs/vm/include/vm/address.hpp
  libs/vm/include/vm/opcode_charges.hpp
  libs/vm/include/vm/vm.hpp
  libs/vm/src/fixed.cpp
  libs/vm/src/object.cpp
  libs/vm/src/string.cpp
  libs/vm/src/vm.cpp
Labels: S-ready-to-merge

#2400 added backward charge estimations for ops
  libs/ml/include/ml/charge_estimation/ops/constants.hpp
  libs/ml/include/ml/ops/abs.hpp
  libs/ml/include/ml/ops/add.hpp
  libs/ml/include/ml/ops/concatenate.hpp
  libs/ml/include/ml/ops/convolution_1d.hpp
  libs/ml/include/ml/ops/convolution_2d.hpp
  libs/ml/include/ml/ops/dataholder.hpp
  libs/ml/include/ml/ops/divide.hpp
  libs/ml/include/ml/ops/embeddings.hpp
  libs/ml/include/ml/ops/exp.hpp
  libs/ml/include/ml/ops/flatten.hpp
  libs/ml/include/ml/ops/layer_norm.hpp
  libs/ml/include/ml/ops/log.hpp
  libs/ml/include/ml/ops/mask_fill.hpp
  libs/ml/include/ml/ops/matrix_multiply.hpp
  libs/ml/include/ml/ops/maximum.hpp
  libs/ml/include/ml/ops/multiply.hpp
  libs/ml/include/ml/ops/one_hot.hpp
  libs/ml/include/ml/ops/prelu_op.hpp
  libs/ml/include/ml/ops/reduce_mean.hpp
  libs/ml/include/ml/ops/reshape.hpp
  libs/ml/include/ml/ops/slice.hpp
  libs/ml/include/ml/ops/sqrt.hpp
  libs/ml/include/ml/ops/squeeze.hpp
  libs/ml/include/ml/ops/strided_slice.hpp
  libs/ml/include/ml/ops/subtract.hpp
  libs/ml/include/ml/ops/tanh.hpp
  libs/ml/include/ml/ops/top_k.hpp
  libs/ml/include/ml/ops/transpose.hpp
  libs/ml/src/ops/abs.cpp
  libs/ml/src/ops/add.cpp
  libs/ml/src/ops/concatenate.cpp
  libs/ml/src/ops/convolution_1d.cpp
  libs/ml/src/ops/convolution_2d.cpp
  libs/ml/src/ops/dataholder.cpp
  libs/ml/src/ops/divide.cpp
  libs/ml/src/ops/embeddings.cpp
  libs/ml/src/ops/exp.cpp
  libs/ml/src/ops/flatten.cpp
  libs/ml/src/ops/layer_norm.cpp
  libs/ml/src/ops/log.cpp
  libs/ml/src/ops/mask_fill.cpp
  libs/ml/src/ops/matrix_multiply.cpp
  libs/ml/src/ops/maximum.cpp
  libs/ml/src/ops/multiply.cpp
  libs/ml/src/ops/one_hot.cpp
  libs/ml/src/ops/prelu_op.cpp
  libs/ml/src/ops/reduce_mean.cpp
  libs/ml/src/ops/reshape.cpp
  libs/ml/src/ops/slice.cpp
  libs/ml/src/ops/sqrt.cpp
  libs/ml/src/ops/squeeze.cpp
  libs/ml/src/ops/strided_slice.cpp
  libs/ml/src/ops/subtract.cpp
  libs/ml/src/ops/tanh.cpp
  libs/ml/src/ops/top_k.cpp
  libs/ml/src/ops/transpose.cpp
Labels: S-ready-to-merge

#2376 Wrap tests in unnamed namespace
  libs/storage/tests/unit/cache_line_LRU_random_access_stack_tests.cpp
  libs/storage/tests/unit/cache_line_random_access_stack_tests.cpp
  libs/storage/tests/unit/cached_random_access_stack_tests.cpp
  libs/storage/tests/unit/mmap_random_access_stack_tests.cpp
  libs/storage/tests/unit/mocked_cached_random_access_stack_tests.cpp
  libs/storage/tests/unit/single_object_store_tests.cpp
  libs/storage/tests/unit/variant_stack_tests.cpp
  libs/storage/tests/unit/versioned_random_access_stack_tests.cpp
Labels: S-ready-to-merge

#2389 Remove unnecessary typename
  libs/core/include/core/mutex.hpp
  libs/crypto/include/crypto/openssl_memory_detail.hpp
  libs/crypto/tests/unit/openssl_memory_detail_openssldeleter_test.cpp
  libs/meta/include/meta/type_traits.hpp
  libs/semanticsearch/include/semanticsearch/module/args_resolver.hpp
  libs/vectorise/include/vectorise/meta/math_type_traits.hpp
  libs/vectorise/include/vectorise/threading/pool.hpp
  libs/vm/include/vm/vm.hpp
Labels: S-ready-to-merge

#2398 Add default args support for FP128 Rand for consistency
  libs/vm-modules/src/math/random.cpp
Labels: S-ready-to-merge

#2388 Remove unnecessary inline specifiers
  apps/muddle-test-network/main.cpp
  libs/core/src/periodic_runnable.cpp
  libs/ledger/tests/chain/main_chain_service_tests.cpp
  libs/ml/include/ml/core/node.hpp
  libs/ml/include/ml/layers/fully_connected.hpp
  libs/ml/include/ml/layers/scaled_dot_product_attention.hpp
  libs/ml/include/ml/layers/skip_gram.hpp
  libs/ml/include/ml/ops/activations/relu.hpp
  libs/ml/include/ml/ops/ops.hpp
  libs/ml/include/ml/optimisation/adagrad_optimiser.hpp
  libs/ml/include/ml/optimisation/adam_optimiser.hpp
  libs/ml/include/ml/optimisation/lazy_adam_optimiser.hpp
  libs/ml/include/ml/optimisation/momentum_optimiser.hpp
  libs/ml/include/ml/optimisation/optimiser.hpp
  libs/ml/include/ml/optimisation/rmsprop_optimiser.hpp
  libs/ml/include/ml/optimisation/sgd_optimiser.hpp
  libs/oef-search/src/dap_manager/NodeExecutorFactory.cpp
  libs/shards/include/shards/manifest.hpp
  libs/shards/include/shards/manifest_entry.hpp
  libs/shards/include/shards/service_identifier.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_double.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_fixed32.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_fixed64.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_float.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_int16.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_int32.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_int64.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_int8.hpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
  libs/vectorise/include/vectorise/math/max.hpp
  libs/vectorise/include/vectorise/math/min.hpp
  libs/vectorise/include/vectorise/memory/parallel_dispatcher.hpp
  libs/vectorise/include/vectorise/register.hpp
  libs/vectorise/include/vectorise/uint/int.hpp
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/src/core/print.cpp
  libs/vm/include/vm/map.hpp
  libs/vm/include/vm/pair.hpp
Labels: S-ready-to-merge

#2411 Bugfix/fp32 vector multiplication fix
  libs/math/tests/unit/vectors/vector_tests.cpp
  libs/vectorise/include/vectorise/arch/avx2/register_fixed32.hpp
Labels: A-maths, C-bug, S-ready-to-merge

#2415 LGDR-630 Refactor/remove heaviest chain endpoint
  libs/ledger/include/ledger/protocols/main_chain_rpc_client.hpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_client_interface.hpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_protocol.hpp
  libs/ledger/src/protocols/main_chain_rpc_client.cpp
  libs/ledger/tests/unit/mock_main_chain_rpc_client.hpp
Labels: S-ready-to-merge

#2410 added charge estimations for layers
  libs/ml/include/ml/layers/PRelu.hpp
  libs/ml/include/ml/layers/convolution_1d.hpp
  libs/ml/include/ml/layers/convolution_2d.hpp
  libs/ml/include/ml/layers/multihead_attention.hpp
  libs/ml/include/ml/layers/scaled_dot_product_attention.hpp
  libs/ml/include/ml/layers/self_attention_encoder.hpp
  libs/ml/include/ml/layers/skip_gram.hpp
  libs/ml/src/layers/PRelu.cpp
  libs/ml/src/layers/convolution_1d.cpp
  libs/ml/src/layers/convolution_2d.cpp
  libs/ml/src/layers/multihead_attention.cpp
  libs/ml/src/layers/scaled_dot_product_attention.cpp
  libs/ml/src/layers/self_attention_encoder.cpp
  libs/ml/src/layers/skip_gram.cpp
Labels: S-ready-to-merge

#2417 added benchmarks for conv layers
  libs/vm-modules/benchmark/model/model.cpp
Labels: S-ready-to-merge

#2414 Model estimation functions moved from Estimator to VMModel
  libs/ml/include/ml/model/model.hpp
  libs/ml/include/ml/ops/ops.hpp
  libs/ml/src/model/model.cpp
  libs/ml/src/ops/abs.cpp
  libs/ml/src/ops/activations/dropout.cpp
  libs/ml/src/ops/activations/elu.cpp
  libs/ml/src/ops/activations/gelu.cpp
  libs/ml/src/ops/activations/leaky_relu.cpp
  libs/ml/src/ops/activations/logsigmoid.cpp
  libs/ml/src/ops/activations/logsoftmax.cpp
  libs/ml/src/ops/activations/randomised_relu.cpp
  libs/ml/src/ops/activations/relu.cpp
  libs/ml/src/ops/activations/sigmoid.cpp
  libs/ml/src/ops/activations/softmax.cpp
  libs/ml/src/ops/add.cpp
  libs/ml/src/ops/avg_pool_1d.cpp
  libs/ml/src/ops/avg_pool_2d.cpp
  libs/ml/src/ops/concatenate.cpp
  libs/ml/src/ops/constant.cpp
  libs/ml/src/ops/convolution_1d.cpp
  libs/ml/src/ops/convolution_2d.cpp
  libs/ml/src/ops/dataholder.cpp
  libs/ml/src/ops/divide.cpp
  libs/ml/src/ops/embeddings.cpp
  libs/ml/src/ops/exp.cpp
  libs/ml/src/ops/flatten.cpp
  libs/ml/src/ops/layer_norm.cpp
  libs/ml/src/ops/log.cpp
  libs/ml/src/ops/loss_functions/cross_entropy_loss.cpp
  libs/ml/src/ops/loss_functions/mean_square_error_loss.cpp
  libs/ml/src/ops/loss_functions/softmax_cross_entropy_loss.cpp
  libs/ml/src/ops/mask_fill.cpp
  libs/ml/src/ops/matrix_multiply.cpp
  libs/ml/src/ops/max_pool_1d.cpp
  libs/ml/src/ops/max_pool_2d.cpp
  libs/ml/src/ops/maximum.cpp
  libs/ml/src/ops/metrics/categorical_accuracy.cpp
  libs/ml/src/ops/multiply.cpp
  libs/ml/src/ops/one_hot.cpp
  libs/ml/src/ops/placeholder.cpp
  libs/ml/src/ops/prelu_op.cpp
  libs/ml/src/ops/reduce_mean.cpp
  libs/ml/src/ops/reshape.cpp
  libs/ml/src/ops/slice.cpp
  libs/ml/src/ops/sqrt.cpp
  libs/ml/src/ops/squeeze.cpp
  libs/ml/src/ops/strided_slice.cpp
  libs/ml/src/ops/subtract.cpp
  libs/ml/src/ops/tanh.cpp
  libs/ml/src/ops/top_k.cpp
  libs/ml/src/ops/transpose.cpp
  libs/ml/src/ops/variable.cpp
  libs/ml/src/ops/weights.cpp
  libs/vm-modules/benchmark/model/model.cpp
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/include/vm_modules/ml/model/model_estimator.hpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/src/ml/model/model_estimator.cpp
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
  libs/vm-modules/tests/unit/ml/model_estimator_tests.cpp
Labels: A-ml, A-vm, S-ready-to-merge

#2412 WIP: Feature/exp fp32 vectorisation
  libs/math/benchmark/CMakeLists.txt
  libs/math/benchmark/activation_functions/activations.cpp
  libs/math/include/math/standard_functions/exp.hpp
  libs/math/tests/unit/vectors/vector_tests.cpp
  libs/vectorise/include/vectorise/arch/avx2/math/exp.hpp
  libs/vectorise/include/vectorise/arch/avx2/math/standard_functions.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_fixed32.hpp
  libs/vectorise/include/vectorise/math/standard_functions.hpp
Labels: A-maths, C-optimisation, S-ready-to-merge

#2428 Feature/ml 523 moving tensor constructions to happen on graph compile
  libs/ml/include/ml/core/graph.hpp
  libs/ml/include/ml/core/subgraph.hpp
  libs/ml/include/ml/layers/convolution_1d.hpp
  libs/ml/include/ml/layers/convolution_2d.hpp
  libs/ml/include/ml/layers/fully_connected.hpp
  libs/ml/include/ml/ops/activations/dropout.hpp
  libs/ml/include/ml/ops/dataholder.hpp
  libs/ml/include/ml/ops/layer_norm.hpp
  libs/ml/include/ml/ops/ops.hpp
  libs/ml/include/ml/ops/slice.hpp
  libs/ml/include/ml/ops/variable.hpp
  libs/ml/include/ml/ops/weights.hpp
  libs/ml/include/ml/saveparams/saveable_params.hpp
  libs/ml/include/ml/serializers/ml_types.hpp
  libs/ml/src/core/graph.cpp
  libs/ml/src/core/node.cpp
  libs/ml/src/core/subgraph.cpp
  libs/ml/src/layers/convolution_1d.cpp
  libs/ml/src/layers/convolution_2d.cpp
  libs/ml/src/layers/fully_connected.cpp
  libs/ml/src/model/model.cpp
  libs/ml/src/ops/activations/dropout.cpp
  libs/ml/src/ops/dataholder.cpp
  libs/ml/src/ops/layer_norm.cpp
  libs/ml/src/ops/slice.cpp
  libs/ml/src/ops/variable.cpp
  libs/ml/tests/unit/graph/graph.cpp
  libs/ml/tests/unit/layers/PRelu.cpp
  libs/ml/tests/unit/layers/convolution_1d.cpp
  libs/ml/tests/unit/layers/convolution_2d.cpp
  libs/ml/tests/unit/layers/fully_connected.cpp
  libs/ml/tests/unit/layers/layer_norm.cpp
  libs/ml/tests/unit/layers/multihead_attention.cpp
  libs/ml/tests/unit/layers/scaled_dot_product_attention.cpp
  libs/ml/tests/unit/layers/self_attention_encoder.cpp
  libs/ml/tests/unit/ops/constant.cpp
  libs/ml/tests/unit/ops/placeholder.cpp
  libs/ml/tests/unit/optimisation/optimisers.cpp
  libs/ml/tests/unit/serializers/graph.cpp
  libs/ml/tests/unit/serializers/layers.cpp
  libs/ml/tests/unit/serializers/ops.cpp
  libs/ml/tests/unit/training/basic_training.cpp
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
Labels: S-ready-to-merge

#2419 Improvement/add not subtree txs to recent queue
  libs/chain/include/chain/transaction.hpp
  libs/chain/src/transaction.cpp
  libs/ledger/include/ledger/storage_unit/transaction_store_sync_service.hpp
  libs/ledger/src/storage_unit/transaction_store_sync_protocol.cpp
  libs/ledger/src/storage_unit/transaction_store_sync_service.cpp
Labels: A-ledger, C-improvement, S-ready-for-review, S-ready-to-merge

#2394 Update SDK version
  Pipfile
  Pipfile.lock
  scripts/end_to_end_test/smart_contract_tests/action_nonexistent_contract.py
  scripts/end_to_end_test/smart_contract_tests/balance.py
  scripts/end_to_end_test/smart_contract_tests/c2c_argument_passing_test.py
  scripts/end_to_end_test/smart_contract_tests/c2c_balance.py
  scripts/end_to_end_test/smart_contract_tests/c2c_call_cycle_test.py
  scripts/end_to_end_test/smart_contract_tests/c2c_multiple_calls.py
  scripts/end_to_end_test/smart_contract_tests/c2c_nested_call_depth_limit_test.py
  scripts/end_to_end_test/smart_contract_tests/c2c_nested_call_test.py
  scripts/end_to_end_test/smart_contract_tests/c2c_self_call_test.py
  scripts/end_to_end_test/smart_contract_tests/c2c_single_call_test.py
  scripts/end_to_end_test/smart_contract_tests/c2c_transfer.py
  scripts/end_to_end_test/smart_contract_tests/c2c_with_context_test.py
  scripts/end_to_end_test/smart_contract_tests/ledger_context.py
  scripts/end_to_end_test/smart_contract_tests/simple_state_test.py
  scripts/end_to_end_test/smart_contract_tests/synergetic_mining.py
  scripts/end_to_end_test/smart_contract_tests/transfer.py
Labels: S-ready-for-review, S-ready-to-merge

#2426 small fix removing the need to construct a new tensor dataloader on e…
  libs/vm-modules/src/ml/model/model.cpp
Labels: S-ready-to-merge

#2443 Decrease build concurrency on MacOS
  Jenkinsfile
Labels: S-ready-for-review

#2430 ML-519 Added charge estimation for dataloaders
  libs/ml/include/ml/dataloaders/tensor_dataloader.hpp
  libs/ml/src/dataloaders/tensor_dataloader.cpp
  libs/vm-modules/include/vm_modules/ml/dataloaders/dataloader.hpp
  libs/vm-modules/include/vm_modules/ml/utilities/conversion_utilities.hpp
  libs/vm-modules/src/ml/dataloaders/dataloader.cpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/src/ml/utilities/conversion_utilities.cpp
  libs/vm-modules/tests/unit/ml/dataloader_tests.cpp
  libs/vm-modules/tests/unit/ml/ml_estimator_tests.cpp
Labels: S-ready-to-merge

#2447 Fix startup bug for the fixed journal file
  libs/ledger/tests/CMakeLists.txt
  libs/ledger/tests/chain/main_chain_tests.cpp
  libs/ledger/tests/integration/main_chain_tests.cpp
  libs/storage/src/fixed_size_journal.cpp
  libs/storage/tests/unit/fixed_size_journal_file_tests.cpp
Labels: S-ready-to-merge

#2435 Removing references to commodity dataloader
  libs/ml/include/ml/meta/ml_type_traits.hpp
  libs/ml/include/ml/serializers/model.hpp
  libs/vm-modules/tests/unit/ml/ml.cpp
Labels: S-ready-to-merge

#2444 No return moves ep 2
  libs/ml/src/ops/weights.cpp
  libs/ml/src/utilities/sparse_tensor_utilities.cpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
Labels: S-ready-for-review, S-ready-to-merge

#2440 Fix copy-paste error in Variant serialiser
  libs/variant/include/variant/variant.hpp
Labels: S-ready-for-review, S-ready-to-merge

#2441 Remove empty statements
  libs/core/include/core/serializers/counter.hpp
  libs/core/src/serializers/main_serializer.cpp
  libs/crypto/tests/unit/openssl_BIGNUM_padding_test.cpp
  libs/ledger/src/protocols/main_chain_rpc_service.cpp
  libs/math/include/math/distance/hamming.hpp
  libs/math/tests/unit/activation_functions/relu.cpp
  libs/ml/src/ops/embeddings.cpp
  libs/ml/src/ops/strided_slice.cpp
  libs/oef-base/include/oef-base/conversation/OutboundEndpoint.hpp
  libs/oef-base/src/monitoring/Monitoring.cpp
  libs/oef-core/src/karma/KarmaPolicyBasic.cpp
  libs/python/include/python/crypto/ecdsa.hpp
  libs/python/include/python/crypto/fnv.hpp
  libs/python/include/python/crypto/sha256.hpp
  libs/python/include/python/json/document.hpp
  libs/python/include/python/json/exceptions.hpp
  libs/python/include/python/network/network_manager.hpp
  libs/variant/include/variant/variant.hpp
Labels: S-ready-for-review, S-ready-to-merge

#2432 implemented mnist training test, and unified mnist example/test utili…
  libs/ml/examples/mnist_model/main.cpp
  libs/ml/include/ml/utilities/mnist_utilities.hpp
  libs/ml/tests/CMakeLists.txt
  libs/ml/tests/integration/mnist/mnist.cpp
  libs/ml/tests/integration/training/basic_training.cpp
Labels: S-ready-to-merge

#2452 rewrite the bloom search logic due to possible bug
  libs/ledger/include/ledger/chain/main_chain.hpp
  libs/ledger/src/chain/main_chain.cpp
Labels: S-ready-to-merge

#2453 Guarantee no writes after socket closure
  libs/http/include/http/connection.hpp
Labels: S-ready-to-merge

#2433 performance improvement tidy
  libs/ledger/include/ledger/storage_unit/transaction_store_sync_service.hpp
  libs/ledger/src/storage_unit/transaction_store_sync_service.cpp
  libs/storage/include/storage/seen_recently_cache.hpp
  libs/storage/tests/unit/have_recently_seen_cache_tests.cpp
Labels: S-ready-to-merge

#2454 fix possible segv in main chain when modifing iterator
  libs/ledger/src/chain/main_chain.cpp
Labels: S-ready-to-merge

#2436 Feature/ml 472 vm modules boston house prices
  libs/vm-modules/examples/boston_house_prices/main.cpp
  libs/vm-modules/include/vm_modules/scripts/ml/boston_house_prices.hpp
  libs/vm-modules/include/vm_modules/test_utilities/fake_io_observer.hpp
  libs/vm-modules/include/vm_modules/test_utilities/mock_io_observer.hpp
  libs/vm-modules/include/vm_modules/test_utilities/vm_test_toolkit.hpp
  libs/vm-modules/src/scripts/ml/boston_house_prices.cpp
  libs/vm-modules/src/test_utilities/fake_io_observer.cpp
  libs/vm-modules/tests/CMakeLists.txt
  libs/vm-modules/tests/integration/ml/boston_house_prices.cpp
  libs/vm-modules/tests/unit/array_tests.cpp
  libs/vm-modules/tests/unit/core_language/annotation_tests.cpp
  libs/vm-modules/tests/unit/core_language/comments_tests.cpp
  libs/vm-modules/tests/unit/core_language/core_etch_tests.cpp
  libs/vm-modules/tests/unit/custom_binding_tests.cpp
  libs/vm-modules/tests/unit/fixed_point.cpp
  libs/vm-modules/tests/unit/initializer_list_tests.cpp
  libs/vm-modules/tests/unit/math/big_number_wrapper_tests.cpp
  libs/vm-modules/tests/unit/math/math.cpp
  libs/vm-modules/tests/unit/math/tensor_estimator_tests.cpp
  libs/vm-modules/tests/unit/math/tensor_tests.cpp
  libs/vm-modules/tests/unit/ml/ml.cpp
  libs/vm-modules/tests/unit/ml/ml_estimator_tests.cpp
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
  libs/vm-modules/tests/unit/ml_scaler_tests.cpp
  libs/vm-modules/tests/unit/ops_tests.cpp
  libs/vm-modules/tests/unit/pair_tests.cpp
  libs/vm-modules/tests/unit/print_tests.cpp
  libs/vm-modules/tests/unit/state_tests.cpp
  libs/vm-modules/tests/unit/string_tests.cpp
  libs/vm-modules/tests/unit/system.cpp
  libs/vm-modules/tests/unit/vm_charge_tests.cpp
Labels: S-ready-to-merge

#2446 add telemetry to muddle register
  libs/muddle/internal/muddle_register.hpp
  libs/muddle/src/muddle_register.cpp
  libs/telemetry/src/registry.cpp
Labels: S-ready-to-merge

#2456 Detect Genesis Mismatch
  libs/ledger/include/ledger/protocols/main_chain_rpc_service.hpp
  libs/ledger/src/protocols/main_chain_rpc_service.cpp
  libs/ledger/tests/sync/main_chain_sync_test.cpp
Labels: A-ledger, C-improvement, S-ready-for-review

#2457 Added benchmarks for AdamOptimiser
  libs/ml/benchmark/CMakeLists.txt
  libs/ml/benchmark/optimisation/optimisation.cpp
  libs/ml/src/optimisation/adam_optimiser.cpp
  libs/ml/src/optimisation/sgd_optimiser.cpp
  libs/vm-modules/tests/unit/ml/model_estimator_tests.cpp
Labels: S-ready-to-merge
