Repository fetchai/ledger, pull requests merged in 2020-03, with the labels that each got.

#2462 ML-528 Adding shapes to ChargeBackwards
  libs/ml/include/ml/core/node.hpp
  libs/ml/include/ml/core/subgraph.hpp
  libs/ml/include/ml/layers/PRelu.hpp
  libs/ml/include/ml/layers/convolution_1d.hpp
  libs/ml/include/ml/layers/convolution_2d.hpp
  libs/ml/include/ml/layers/fully_connected.hpp
  libs/ml/include/ml/layers/multihead_attention.hpp
  libs/ml/include/ml/layers/scaled_dot_product_attention.hpp
  libs/ml/include/ml/layers/self_attention_encoder.hpp
  libs/ml/include/ml/layers/skip_gram.hpp
  libs/ml/include/ml/ops/ops.hpp
  libs/ml/src/core/graph.cpp
  libs/ml/src/core/node.cpp
  libs/ml/src/core/subgraph.cpp
  libs/ml/src/layers/PRelu.cpp
  libs/ml/src/layers/convolution_1d.cpp
  libs/ml/src/layers/convolution_2d.cpp
  libs/ml/src/layers/fully_connected.cpp
  libs/ml/src/layers/multihead_attention.cpp
  libs/ml/src/layers/scaled_dot_product_attention.cpp
  libs/ml/src/layers/self_attention_encoder.cpp
  libs/ml/src/layers/skip_gram.cpp
  libs/ml/tests/unit/graph/graph.cpp
Labels: S-ready-to-merge

#2466 Add builder to ContractContext
  libs/ledger/benchmark/executor_bench.cpp
  libs/ledger/include/ledger/chaincode/contract_context.hpp
  libs/ledger/include/ledger/upow/synergetic_contract.hpp
  libs/ledger/src/chaincode/contract_context.cpp
  libs/ledger/src/chaincode/contract_http_interface.cpp
  libs/ledger/src/chaincode/smart_contract.cpp
  libs/ledger/src/chaincode/smart_contract_manager.cpp
  libs/ledger/src/executor.cpp
  libs/ledger/src/fees/fee_manager.cpp
  libs/ledger/src/transaction_validator.cpp
  libs/ledger/src/upow/naive_synergetic_miner.cpp
  libs/ledger/src/upow/synergetic_contract.cpp
  libs/ledger/src/upow/synergetic_executor.cpp
  libs/ledger/tests/chaincode/contract_test.hpp
  libs/ledger/tests/unit/transaction_validator_tests.cpp
  libs/vm-modules/include/vm_modules/ledger/balance.hpp
  libs/vm-modules/include/vm_modules/ledger/transfer_function.hpp
Labels: S-ready-to-merge

#2470 Replace shared_ptr with unique_ptr
  libs/ledger/include/ledger/chaincode/chain_code_factory.hpp
  libs/ledger/src/chaincode/chain_code_factory.cpp
Labels: S-ready-to-merge

#2471 VM Return instruction bugfix
  libs/vm/src/parser.cpp
  libs/vm/src/vm_handlers.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2448 Refactor/ml 525 fine tune coefs flatten
  libs/ml/benchmark/ops/ops.cpp
  libs/ml/include/ml/charge_estimation/ops/constants.hpp
  libs/ml/src/ops/flatten.cpp
  libs/ml/tests/unit/graph/graph.cpp
  libs/ml/tests/unit/model/sequential_test.cpp
  libs/vm-modules/tests/unit/ml/model_estimator_tests.cpp
Labels: S-ready-to-merge

#2450 Add finetuning
  libs/math/benchmark/tensor/tensor.cpp
  libs/math/include/math/charge_estimation/constants.hpp
  libs/math/src/tensor/tensor.cpp
  libs/ml/benchmark/ops/ops.cpp
  libs/ml/include/ml/charge_estimation/ops/constants.hpp
  libs/ml/include/ml/ops/flatten.hpp
  libs/ml/src/ops/add.cpp
  libs/ml/src/ops/avg_pool_1d.cpp
  libs/ml/src/ops/avg_pool_2d.cpp
  libs/ml/src/ops/embeddings.cpp
  libs/ml/src/ops/flatten.cpp
  libs/ml/src/ops/matrix_multiply.cpp
  libs/ml/tests/unit/graph/graph.cpp
  libs/ml/tests/unit/model/sequential_test.cpp
  libs/vm-modules/tests/unit/ml/model_estimator_tests.cpp
Labels: A-ml, A-vm, S-ready-for-review

#2458 Loss functions tuning
  libs/math/benchmark/basic_math/basic_math.cpp
  libs/math/benchmark/basic_math/square_distance.cpp
  libs/math/benchmark/tensor/tensor.cpp
  libs/ml/benchmark/loss_functions/loss_functions.cpp
  libs/ml/benchmark/ops/ops.cpp
  libs/ml/include/ml/charge_estimation/ops/constants.hpp
  libs/ml/include/ml/ops/loss_functions/cross_entropy_loss.hpp
  libs/ml/include/ml/ops/loss_functions/mean_square_error_loss.hpp
  libs/ml/include/ml/ops/multiply.hpp
  libs/ml/src/ops/activations/dropout.cpp
  libs/ml/src/ops/convolution_1d.cpp
  libs/ml/src/ops/convolution_2d.cpp
  libs/ml/src/ops/exp.cpp
  libs/ml/src/ops/loss_functions/cross_entropy_loss.cpp
  libs/ml/src/ops/loss_functions/mean_square_error_loss.cpp
  libs/ml/src/ops/mask_fill.cpp
  libs/ml/src/ops/matrix_multiply.cpp
  libs/ml/src/ops/multiply.cpp
  libs/ml/src/ops/subtract.cpp
  libs/ml/tests/unit/graph/graph.cpp
  libs/ml/tests/unit/model/sequential_test.cpp
  libs/vm-modules/benchmark/model/model.cpp
  libs/vm-modules/benchmark/tensor/tensor.cpp
  libs/vm-modules/tests/unit/ml/model_estimator_tests.cpp
Labels: S-ready-to-merge

#2474 Bugfix/ml 527 charge compile fix
  libs/ml/src/core/graph.cpp
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/tests/unit/ml/model_estimator_tests.cpp
Labels: S-ready-to-merge

#2463 LGDR-733 Bug/telemetry uniqueness
  libs/core/include/core/state_machine.hpp
  libs/core/src/periodic_runnable.cpp
  libs/telemetry/CMakeLists.txt
  libs/telemetry/include/telemetry/registry.hpp
  libs/telemetry/src/registry.cpp
  libs/telemetry/tests/unit/registry_tests.cpp
Labels: A-core, C-bug, S-ready-for-review, S-ready-to-merge

#2465 ML-530 Fine-tuning charge estimation for tensor dataloader
  libs/ml/benchmark/CMakeLists.txt
  libs/ml/benchmark/dataloaders/dataloaders.cpp
  libs/ml/include/ml/charge_estimation/dataloaders/constants.hpp
  libs/ml/src/dataloaders/tensor_dataloader.cpp
  libs/vm-modules/tests/unit/ml/dataloader_tests.cpp
Labels: S-ready-to-merge

#2438 Backport/no recent subtree txs
  libs/chain/include/chain/transaction.hpp
  libs/chain/src/transaction.cpp
  libs/ledger/include/ledger/storage_unit/transaction_store_sync_service.hpp
  libs/ledger/src/storage_unit/transaction_store_sync_protocol.cpp
  libs/ledger/src/storage_unit/transaction_store_sync_service.cpp
Labels: S-ready-to-merge
