Repository fetchai/ledger, pull requests merged in 2020-01, with the labels that each got.

#2253 Refactor/ml 391 reducing rebuild impact of tensor
  libs/math/benchmark/tensor/tensor.cpp
  libs/math/include/math/activation_functions/softmax.hpp
  libs/math/include/math/fundamental_operators.hpp
  libs/math/include/math/matrix_operations.hpp
  libs/math/include/math/metrics/l2_loss.hpp
  libs/math/include/math/metrics/l2_norm.hpp
  libs/math/include/math/standard_functions/abs.hpp
  libs/math/include/math/standard_functions/pow.hpp
  libs/math/include/math/tensor/tensor.hpp
  libs/math/src/tensor/tensor.cpp
  libs/math/tests/unit/distance/pairwise_distance.cpp
  libs/math/tests/unit/fixed_point/fixed_point.cpp
  libs/math/tests/unit/tensor/l2loss.cpp
  libs/math/tests/unit/tensor/tensor_operations.cpp
  libs/math/tests/unit/tensor_iterator/iterator.cpp
  libs/ml/include/ml/clustering/tsne.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/sgns_w2v_dataloader.hpp
  libs/ml/include/ml/ops/abs.hpp
  libs/ml/include/ml/ops/activations/softmax.hpp
  libs/ml/include/ml/ops/add.hpp
  libs/ml/include/ml/ops/exp.hpp
  libs/ml/include/ml/ops/layer_norm.hpp
  libs/ml/include/ml/ops/metrics/categorical_accuracy.hpp
  libs/ml/include/ml/ops/sqrt.hpp
  libs/ml/include/ml/ops/weights.hpp
  libs/ml/include/ml/utilities/word2vec_utilities.hpp
  libs/ml/tests/unit/ops/activations/randomised_relu.cpp
  libs/vectorise/include/vectorise/memory/parallel_dispatcher.hpp
Labels: S-ready-for-review, S-ready-to-merge

#2247 benchmarck for categorical accuracy
  libs/ml/benchmark/CMakeLists.txt
  libs/ml/benchmark/metrics/metrics.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2250 Combined Port of Release branches fixes
  apps/constellation/config_builder.cpp
  apps/constellation/main.cpp
  libs/beacon/include/beacon/beacon_service.hpp
  libs/beacon/include/beacon/beacon_setup_service.hpp
  libs/beacon/src/beacon_service.cpp
  libs/beacon/src/beacon_setup_service.cpp
  libs/constellation/include/constellation/constellation.hpp
  libs/constellation/src/constellation.cpp
  libs/core/include/core/serializers/base_types.hpp
  libs/http/src/https_client.cpp
  libs/ledger/include/ledger/chain/block_coordinator.hpp
  libs/ledger/include/ledger/chain/main_chain.hpp
  libs/ledger/include/ledger/consensus/consensus.hpp
  libs/ledger/include/ledger/genesis_loading/genesis_file_creator.hpp
  libs/ledger/include/ledger/miner/annealer_miner.hpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_service.hpp
  libs/ledger/include/ledger/storage_unit/transaction_store_sync_protocol.hpp
  libs/ledger/include/ledger/storage_unit/transaction_store_sync_service.hpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/src/chaincode/token_contract.cpp
  libs/ledger/src/consensus/consensus.cpp
  libs/ledger/src/genesis_file_creator.cpp
  libs/ledger/src/protocols/main_chain_rpc_service.cpp
  libs/ledger/src/storage_unit/storage_unit_client.cpp
  libs/ledger/src/storage_unit/transaction_store_sync_protocol.cpp
  libs/ledger/src/storage_unit/transaction_store_sync_service.cpp
  libs/ledger/tests/chaincode/token_contract_tests.cpp
  libs/ledger/tests/consensus/pos_tests.cpp
  libs/muddle/tests/integration/peer_table_desired_recovery.cpp
  libs/muddle/tests/integration/peer_table_reboot.cpp
  libs/network/include/network/service/promise.hpp
  libs/network/include/network/uri.hpp
  libs/network/src/service/promise.cpp
  libs/shards/include/shards/service_identifier.hpp
  libs/shards/src/service_identifier.cpp
  libs/storage/include/storage/new_versioned_random_access_stack.hpp
  scripts/end_to_end_test/run_end_to_end_test.py
  scripts/fetchai_netutils/fetch/cluster/instance.py
  scripts/fetchai_netutils/fetch/testing/testcase.py
  scripts/fetchai_netutils/setup.py
  scripts/generate-genesis-file.py
Labels: S-ready-for-review

#2258 ML-290: added reshape layer binding
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/include/vm_modules/ml/model/model_estimator.hpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/src/ml/model/model_estimator.cpp
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2259 Refactor/ml 418 move ml ops implementations to source files (A->C)
  .gitignore
  libs/math/include/math/matrix_operations.hpp
  libs/ml/include/ml/ops/abs.hpp
  libs/ml/include/ml/ops/activation.hpp
  libs/ml/include/ml/ops/add.hpp
  libs/ml/include/ml/ops/avg_pool_1d.hpp
  libs/ml/include/ml/ops/avg_pool_2d.hpp
  libs/ml/include/ml/ops/concatenate.hpp
  libs/ml/include/ml/ops/constant.hpp
  libs/ml/include/ml/ops/convolution_1d.hpp
  libs/ml/include/ml/ops/convolution_2d.hpp
  libs/ml/include/ml/utilities/graph_builder.hpp
  libs/ml/src/ops/abs.cpp
  libs/ml/src/ops/activation.cpp
  libs/ml/src/ops/add.cpp
  libs/ml/src/ops/avg_pool_1d.cpp
  libs/ml/src/ops/avg_pool_2d.cpp
  libs/ml/src/ops/concatenate.cpp
  libs/ml/src/ops/constant.cpp
  libs/ml/src/ops/convolution_1d.cpp
  libs/ml/src/ops/convolution_2d.cpp
  libs/ml/tests/unit/ops/abs.cpp
  libs/ml/tests/unit/ops/activations/dropout.cpp
  libs/ml/tests/unit/ops/activations/gelu.cpp
  libs/ml/tests/unit/ops/activations/leaky_relu.cpp
  libs/ml/tests/unit/ops/activations/logsigmoid.cpp
  libs/ml/tests/unit/ops/activations/logsoftmax.cpp
  libs/ml/tests/unit/ops/activations/randomised_relu.cpp
  libs/ml/tests/unit/ops/activations/relu.cpp
  libs/ml/tests/unit/ops/activations/sigmoid.cpp
  libs/ml/tests/unit/ops/activations/softmax.cpp
  libs/ml/tests/unit/ops/concatenate.cpp
  libs/ml/tests/unit/ops/constant.cpp
  libs/ml/tests/unit/serializers/ml_types.cpp
  libs/ml/tests/unit/training/basic_training.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2263 Refactor/ml 419 move ml ops implementation to source files ops D-L
  libs/ml/examples/word2vec_SGNS_dataloader/main.cpp
  libs/ml/include/ml/ops/abs.hpp
  libs/ml/include/ml/ops/add.hpp
  libs/ml/include/ml/ops/avg_pool_1d.hpp
  libs/ml/include/ml/ops/avg_pool_2d.hpp
  libs/ml/include/ml/ops/constant.hpp
  libs/ml/include/ml/ops/dataholder.hpp
  libs/ml/include/ml/ops/divide.hpp
  libs/ml/include/ml/ops/embeddings.hpp
  libs/ml/include/ml/ops/exp.hpp
  libs/ml/include/ml/ops/flatten.hpp
  libs/ml/include/ml/ops/layer_norm.hpp
  libs/ml/include/ml/ops/log.hpp
  libs/ml/include/ml/ops/loss_functions.hpp
  libs/ml/include/ml/ops/weights.hpp
  libs/ml/include/ml/regularisers/l1_regulariser.hpp
  libs/ml/include/ml/regularisers/l2_regulariser.hpp
  libs/ml/include/ml/utilities/graph_builder.hpp
  libs/ml/src/ops/abs.cpp
  libs/ml/src/ops/add.cpp
  libs/ml/src/ops/avg_pool_1d.cpp
  libs/ml/src/ops/avg_pool_2d.cpp
  libs/ml/src/ops/dataholder.cpp
  libs/ml/src/ops/divide.cpp
  libs/ml/src/ops/embeddings.cpp
  libs/ml/src/ops/exp.cpp
  libs/ml/src/ops/flatten.cpp
  libs/ml/src/ops/layer_norm.cpp
  libs/ml/src/ops/log.cpp
  libs/ml/tests/unit/layers/fully_connected.cpp
  libs/ml/tests/unit/layers/scaled_dot_product_attention.cpp
  libs/ml/tests/unit/optimisation/optimisers.cpp
  libs/ml/tests/unit/optimisation/sparse_optimisers.cpp
  libs/ml/tests/unit/training/basic_training.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2264 Refactor/ml 422 move ml ops implementation to source files ops t w
  libs/math/include/math/fundamental_operators.hpp
  libs/math/include/math/kernels/trigonometry.hpp
  libs/ml/include/ml/core/graph.hpp
  libs/ml/include/ml/ops/tanh.hpp
  libs/ml/include/ml/ops/top_k.hpp
  libs/ml/include/ml/ops/trainable.hpp
  libs/ml/include/ml/ops/transpose.hpp
  libs/ml/include/ml/ops/variable.hpp
  libs/ml/include/ml/ops/weights.hpp
  libs/ml/include/ml/state_dict.hpp
  libs/ml/src/ops/tanh.cpp
  libs/ml/src/ops/top_k.cpp
  libs/ml/src/ops/trainable.cpp
  libs/ml/src/ops/transpose.cpp
  libs/ml/src/ops/variable.cpp
  libs/ml/src/ops/weights.cpp
  libs/ml/tests/unit/ops/tanh.cpp
  libs/ml/tests/unit/ops/weights.cpp
  libs/ml/tests/unit/state/state_dict.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2266 Refactor/ml 421 move ml ops implementation to source files ops p s
  libs/math/include/math/fundamental_operators.hpp
  libs/ml/include/ml/ops/placeholder.hpp
  libs/ml/include/ml/ops/prelu_op.hpp
  libs/ml/include/ml/ops/reduce_mean.hpp
  libs/ml/include/ml/ops/reshape.hpp
  libs/ml/include/ml/ops/slice.hpp
  libs/ml/include/ml/ops/sqrt.hpp
  libs/ml/include/ml/ops/squeeze.hpp
  libs/ml/include/ml/ops/strided_slice.hpp
  libs/ml/src/ops/placeholder.cpp
  libs/ml/src/ops/prelu_op.cpp
  libs/ml/src/ops/reduce_mean.cpp
  libs/ml/src/ops/reshape.cpp
  libs/ml/src/ops/slice.cpp
  libs/ml/src/ops/sqrt.cpp
  libs/ml/src/ops/squeeze.cpp
  libs/ml/src/ops/strided_slice.cpp
Labels: S-ready-to-merge

#2268 Refactor/ml 417 move ml ops metrics implementation to source files
  libs/math/include/math/fundamental_operators.hpp
  libs/ml/include/ml/ops/metrics/categorical_accuracy.hpp
  libs/ml/src/ops/metrics/categorical_accuracy.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2269 Refactor/ml 416 move ml ops loss functions implementations to source files
  libs/math/include/math/distance/square.hpp
  libs/math/include/math/fundamental_operators.hpp
  libs/math/include/math/metrics/cross_entropy.hpp
  libs/ml/include/ml/ops/loss_functions/cross_entropy_loss.hpp
  libs/ml/include/ml/ops/loss_functions/mean_square_error_loss.hpp
  libs/ml/include/ml/ops/loss_functions/softmax_cross_entropy_loss.hpp
  libs/ml/include/ml/utilities/bert_utilities.hpp
  libs/ml/src/ops/loss_functions/cross_entropy_loss.cpp
  libs/ml/src/ops/loss_functions/mean_square_error_loss.cpp
  libs/ml/src/ops/loss_functions/softmax_cross_entropy_loss.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2270 Added more VMPair tests
  libs/vm-modules/tests/unit/pair_tests.cpp
Labels: A-vm, S-ready-for-review, S-ready-to-merge

#2267 Improvement/noexcept mainchain
  libs/ledger/include/ledger/chain/time_travelogue.hpp
  libs/ledger/src/chain/main_chain.cpp
Labels: S-ready-to-merge

#2272 Pair serialisation fixed and tests added
  libs/core/include/core/serializers/base_types.hpp
  libs/vm-modules/tests/unit/parameter_serialization.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2271 Refactor/ml 415 move ml ops activations implementations to source files
  libs/math/include/math/activation_functions/sigmoid.hpp
  libs/math/include/math/kernels/trigonometry.hpp
  libs/math/include/math/standard_functions/pow.hpp
  libs/ml/include/ml/ops/activations/dropout.hpp
  libs/ml/include/ml/ops/activations/elu.hpp
  libs/ml/include/ml/ops/activations/gelu.hpp
  libs/ml/include/ml/ops/activations/leaky_relu.hpp
  libs/ml/include/ml/ops/activations/logsigmoid.hpp
  libs/ml/include/ml/ops/activations/logsoftmax.hpp
  libs/ml/include/ml/ops/activations/randomised_relu.hpp
  libs/ml/include/ml/ops/activations/relu.hpp
  libs/ml/include/ml/ops/activations/sigmoid.hpp
  libs/ml/include/ml/ops/activations/softmax.hpp
  libs/ml/include/ml/optimisation/optimiser.hpp
  libs/ml/src/ops/activations/dropout.cpp
  libs/ml/src/ops/activations/elu.cpp
  libs/ml/src/ops/activations/gelu.cpp
  libs/ml/src/ops/activations/leaky_relu.cpp
  libs/ml/src/ops/activations/logsigmoid.cpp
  libs/ml/src/ops/activations/logsoftmax.cpp
  libs/ml/src/ops/activations/randomised_relu.cpp
  libs/ml/src/ops/activations/relu.cpp
  libs/ml/src/ops/activations/sigmoid.cpp
  libs/ml/src/ops/activations/softmax.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2279 Remove duplicate copyright
  libs/oef-base/include/oef-base/comms/Listener.hpp
Labels: S-ready-to-merge

#2278 Remove duplicate copyright
  libs/oef-base/include/oef-base/comms/Listener.hpp
Labels: S-ready-to-merge

#2274 Do not trim cabinet history after reversion
  libs/ledger/src/consensus/consensus.cpp
  libs/ledger/tests/consensus/pos_tests.cpp
  libs/ledger/tests/notarisation/notarisation_tests.cpp
Labels: S-ready-to-merge

#2282 Feature/ml 379 benchmark loss functions
  libs/ml/benchmark/CMakeLists.txt
  libs/ml/benchmark/loss_functions/loss_functions.cpp
  libs/ml/src/ops/loss_functions/softmax_cross_entropy_loss.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2285 moved tsne implementation to source
  libs/math/include/math/tensor/tensor.hpp
  libs/ml/include/ml/clustering/tsne.hpp
  libs/ml/src/clustering/tsne.cpp
Labels: S-ready-to-merge

#2277 Feature/ml 381 benchmark ops
  libs/ml/benchmark/ops/ops.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2262 ML-442: empty constructor binding
  libs/vm-modules/include/vm_modules/math/tensor/tensor.hpp
  libs/vm-modules/src/math/tensor/tensor.cpp
  libs/vm-modules/tests/unit/math/tensor_tests.cpp
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2297 Cherry-pick release branch bug fixes
  apps/constellation/config_builder.cpp
  libs/constellation/src/constellation.cpp
  libs/ledger/include/ledger/chain/main_chain.hpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/tests/chain/main_chain_tests.cpp
  libs/network/include/network/p2pservice/p2p_http_interface.hpp
Labels: S-ready-to-merge

#2307 Remove dataloader floats
  libs/dmlf/examples/boston_housing_distributed_learning/main.cpp
  libs/dmlf/examples/boston_housing_multiprocess_distributed_learning/main.cpp
  libs/dmlf/examples/mnist_distributed_learning/main.cpp
  libs/dmlf/examples/mnist_multiprocess_distributed_learning/main.cpp
  libs/dmlf/include/dmlf/collective_learning/client_algorithm.hpp
  libs/dmlf/include/dmlf/collective_learning/utilities/boston_housing_client_utilities.hpp
  libs/dmlf/include/dmlf/collective_learning/utilities/mnist_client_utilities.hpp
  libs/ml/examples/code2vec/main.cpp
  libs/ml/examples/code2vec_dataloading/main.cpp
  libs/ml/examples/commodity_prediction/main.cpp
  libs/ml/examples/crypto_price_prediction/main.cpp
  libs/ml/examples/mnist/main.cpp
  libs/ml/examples/mnist_model/main.cpp
  libs/ml/examples/tsne/main.cpp
  libs/ml/include/ml/dataloaders/code2vec_context_loaders/context_loader.hpp
  libs/ml/include/ml/dataloaders/dataloader.hpp
  libs/ml/include/ml/dataloaders/tensor_dataloader.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/sgns_w2v_dataloader.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/w2v_dataloader.hpp
  libs/ml/include/ml/model/model.hpp
  libs/ml/include/ml/optimisation/optimiser.hpp
  libs/ml/tests/unit/dataloader/code2vec_context_loader.cpp
  libs/ml/tests/unit/dataloader/tensor_dataloader.cpp
  libs/ml/tests/unit/model/dnn_classifier_test.cpp
  libs/ml/tests/unit/model/dnn_regressor_test.cpp
  libs/ml/tests/unit/model/sequential_test.cpp
  libs/vm-modules/include/vm_modules/ml/dataloaders/dataloader.hpp
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/include/vm_modules/ml/optimisation/optimiser.hpp
  libs/vm-modules/src/ml/dataloaders/dataloader.cpp
Labels: S-ready-to-merge

#2281 ML-420: move templated ops...M-O
  libs/math/include/math/one_hot.hpp
  libs/ml/include/ml/ops/mask_fill.hpp
  libs/ml/include/ml/ops/matrix_multiply.hpp
  libs/ml/include/ml/ops/max_pool.hpp
  libs/ml/include/ml/ops/max_pool_1d.hpp
  libs/ml/include/ml/ops/max_pool_2d.hpp
  libs/ml/include/ml/ops/maximum.hpp
  libs/ml/include/ml/ops/multiply.hpp
  libs/ml/include/ml/ops/one_hot.hpp
  libs/ml/src/ops/mask_fill.cpp
  libs/ml/src/ops/matrix_multiply.cpp
  libs/ml/src/ops/max_pool.cpp
  libs/ml/src/ops/max_pool_1d.cpp
  libs/ml/src/ops/max_pool_2d.cpp
  libs/ml/src/ops/maximum.cpp
  libs/ml/src/ops/multiply.cpp
  libs/ml/src/ops/one_hot.cpp
  libs/ml/tests/unit/ops/max_pool.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2288 Dropout keep prob replaced with drop prop
  libs/ml/examples/bert_simple_cls_example/main.cpp
  libs/ml/examples/commodity_prediction/main.cpp
  libs/ml/include/ml/layers/multihead_attention.hpp
  libs/ml/include/ml/layers/scaled_dot_product_attention.hpp
  libs/ml/include/ml/layers/self_attention_encoder.hpp
  libs/ml/include/ml/utilities/bert_utilities.hpp
  libs/ml/src/ops/activations/dropout.cpp
  libs/ml/tests/unit/layers/scaled_dot_product_attention.cpp
  libs/ml/tests/unit/ops/activations/dropout.cpp
  libs/vm-modules/examples/commodity_prediction/script/commodity_prediction.etch
  libs/vm-modules/examples/commodity_prediction/script/graph_saver.etch
  libs/vm-modules/src/ml/model/model.cpp
Labels: A-ml, S-ready-to-merge

#2276 Feature/ml 185 vectorise trivial functions
  libs/math/include/math/matrix_operations.hpp
  libs/math/tests/unit/vectors/vector_tests.cpp
  libs/vectorise/benchmarks/parallel_dispatcher/abs_bench.cpp
  libs/vectorise/include/vectorise/arch/avx2/math/abs.hpp
  libs/vectorise/include/vectorise/arch/avx2/math/max.hpp
  libs/vectorise/include/vectorise/arch/avx2/math/min.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_double.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_fixed32.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_fixed64.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_float.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_int32.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_int64.hpp
  libs/vectorise/include/vectorise/fixed_point/type_traits.hpp
  libs/vectorise/include/vectorise/math/max.hpp
  libs/vectorise/include/vectorise/math/standard_functions.hpp
  libs/vectorise/include/vectorise/memory/parallel_dispatcher.hpp
  libs/vectorise/include/vectorise/register.hpp
  libs/vectorise/include/vectorise/vectorise.hpp
Labels: A-maths, C-optimisation, S-ready-for-review, S-ready-to-merge

#2295 Test annotations for tooling.
  apps/etch/main.cpp
  libs/vm/include/vm/analyser.hpp
  libs/vm/include/vm/module.hpp
  libs/vm/src/analyser.cpp
  libs/vm/src/compiler.cpp
Labels: S-ready-to-merge

#2290 Deprecated DNNClassifier and DNNRegressor
  libs/ml/examples/mnist_model/main.cpp
  libs/ml/include/ml/model/dnn_classifier.hpp
  libs/ml/include/ml/model/dnn_regressor.hpp
  libs/ml/tests/unit/model/dnn_classifier_test.cpp
  libs/ml/tests/unit/model/dnn_regressor_test.cpp
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/include/vm_modules/ml/model/model_estimator.hpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/src/ml/model/model_estimator.cpp
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
  libs/vm-modules/tests/unit/ml/model_estimator_tests.cpp
  scripts/experimental-etch-language-tests/ml/model/regressor.etch
  scripts/experimental-etch-language-tests/ml/model/sequential.etch
Labels: A-ml, A-vm, S-ready-for-review, S-ready-to-merge

#2286 Restoring `-standalone` for PoS
  apps/constellation/config_builder.cpp
  apps/constellation/settings.cpp
  apps/constellation/settings.hpp
  libs/beacon/src/beacon_service.cpp
  libs/beacon/src/beacon_setup_service.cpp
  libs/constellation/src/constellation.cpp
  libs/http/include/http/http_connection_manager.hpp
  libs/http/src/http_connection_manager.cpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/consensus/consensus.cpp
  libs/ledger/src/genesis_file_creator.cpp
Labels: S-ready-for-review

#2296 Remove redundant static qualifiers
  libs/ledger/tests/chain/main_chain_tests.cpp
Labels: S-ready-to-merge

#2294 VMTensor string constructor with charge estimate, benchmarks and tests
  libs/math/src/tensor/tensor.cpp
  libs/vm-modules/benchmark/tensor/tensor.cpp
  libs/vm-modules/include/vm_modules/math/tensor/tensor.hpp
  libs/vm-modules/src/math/tensor/tensor.cpp
  libs/vm-modules/tests/unit/math/tensor_tests.cpp
Labels: A-vm, S-ready-to-merge

#2291 implemented small integer types for used BLAS routines
  libs/math/src/linalg/blas/gemm_nn_novector.cpp
  libs/math/src/linalg/blas/gemm_nn_vector.cpp
  libs/math/src/linalg/blas/gemm_nt_novector.cpp
  libs/math/src/linalg/blas/gemm_nt_vector.cpp
  libs/math/src/linalg/blas/gemm_tn_novector.cpp
  libs/math/src/linalg/blas/gemm_tn_vector.cpp
  libs/math/src/linalg/blas/gemm_tt_novector.cpp
  libs/math/src/linalg/blas/gemm_tt_vector.cpp
  libs/math/src/linalg/blas/gemv_n_novector.cpp
  libs/math/src/linalg/blas/gemv_n_vector.cpp
  libs/math/src/linalg/blas/gemv_t_novector.cpp
  libs/math/src/linalg/blas/gemv_t_vector.cpp
  libs/ml/src/clustering/tsne.cpp
  libs/ml/src/ops/convolution_1d.cpp
  libs/ml/src/ops/convolution_2d.cpp
  libs/vectorise/include/vectorise/memory/parallel_dispatcher.hpp
Labels: S-ready-for-review, S-ready-to-merge

#2289 moved ml/core implementation to source
  libs/ml/include/ml/core/graph.hpp
  libs/ml/include/ml/core/node.hpp
  libs/ml/include/ml/core/subgraph.hpp
  libs/ml/include/ml/ops/placeholder.hpp
  libs/ml/src/core/graph.cpp
  libs/ml/src/core/node.cpp
  libs/ml/src/core/subgraph.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2302 Move dataloader implementation to source files
  libs/dmlf/examples/boston_housing_distributed_learning/main.cpp
  libs/dmlf/examples/boston_housing_multiprocess_distributed_learning/main.cpp
  libs/dmlf/examples/mnist_distributed_learning/main.cpp
  libs/dmlf/examples/mnist_multiprocess_distributed_learning/main.cpp
  libs/dmlf/include/dmlf/collective_learning/client_word2vec_algorithm.hpp
  libs/dmlf/include/dmlf/collective_learning/utilities/boston_housing_client_utilities.hpp
  libs/dmlf/include/dmlf/collective_learning/utilities/mnist_client_utilities.hpp
  libs/ml/examples/code2vec_dataloading/main.cpp
  libs/ml/examples/mnist_model/main.cpp
  libs/ml/examples/word2vec_SGNS_dataloader/main.cpp
  libs/ml/include/ml/dataloaders/code2vec_context_loaders/context_loader.hpp
  libs/ml/include/ml/dataloaders/dataloader.hpp
  libs/ml/include/ml/dataloaders/tensor_dataloader.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/sgns_w2v_dataloader.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/unigram_table.hpp
  libs/ml/include/ml/dataloaders/word2vec_loaders/w2v_dataloader.hpp
  libs/ml/src/dataloaders/code2vec_context_loaders/context_loader.cpp
  libs/ml/src/dataloaders/dataloader.cpp
  libs/ml/src/dataloaders/tensor_dataloader.cpp
  libs/ml/src/dataloaders/word2vec_loaders/sgns_w2v_dataloader.cpp
  libs/ml/src/dataloaders/word2vec_loaders/unigram_table.cpp
  libs/ml/src/dataloaders/word2vec_loaders/w2v_dataloader.cpp
  libs/ml/tests/unit/dataloader/code2vec_context_loader.cpp
  libs/ml/tests/unit/dataloader/skipgram_loader.cpp
  libs/ml/tests/unit/dataloader/tensor_dataloader.cpp
Labels: A-ml, S-ready-for-review, S-ready-to-merge

#2310 Fix vm-modules crypto example
  libs/ml/examples/crypto_price_prediction/main.cpp
  libs/vm-modules/examples/crypto_price_prediction/main.cpp
  libs/vm-modules/examples/crypto_price_prediction/script/bitcoin.etch
Labels: S-ready-to-merge

#2303 Refactor/ml 430 partial move graph builder implementations
  libs/dmlf/include/dmlf/collective_learning/client_algorithm.hpp
  libs/dmlf/include/dmlf/collective_learning/utilities/boston_housing_client_utilities.hpp
  libs/ml/benchmark/embeddings/embeddings.cpp
  libs/ml/examples/commodity_prediction/main.cpp
  libs/ml/examples/crypto_price_prediction/main.cpp
  libs/ml/examples/mnist_model/main.cpp
  libs/ml/include/ml/model/model.hpp
  libs/ml/include/ml/model/sequential.hpp
  libs/ml/include/ml/ops/subtract.hpp
  libs/ml/include/ml/serializers/ml_types.hpp
  libs/ml/include/ml/utilities/graph_builder.hpp
  libs/ml/src/ops/matrix_multiply.cpp
  libs/ml/src/ops/subtract.cpp
  libs/ml/src/utilities/graph_builder.cpp
  libs/ml/tests/unit/layers/PRelu.cpp
  libs/ml/tests/unit/layers/convolution_2d.cpp
  libs/ml/tests/unit/layers/layer_norm.cpp
  libs/ml/tests/unit/layers/multihead_attention.cpp
  libs/ml/tests/unit/layers/self_attention_encoder.cpp
  libs/ml/tests/unit/layers/skip_gram.cpp
  libs/ml/tests/unit/optimisation/sparse_optimisers.cpp
  libs/ml/tests/unit/serializers/ml_types.cpp
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/src/ml/graph.cpp
  libs/vm-modules/src/ml/model/model.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2299 Feature/ml 426 ml layers to source
  libs/ml/benchmark/embeddings/embeddings.cpp
  libs/ml/benchmark/serialization/serialization.cpp
  libs/ml/benchmark/training/training.cpp
  libs/ml/examples/commodity_prediction/main.cpp
  libs/ml/examples/crypto_price_prediction/main.cpp
  libs/ml/examples/mnist/main.cpp
  libs/ml/examples/word2vec_SGNS_dataloader/main.cpp
  libs/ml/include/ml/core/graph.hpp
  libs/ml/include/ml/layers/PRelu.hpp
  libs/ml/include/ml/layers/convolution_1d.hpp
  libs/ml/include/ml/layers/convolution_2d.hpp
  libs/ml/include/ml/layers/fully_connected.hpp
  libs/ml/include/ml/layers/multihead_attention.hpp
  libs/ml/include/ml/layers/normalisation/layer_norm.hpp
  libs/ml/include/ml/layers/scaled_dot_product_attention.hpp
  libs/ml/include/ml/layers/self_attention_encoder.hpp
  libs/ml/include/ml/layers/skip_gram.hpp
  libs/ml/include/ml/ops/activation.hpp
  libs/ml/include/ml/utilities/bert_utilities.hpp
  libs/ml/src/layers/PRelu.cpp
  libs/ml/src/layers/convolution_1d.cpp
  libs/ml/src/layers/convolution_2d.cpp
  libs/ml/src/layers/fully_connected.cpp
  libs/ml/src/layers/multihead_attention.cpp
  libs/ml/src/layers/normalisation/layer_norm.cpp
  libs/ml/src/layers/scaled_dot_product_attention.cpp
  libs/ml/src/layers/self_attention_encoder.cpp
  libs/ml/src/layers/skip_gram.cpp
  libs/ml/src/ops/activation.cpp
  libs/ml/src/utilities/graph_builder.cpp
  libs/ml/tests/unit/graph/graph.cpp
  libs/ml/tests/unit/layers/PRelu.cpp
  libs/ml/tests/unit/layers/convolution_1d.cpp
  libs/ml/tests/unit/layers/convolution_2d.cpp
  libs/ml/tests/unit/layers/fully_connected.cpp
  libs/ml/tests/unit/layers/layer_norm.cpp
  libs/ml/tests/unit/layers/multihead_attention.cpp
  libs/ml/tests/unit/layers/scaled_dot_product_attention.cpp
  libs/ml/tests/unit/layers/self_attention_encoder.cpp
  libs/ml/tests/unit/layers/skip_gram.cpp
  libs/ml/tests/unit/training/basic_training.cpp
  libs/vm-modules/src/ml/graph.cpp
  libs/vm-modules/src/ml/model/model.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2249 Improvement/add block by pointer
  libs/core/include/core/serializers/base_types.hpp
  libs/ledger/include/ledger/chain/block.hpp
  libs/ledger/include/ledger/chain/block_coordinator.hpp
  libs/ledger/include/ledger/chain/main_chain.hpp
  libs/ledger/include/ledger/chain/time_travelogue.hpp
  libs/ledger/include/ledger/consensus/consensus.hpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_client_interface.hpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_protocol.hpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_service.hpp
  libs/ledger/include/ledger/testing/block_generator.hpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/src/consensus/consensus.cpp
  libs/ledger/src/fees/fee_manager.cpp
  libs/ledger/src/protocols/main_chain_rpc_service.cpp
  libs/ledger/src/storage_unit/transaction_store_sync_protocol.cpp
  libs/ledger/src/storage_unit/transaction_store_sync_service.cpp
  libs/ledger/src/upow/naive_synergetic_miner.cpp
  libs/ledger/tests/chain/main_chain_subtree_tests.cpp
  libs/ledger/tests/notarisation/notarisation_tests.cpp
  libs/meta/include/meta/value_util.hpp
  libs/network/include/network/p2pservice/p2p_http_interface.hpp
Labels: A-ledger, C-improvement, S-ready-for-review, S-ready-to-merge

#2305 Feature/ml 428 optimisation to src
  libs/ml/examples/commodity_prediction/main.cpp
  libs/ml/include/ml/optimisation/adagrad_optimiser.hpp
  libs/ml/include/ml/optimisation/adam_optimiser.hpp
  libs/ml/include/ml/optimisation/lazy_adam_optimiser.hpp
  libs/ml/include/ml/optimisation/learning_rate_params.hpp
  libs/ml/include/ml/optimisation/momentum_optimiser.hpp
  libs/ml/include/ml/optimisation/optimiser.hpp
  libs/ml/include/ml/optimisation/rmsprop_optimiser.hpp
  libs/ml/include/ml/optimisation/sgd_optimiser.hpp
  libs/ml/include/ml/serializers/ml_types.hpp
  libs/ml/src/optimisation/adagrad_optimiser.cpp
  libs/ml/src/optimisation/adam_optimiser.cpp
  libs/ml/src/optimisation/lazy_adam_optimiser.cpp
  libs/ml/src/optimisation/momentum_optimiser.cpp
  libs/ml/src/optimisation/optimiser.cpp
  libs/ml/src/optimisation/rmsprop_optimiser.cpp
  libs/ml/src/optimisation/sgd_optimiser.cpp
Labels: S-ready-to-merge

#2317 Backport of release fixes
  libs/beacon/src/beacon_service.cpp
  libs/bloom-filter/src/progressive_bloom_filter.cpp
  libs/constellation/src/constellation.cpp
  libs/core/src/byte_array/const_byte_array.cpp
  libs/ledger/include/ledger/chain/block.hpp
  libs/ledger/include/ledger/chain/block_coordinator.hpp
  libs/ledger/include/ledger/chain/main_chain.hpp
  libs/ledger/include/ledger/consensus/consensus.hpp
  libs/ledger/src/chain/block.cpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/src/consensus/consensus.cpp
  libs/ledger/src/executor.cpp
  libs/ledger/src/miner/basic_miner.cpp
  libs/ledger/src/protocols/main_chain_rpc_service.cpp
  libs/ledger/tests/chain/block_coordinator_tests.cpp
  libs/ledger/tests/chain/main_chain_tests.cpp
  libs/ledger/tests/consensus/pos_tests.cpp
  libs/ledger/tests/notarisation/notarisation_tests.cpp
  libs/muddle/src/muddle.cpp
  libs/network/include/network/generics/milli_timer.hpp
Labels: S-ready-to-merge

#2304 ML-427: moved model implementations to source files
  libs/dmlf/include/dmlf/collective_learning/client_word2vec_algorithm.hpp
  libs/ml/include/ml/model/model.hpp
  libs/ml/include/ml/model/model_config.hpp
  libs/ml/include/ml/model/sequential.hpp
  libs/ml/include/ml/optimisation/learning_rate_params.hpp
  libs/ml/include/ml/optimisation/optimiser.hpp
  libs/ml/include/ml/optimisation/sgd_optimiser.hpp
  libs/ml/include/ml/serializers/model.hpp
  libs/ml/include/ml/serializers/model_config.hpp
  libs/ml/include/ml/serializers/sequential.hpp
  libs/ml/src/model/model.cpp
  libs/ml/src/model/sequential.cpp
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/src/ml/model/model.cpp
Labels: S-ready-for-review

#2318 Added functions for layer name finding and reporting
  libs/ml/include/ml/core/graph.hpp
  libs/ml/src/core/graph.cpp
  libs/ml/tests/unit/graph/graph.cpp
Labels: A-ml, S-ready-to-merge

#2314 enable testing of POS at E2E level
  scripts/end_to_end_test/end_to_end_test.yaml
Labels: S-ready-to-merge

#2301 Refactor/ml 467 unify ml ops serialisation tests
  libs/math/include/math/one_hot.hpp
  libs/ml/include/ml/utilities/graph_builder.hpp
  libs/ml/src/utilities/graph_builder.cpp
  libs/ml/tests/unit/graph/graph_every_op.cpp
  libs/ml/tests/unit/layers/PRelu.cpp
  libs/ml/tests/unit/layers/convolution_1d.cpp
  libs/ml/tests/unit/layers/convolution_2d.cpp
  libs/ml/tests/unit/layers/fully_connected.cpp
  libs/ml/tests/unit/layers/layer_norm.cpp
  libs/ml/tests/unit/layers/multihead_attention.cpp
  libs/ml/tests/unit/layers/scaled_dot_product_attention.cpp
  libs/ml/tests/unit/layers/self_attention_encoder.cpp
  libs/ml/tests/unit/layers/skip_gram.cpp
  libs/ml/tests/unit/ops/abs.cpp
  libs/ml/tests/unit/ops/add.cpp
  libs/ml/tests/unit/ops/avg_pool_1d.cpp
  libs/ml/tests/unit/ops/avg_pool_2d.cpp
  libs/ml/tests/unit/ops/concatenate.cpp
  libs/ml/tests/unit/ops/constant.cpp
  libs/ml/tests/unit/ops/convolution_1d.cpp
  libs/ml/tests/unit/ops/convolution_2d.cpp
  libs/ml/tests/unit/ops/divide.cpp
  libs/ml/tests/unit/ops/embeddings.cpp
  libs/ml/tests/unit/ops/exp.cpp
  libs/ml/tests/unit/ops/flatten.cpp
  libs/ml/tests/unit/ops/layer_norm.cpp
  libs/ml/tests/unit/ops/log.cpp
  libs/ml/tests/unit/ops/mask_fill.cpp
  libs/ml/tests/unit/ops/matrix_multiply.cpp
  libs/ml/tests/unit/ops/max_pool.cpp
  libs/ml/tests/unit/ops/max_pool_1d.cpp
  libs/ml/tests/unit/ops/max_pool_2d.cpp
  libs/ml/tests/unit/ops/maximum.cpp
  libs/ml/tests/unit/ops/multiply.cpp
  libs/ml/tests/unit/ops/one_hot.cpp
  libs/ml/tests/unit/ops/placeholder.cpp
  libs/ml/tests/unit/ops/prelu_op.cpp
  libs/ml/tests/unit/ops/reduce_mean.cpp
  libs/ml/tests/unit/ops/reshape.cpp
  libs/ml/tests/unit/ops/slice.cpp
  libs/ml/tests/unit/ops/sqrt.cpp
  libs/ml/tests/unit/ops/squeeze.cpp
  libs/ml/tests/unit/ops/strided_slice.cpp
  libs/ml/tests/unit/ops/subtract.cpp
  libs/ml/tests/unit/ops/switch.cpp
  libs/ml/tests/unit/ops/tanh.cpp
  libs/ml/tests/unit/ops/top_k.cpp
  libs/ml/tests/unit/ops/transpose_op.cpp
  libs/ml/tests/unit/ops/weights.cpp
  libs/ml/tests/unit/serializers/graph.cpp
  libs/ml/tests/unit/serializers/layers.cpp
  libs/ml/tests/unit/serializers/ml_types.cpp
  libs/ml/tests/unit/serializers/ops.cpp
  libs/ml/tests/unit/serializers/serializer_includes.hpp
  libs/ml/tests/unit/serializers/serializer_test_utils.hpp
Labels: S-ready-for-review, S-ready-to-merge

#2319 Deprecated StateDict
  libs/ml/examples/bert_for_finetune/main.cpp
  libs/ml/examples/bert_save_load_pretrained_model_example/main.cpp
  libs/ml/examples/bert_simple_cls_example/main.cpp
  libs/ml/include/ml/core/graph.hpp
  libs/ml/include/ml/ops/trainable.hpp
  libs/ml/include/ml/ops/weights.hpp
  libs/ml/include/ml/serializers/ml_types.hpp
  libs/ml/include/ml/state_dict.hpp
  libs/ml/include/ml/utilities/bert_utilities.hpp
  libs/ml/src/core/graph.cpp
  libs/ml/src/ops/weights.cpp
  libs/ml/tests/CMakeLists.txt
  libs/ml/tests/unit/graph/graph.cpp
  libs/ml/tests/unit/layers/PRelu.cpp
  libs/ml/tests/unit/layers/convolution_1d.cpp
  libs/ml/tests/unit/layers/convolution_2d.cpp
  libs/ml/tests/unit/layers/fully_connected.cpp
  libs/ml/tests/unit/layers/layer_norm.cpp
  libs/ml/tests/unit/ops/weights.cpp
  libs/ml/tests/unit/serializers/graph.cpp
  libs/ml/tests/unit/state/state_dict.cpp
  libs/vm-modules/examples/commodity_prediction/script/graph_saver.etch
  libs/vm-modules/include/vm_modules/ml/graph.hpp
  libs/vm-modules/src/ml/graph.cpp
Labels: A-ml, A-vm, S-ready-to-merge

#2321 Added tests that ensures GetWeightReferences has always same order
  libs/ml/tests/unit/graph/graph.cpp
Labels: A-ml, S-ready-for-review

#2312 Improvement/try-catch consensus
  libs/constellation/include/constellation/constellation.hpp
  libs/constellation/src/constellation.cpp
  libs/ledger/include/ledger/consensus/consensus.hpp
  libs/ledger/include/ledger/consensus/consensus_interface.hpp
  libs/ledger/include/ledger/consensus/simulated_pow_consensus.hpp
  libs/ledger/include/ledger/miner/transaction_layout_queue.hpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_service.hpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/consensus/consensus.cpp
  libs/ledger/src/consensus/simulated_pow_consensus.cpp
  libs/ledger/src/miner/basic_miner.cpp
  libs/ledger/src/miner/transaction_layout_queue.cpp
  libs/ledger/src/protocols/main_chain_rpc_service.cpp
  libs/ledger/tests/chain/main_chain_service_tests.cpp
  libs/ledger/tests/chain/mock_consensus.hpp
  libs/ledger/tests/consensus/pos_tests.cpp
  libs/ledger/tests/consensus/simulated_pow_tests.cpp
  libs/ledger/tests/notarisation/notarisation_tests.cpp
  libs/logging/src/logging.cpp
Labels: A-ledger, C-improvement, S-ready-for-review, S-ready-to-merge

#2329 Fix scenario where reverting after a crash to a ledger with no TXs
  libs/ledger/src/storage_unit/storage_unit_client.cpp
Labels: S-ready-to-merge

#2316 single object store
  libs/storage/include/storage/single_object_store.hpp
  libs/storage/src/single_object_store.cpp
  libs/storage/tests/unit/single_object_store_tests.cpp
Labels: S-ready-to-merge

#2328 Remove unnecessary crypto include
  libs/muddle/CMakeLists.txt
  libs/network/CMakeLists.txt
  libs/network/include/network/uri.hpp
  libs/oef-core/CMakeLists.txt
  libs/variant/CMakeLists.txt
  libs/variant/include/variant/variant.hpp
Labels: S-ready-to-merge

#2340 Pin lark parser dependency (quick fix)
  scripts/install-test-dependencies.sh
Labels: S-ready-to-merge

#2338 Backport: Disable message signing for internal muddle comms
  libs/constellation/src/constellation.cpp
  libs/ledger/src/storage_unit/lane_service.cpp
  libs/muddle/include/muddle/muddle_interface.hpp
  libs/muddle/internal/muddle.hpp
  libs/muddle/internal/router.hpp
  libs/muddle/src/muddle.cpp
  libs/muddle/src/muddle_interface.cpp
  libs/muddle/src/router.cpp
Labels: S-ready-to-merge

#2339 Disable message signing for internal muddle comms
  libs/constellation/src/constellation.cpp
  libs/ledger/src/storage_unit/lane_service.cpp
  libs/muddle/include/muddle/muddle_interface.hpp
  libs/muddle/internal/muddle.hpp
  libs/muddle/internal/router.hpp
  libs/muddle/src/muddle.cpp
  libs/muddle/src/muddle_interface.cpp
  libs/muddle/src/router.cpp
Labels: S-ready-to-merge

#2332 Feature/ml 451 vectorise small ints
  libs/math/include/math/matrix_operations.hpp
  libs/math/tests/unit/vectors/vector_tests.cpp
  libs/vectorise/include/vectorise/arch/avx2.hpp
  libs/vectorise/include/vectorise/arch/avx2/info.hpp
  libs/vectorise/include/vectorise/arch/avx2/math/max.hpp
  libs/vectorise/include/vectorise/arch/avx2/math/min.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_int16.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_int32.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_int64.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_int8.hpp
  libs/vectorise/include/vectorise/vectorise.hpp
Labels: A-maths, C-optimisation, S-ready-for-review, S-ready-to-merge

#2280 Improvement/expo backtrace
  libs/core/include/core/macros.hpp
  libs/ledger/include/ledger/protocols/main_chain_rpc_service.hpp
  libs/ledger/include/ledger/testing/block_generator.hpp
  libs/ledger/src/chain/block_coordinator.cpp
  libs/ledger/src/chain/main_chain.cpp
  libs/ledger/src/protocols/main_chain_rpc_service.cpp
  libs/ledger/src/testing/block_generator.cpp
  libs/ledger/tests/CMakeLists.txt
  libs/ledger/tests/chain/fake_muddle_endpoint.cpp
  libs/ledger/tests/chain/fake_muddle_endpoint.hpp
  libs/ledger/tests/chain/main_chain_service_tests.cpp
  libs/ledger/tests/sync/main_chain_sync_test.cpp
  libs/ledger/tests/unit/digest_matcher.hpp
  libs/ledger/tests/unit/fake_muddle_endpoint.hpp
  libs/ledger/tests/unit/mock_consensus.hpp
  libs/ledger/tests/unit/mock_main_chain_rpc_client.hpp
  libs/ledger/tests/unit/mock_muddle_endpoint.hpp
  libs/ledger/tests/unit/mock_trust_system.hpp
  scripts/install-test-dependencies.sh
Labels: A-ledger, C-improvement, S-ready-for-review, S-ready-to-merge

#2336 Add Simple TX Generator
  apps/storage-tools/CMakeLists.txt
  apps/storage-tools/tx_gen.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2323 Ops-based charge estimation framework skeleton
  libs/ml/include/ml/charge_estimation/ops/constants.hpp
  libs/ml/include/ml/charge_estimation/types.hpp
  libs/ml/include/ml/core/graph.hpp
  libs/ml/include/ml/core/node.hpp
  libs/ml/include/ml/layers/fully_connected.hpp
  libs/ml/include/ml/model/model.hpp
  libs/ml/include/ml/ops/add.hpp
  libs/ml/include/ml/ops/flatten.hpp
  libs/ml/include/ml/ops/matrix_multiply.hpp
  libs/ml/include/ml/ops/ops.hpp
  libs/ml/include/ml/ops/placeholder.hpp
  libs/ml/include/ml/ops/subtract.hpp
  libs/ml/include/ml/ops/weights.hpp
  libs/ml/src/core/graph.cpp
  libs/ml/src/core/node.cpp
  libs/ml/src/layers/convolution_2d.cpp
  libs/ml/src/layers/fully_connected.cpp
  libs/ml/src/model/model.cpp
  libs/ml/src/ops/add.cpp
  libs/ml/src/ops/flatten.cpp
  libs/ml/src/ops/matrix_multiply.cpp
  libs/ml/src/ops/placeholder.cpp
  libs/ml/src/ops/subtract.cpp
  libs/ml/src/ops/weights.cpp
  libs/ml/tests/unit/graph/graph.cpp
  libs/ml/tests/unit/model/sequential_test.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2352 added charge estimation for activations
  libs/ml/include/ml/charge_estimation/ops/constants.hpp
  libs/ml/include/ml/ops/activations/dropout.hpp
  libs/ml/include/ml/ops/activations/elu.hpp
  libs/ml/include/ml/ops/activations/gelu.hpp
  libs/ml/include/ml/ops/activations/leaky_relu.hpp
  libs/ml/include/ml/ops/activations/logsigmoid.hpp
  libs/ml/include/ml/ops/activations/logsoftmax.hpp
  libs/ml/include/ml/ops/activations/randomised_relu.hpp
  libs/ml/include/ml/ops/activations/relu.hpp
  libs/ml/include/ml/ops/activations/sigmoid.hpp
  libs/ml/include/ml/ops/activations/softmax.hpp
  libs/ml/src/ops/activations/dropout.cpp
  libs/ml/src/ops/activations/elu.cpp
  libs/ml/src/ops/activations/gelu.cpp
  libs/ml/src/ops/activations/leaky_relu.cpp
  libs/ml/src/ops/activations/logsigmoid.cpp
  libs/ml/src/ops/activations/logsoftmax.cpp
  libs/ml/src/ops/activations/randomised_relu.cpp
  libs/ml/src/ops/activations/relu.cpp
  libs/ml/src/ops/activations/sigmoid.cpp
  libs/ml/src/ops/activations/softmax.cpp
Labels: S-ready-to-merge

#2347 Added try catch for vmmodel
  libs/vm-modules/src/ml/model/model.cpp
Labels: A-vm, S-ready-for-review

#2353 added charge estimation for losses
  libs/ml/include/ml/charge_estimation/ops/constants.hpp
  libs/ml/include/ml/ops/loss_functions/cross_entropy_loss.hpp
  libs/ml/include/ml/ops/loss_functions/mean_square_error_loss.hpp
  libs/ml/include/ml/ops/loss_functions/softmax_cross_entropy_loss.hpp
  libs/ml/src/ops/loss_functions/cross_entropy_loss.cpp
  libs/ml/src/ops/loss_functions/mean_square_error_loss.cpp
  libs/ml/src/ops/loss_functions/softmax_cross_entropy_loss.cpp
Labels: S-ready-to-merge

#2351 Feature/ml 480 conv layer charge estimation
  libs/ml/include/ml/layers/convolution_1d.hpp
  libs/ml/include/ml/layers/convolution_2d.hpp
  libs/ml/include/ml/ops/convolution_1d.hpp
  libs/ml/include/ml/ops/convolution_2d.hpp
  libs/ml/src/layers/convolution_1d.cpp
  libs/ml/src/layers/convolution_2d.cpp
  libs/ml/src/ops/convolution_1d.cpp
  libs/ml/src/ops/convolution_2d.cpp
Labels: S-ready-for-review, S-ready-to-merge

#2356 Feature/ml 230 fixedpoint optimisations
  libs/math/tests/unit/vectors/vector_tests.cpp
  libs/vectorise/include/vectorise/arch/avx2/register_fixed32.hpp
  libs/vectorise/include/vectorise/arch/avx2/register_fixed64.hpp
  libs/vectorise/include/vectorise/fixed_point/fixed_point.hpp
Labels: A-maths, C-optimisation, S-ready-for-review, S-ready-to-merge

#2331 prevent out of order entropy gen
  libs/beacon/include/beacon/beacon_service.hpp
  libs/beacon/src/beacon_service.cpp
Labels: S-ready-to-merge

#2363 added charge estimations to ops
  libs/ml/include/ml/charge_estimation/ops/constants.hpp
  libs/ml/include/ml/ops/abs.hpp
  libs/ml/include/ml/ops/concatenate.hpp
  libs/ml/include/ml/ops/dataholder.hpp
  libs/ml/include/ml/ops/divide.hpp
  libs/ml/include/ml/ops/embeddings.hpp
  libs/ml/include/ml/ops/exp.hpp
  libs/ml/include/ml/ops/layer_norm.hpp
  libs/ml/include/ml/ops/log.hpp
  libs/ml/include/ml/ops/mask_fill.hpp
  libs/ml/include/ml/ops/maximum.hpp
  libs/ml/include/ml/ops/multiply.hpp
  libs/ml/include/ml/ops/one_hot.hpp
  libs/ml/include/ml/ops/prelu_op.hpp
  libs/ml/include/ml/ops/reduce_mean.hpp
  libs/ml/include/ml/ops/reshape.hpp
  libs/ml/include/ml/ops/slice.hpp
  libs/ml/include/ml/ops/sqrt.hpp
  libs/ml/include/ml/ops/squeeze.hpp
  libs/ml/include/ml/ops/strided_slice.hpp
  libs/ml/include/ml/ops/tanh.hpp
  libs/ml/include/ml/ops/top_k.hpp
  libs/ml/include/ml/ops/transpose.hpp
  libs/ml/src/ops/abs.cpp
  libs/ml/src/ops/concatenate.cpp
  libs/ml/src/ops/dataholder.cpp
  libs/ml/src/ops/divide.cpp
  libs/ml/src/ops/embeddings.cpp
  libs/ml/src/ops/exp.cpp
  libs/ml/src/ops/layer_norm.cpp
  libs/ml/src/ops/log.cpp
  libs/ml/src/ops/mask_fill.cpp
  libs/ml/src/ops/maximum.cpp
  libs/ml/src/ops/multiply.cpp
  libs/ml/src/ops/one_hot.cpp
  libs/ml/src/ops/prelu_op.cpp
  libs/ml/src/ops/reduce_mean.cpp
  libs/ml/src/ops/reshape.cpp
  libs/ml/src/ops/slice.cpp
  libs/ml/src/ops/sqrt.cpp
  libs/ml/src/ops/squeeze.cpp
  libs/ml/src/ops/strided_slice.cpp
  libs/ml/src/ops/tanh.cpp
  libs/ml/src/ops/top_k.cpp
  libs/ml/src/ops/transpose.cpp
Labels: S-ready-to-merge

#2348 Feature/reactor alerts
  libs/core/CMakeLists.txt
  libs/core/include/core/periodic_runnable.hpp
  libs/core/include/core/reactor.hpp
  libs/core/include/core/runnable.hpp
  libs/core/include/core/serializers/clock_serializers.hpp
  libs/core/include/core/state_machine.hpp
  libs/core/include/core/state_machine_interface.hpp
  libs/core/src/periodic_runnable.cpp
  libs/core/src/reactor.cpp
  libs/core/tests/integration/state_machine_tests.cpp
  libs/moment/CMakeLists.txt
  libs/moment/include/moment/clock_interfaces.hpp
  libs/moment/src/clocks.cpp
  libs/muddle/internal/kademlia/table.hpp
  libs/muddle/internal/promise_runnable.hpp
  libs/muddle/src/promise_runnable.cpp
Labels: S-ready-to-merge

#2337 Deploy Python tooling with pipenv
  Jenkinsfile
  Pipfile
  Pipfile.lock
  scripts/install-test-dependencies.sh
Labels: S-do-not-merge, S-ready-for-review

#2355 added charge estimation for pooling ops
  libs/ml/include/ml/ops/avg_pool_1d.hpp
  libs/ml/include/ml/ops/avg_pool_2d.hpp
  libs/ml/include/ml/ops/max_pool_1d.hpp
  libs/ml/include/ml/ops/max_pool_2d.hpp
  libs/ml/src/ops/avg_pool_1d.cpp
  libs/ml/src/ops/avg_pool_2d.cpp
  libs/ml/src/ops/max_pool_1d.cpp
  libs/ml/src/ops/max_pool_2d.cpp
Labels: S-ready-to-merge

#2366 Fix teardown segfault if no genesis file
  libs/constellation/src/constellation.cpp
Labels: S-ready-to-merge

#2364 Feature/ml 253 add keras style pooling layers
  libs/ml/src/ops/convolution_1d.cpp
  libs/ml/src/ops/max_pool_1d.cpp
  libs/vm-modules/include/vm_modules/ml/model/model.hpp
  libs/vm-modules/include/vm_modules/ml/model/model_estimator.hpp
  libs/vm-modules/src/ml/model/model.cpp
  libs/vm-modules/src/ml/model/model_estimator.cpp
  libs/vm-modules/tests/unit/ml/ml_model_tests.cpp
Labels: S-ready-to-merge

#2373 Fix legacy issues with protobuf message size accessors
  cmake/BuildTargets.cmake
Labels: S-ready-for-review, S-ready-to-merge

#2360 Miscellaneous changes
  libs/crypto/tests/unit/openssl_memory_shared_ptr_test.cpp
  libs/ledger/include/ledger/consensus/stake_manager.hpp
  libs/ledger/src/transaction_validator.cpp
  libs/ledger/tests/unit/transaction_validator_tests.cpp
  libs/semanticsearch/CMakeLists.txt
  libs/semanticsearch/examples/CMakeLists.txt
  libs/telemetry/CMakeLists.txt
  libs/vm-modules/tests/unit/vm_modules_tests.cpp
  scripts/end_to_end_test/end_to_end_test.yaml
Labels: S-ready-to-merge

#2361 Fix serializer element count; typos
  libs/core/include/core/serializers/array_interface.hpp
  libs/core/include/core/serializers/map_interface.hpp
  libs/ledger/include/ledger/consensus/stake_manager.hpp
Labels: S-ready-to-merge

#2372 Only use angle brackets for system third-party headers
  apps/oef-core/MtCore.cpp
  apps/oef-search/MtSearch.cpp
  libs/crypto/include/crypto/openssl_common.hpp
  libs/crypto/include/crypto/openssl_context_detail.hpp
  libs/crypto/include/crypto/openssl_memory_detail.hpp
  libs/crypto/src/openssl_hasher.cpp
  libs/oef-core/include/oef-core/comms/EndpointSSL.hpp
  libs/oef-core/include/oef-core/comms/public_key_utils.hpp
  libs/oef-core/include/oef-core/oef-functions/InitialSecureHandshakeTaskFactory.hpp
  libs/oef-core/src/comms/EndpointSSL.cpp
Labels: S-ready-to-merge
